- stable/localvolumeprovisioner/Chart.yaml
- stable/localvolumeprovisioner/templates/NOTES.txt
- stable/localvolumeprovisioner/templates/deployment.yaml
- stable/localvolumeprovisioner/templates/service.yaml
- stable/localvolumeprovisioner/templates/storageclass.yaml
- stable/localvolumeprovisioner/values.yaml
This chart will be used by the local volume provisioner konvoy addon.
> Add a chart for the local volume provisioner

- Makefile
We need to set the url of the chart repository to get the index with the appropriate entry.
> Makefile: set the url of chart repository

- Makefile
This PR allows the `publish` target to update the forked repository.
TODO:
> Makefile: publish to fork

- Makefile
trying to help fix the publish issue that arouse earlier.
> attempting to fix make publish

- stable/kommander/Chart.yaml
- stable/kommander/templates/deployment.yaml
- stable/kommander/templates/service.yaml
- stable/kommander/templates/serviceaccount.yaml
Use Release.namespace instead of hardcoding the namespace
> Use Release.namespace to pass the namespace name to kommander

- staging/dex-k8s-authenticator/Chart.yaml
- staging/dex-k8s-authenticator/html-templates/index.html
- staging/dex-k8s-authenticator/html-templates/kubeconfig.html
- staging/dex-k8s-authenticator/html-templates/linux-mac-common.html
- staging/dex-k8s-authenticator/html-templates/linux-tab.html
- staging/dex-k8s-authenticator/html-templates/mac-tab.html
- staging/dex-k8s-authenticator/html-templates/windows-tab.html
- staging/dex-k8s-authenticator/templates/ca_secrets.yaml
- staging/dex-k8s-authenticator/templates/configmap.yaml
- staging/dex-k8s-authenticator/templates/configmap_templates.yaml
- staging/dex-k8s-authenticator/templates/deployment.yaml
- staging/dex-k8s-authenticator/templates/ingress.yaml
- staging/dex-k8s-authenticator/templates/service.yaml
A new version of the chart that deploys authenticator version that does not expose OAuth client secret to the authenticated user.
To override HTML templates in the official container this PR introduces new `ConfigMap` that injects custom version of HTML templates into the authenticator container.
JIRA: https://jira.mesosphere.com/browse/DCOS-56105
> dex-k8s-authenticator: add custom templates

- staging/traefik-forward-auth/.helmignore
- staging/traefik-forward-auth/Chart.yaml
- staging/traefik-forward-auth/LICENSE
- staging/traefik-forward-auth/README.md
- staging/traefik-forward-auth/templates/NOTES.txt
- staging/traefik-forward-auth/templates/_helpers.tpl
- staging/traefik-forward-auth/templates/configmap.yaml
- staging/traefik-forward-auth/templates/deployment.yaml
- staging/traefik-forward-auth/templates/ingress.yaml
- staging/traefik-forward-auth/templates/secret.yaml
- staging/traefik-forward-auth/templates/service.yaml
- staging/traefik-forward-auth/templates/tests/test-connection.yaml
- staging/traefik-forward-auth/values.yaml
Chart for traefik-forward-auth
> Add traefik-forward-auth chart

- staging/dex-k8s-authenticator/Chart.yaml
- staging/dex-k8s-authenticator/values.yaml
Reduce some timeout values for readiness probe and liveness probe.
> dex-k8s-authenticator: reduce timeout

- stable/kommander/Chart.yaml
- stable/kommander/templates/ingress.yaml
- stable/kommander/values.yaml
- stable/opsportal/Chart.yaml
- stable/opsportal/templates/ingress-opsportal.yaml
I have the feeling we want to change this too :)
> stable: add X-Forwarded-User to opsportal and kommander

- Makefile
found an error in the makefile
> make file needed to be fixed

- stable/kommander/Chart.yaml
- stable/kommander/templates/deployment.yaml
- stable/kommander/values.yaml
This release is aware of its namespace, therefore we need to add an
environment variable with the namespace passed to it
> chore(kommander): update kommander to 1.40.0

- stable/awsebscsiprovisioner/Chart.yaml
- stable/awsebscsiprovisioner/templates/storageclass.yaml
- stable/awsebsprovisioner/Chart.yaml
- stable/awsebsprovisioner/templates/storageclass.yaml
- stable/localpathprovisioner/Chart.yaml
- stable/localpathprovisioner/templates/storageclass.yaml
- stable/localvolumeprovisioner/Chart.yaml
- stable/localvolumeprovisioner/templates/storageclass.yaml
because it only works when the boolean is quoted
> change all .storageclass.isDefault

- staging/prometheus-operator/Chart.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/apiserver.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/controlmanager.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/elasticsearchdashboard.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/fluentbitdashboard.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/grafanadashboard.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/kubelet.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/localvolumeprovisioner.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/localvolumeusage.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/prometheusoverview.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/scheduler.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/traefikdashboard.yaml
- staging/prometheus-operator/templates/mesosphere-hooks/post-install-hooks.yaml
- staging/prometheus-operator/values.yaml
- Post install hook created
- Fix indentation problem
> [prometheus-operator] post install hook created, spacing fixed

- staging/traefik-forward-auth/Chart.yaml
- staging/traefik-forward-auth/templates/deployment.yaml
- staging/traefik-forward-auth/templates/hooks.yaml
- staging/traefik-forward-auth/templates/rolebinding.yaml
- staging/traefik-forward-auth/templates/secret.yaml
- staging/traefik-forward-auth/values.yaml
Generating `extra-steps` secret with hooks.
> tfa: create secret as hooks

- staging/prometheus-operator/Chart.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/konvoyuidashboard.yaml
- staging/prometheus-operator/values.yaml
Dashboard for Konvoy UI (the bug causing the service to always report as down should be fixed in: https://github.com/mesosphere/kommander/pull/251)
> Add Konvoy UI dashboard

- staging/prometheus-operator/Chart.yaml
- staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/elasticsearchdashboard.yaml
Update ES dashboard to latest revision (https://grafana.com/grafana/dashboards/2322) and fix a syntax error that was preventing the dashboard from getting loaded
> Update ES dashboard and fix syntax error

- staging/knative/charts/eventing-sources/Chart.yaml
- staging/knative/charts/eventing-sources/charts/github/Chart.yaml
- staging/knative/charts/eventing-sources/charts/github/LICENSE
- staging/knative/charts/eventing-sources/charts/github/templates/clusterrole.yaml
- staging/knative/charts/eventing-sources/charts/github/templates/clusterrolebinding.yaml
- staging/knative/charts/eventing-sources/charts/github/templates/controller-service.yaml
- staging/knative/charts/eventing-sources/charts/github/templates/controller.yaml
- staging/knative/charts/eventing-sources/charts/github/templates/githubsource.yaml
- staging/knative/charts/eventing-sources/charts/github/templates/namespace.yaml
- staging/knative/charts/eventing-sources/charts/github/templates/serviceaccount.yaml
- staging/knative/charts/eventing-sources/charts/github/values.yaml
- staging/knative/charts/eventing-sources/values.yaml
We used a custom controller image to include the following fix:
https://github.com/knative/eventing-contrib/pull/489
JIRA: https://jira.mesosphere.com/browse/DCOS-56869
> Added a chart for github eventing source.

- stable/opsportal/Chart.yaml
- stable/opsportal/values.yaml
> opsportla: fix image tag

- stable/opsportal/Chart.yaml
- stable/opsportal/templates/deployment-bearerproxy.yaml
- stable/opsportal/templates/landing.yaml
- stable/opsportal/values.yaml
Added ability to provide `resources:` in opsportal.
> opsportal: add pod resource:

- stable/kommander/Chart.yaml
- stable/kommander/templates/hooks-roles.yaml
- stable/kommander/templates/roles.yaml
make kommander idempontent by recreating SA if reinstalling also make it obvious what items are hooks by moving that SA creation to its own file
> chore: make kommander idempotent

- staging/velero/Chart.yaml
- staging/velero/templates/deployment.yaml
- staging/velero/templates/miniobackend.yaml
it's now available officially and fixes a bug
which required a fork earlier
> update minio to use the official one

- README.md
- staging/gatekeeper/.helmignore
- staging/gatekeeper/Chart.yaml
- staging/gatekeeper/templates/_helpers.tpl
- staging/gatekeeper/templates/clusterrole.yaml
- staging/gatekeeper/templates/clusterrolebinding.yaml
- staging/gatekeeper/templates/config-crd.yaml
- staging/gatekeeper/templates/constraint-template-crd.yaml
- staging/gatekeeper/templates/deployment.yaml
- staging/gatekeeper/templates/service.yaml
- staging/gatekeeper/templates/serviceaccount.yaml
- staging/gatekeeper/templates/tests/test-connection.yaml
- staging/gatekeeper/templates/validatingwebhook.yaml
- staging/gatekeeper/values.yaml
This will be pushed upstream ASAP but we would like
to include it in Mesosphere charts repo quickly and
demo it for customers.
> feat: Add gatekeeper chart

- staging/gatekeeper/Chart.yaml
- staging/gatekeeper/README.md
- staging/gatekeeper/templates/_helpers.tpl
- staging/gatekeeper/templates/deployment.yaml
- staging/gatekeeper/templates/validatingwebhook.yaml
- staging/gatekeeper/values.yaml
Also adds more configurability of webhook rules.
> [staging/gatekeeper] Cert manager integration

- staging/kubeaddons-catalog/Chart.yaml
- staging/kubeaddons-catalog/templates/deployment.yaml
liveness and readiness probes point to availability of catalog to serve requests.
> catalog: point liveness/readiness to health

- staging/kube-oidc-proxy/.helmignore
- staging/kube-oidc-proxy/Chart.yaml
- staging/kube-oidc-proxy/LICENSE
- staging/kube-oidc-proxy/README.md
- staging/kube-oidc-proxy/templates/NOTES.txt
- staging/kube-oidc-proxy/templates/_helpers.tpl
- staging/kube-oidc-proxy/templates/clusterrole.yaml
- staging/kube-oidc-proxy/templates/clusterrolebinding.yaml
- staging/kube-oidc-proxy/templates/deployment.yaml
- staging/kube-oidc-proxy/templates/ingress.yaml
- staging/kube-oidc-proxy/templates/secret_config.yaml
- staging/kube-oidc-proxy/templates/secret_tls.yaml
- staging/kube-oidc-proxy/templates/service.yaml
- staging/kube-oidc-proxy/templates/serviceaccount.yaml
- staging/kube-oidc-proxy/templates/tests/test-connection.yaml
- staging/kube-oidc-proxy/values.yaml
JIRA: https://jira.mesosphere.com/browse/DCOS-58525
Public PR: https://github.com/jetstack/kube-oidc-proxy/pull/97
> staging/kube-oidc-proxy: add chart

- stable/awsebscsiprovisioner/Chart.yaml
- stable/awsebscsiprovisioner/templates/roles.yaml
- stable/awsebscsiprovisioner/templates/statefulset.yaml
- stable/awsebscsiprovisioner/values.yaml
Merging the same PR to `dev` instead of `master`.
> stable/awsebscsi: fix role not being created and add env to values

- staging/konvoyconfig/.helmignore
- staging/konvoyconfig/Chart.yaml
- staging/konvoyconfig/README.md
- staging/konvoyconfig/templates/_helpers.tpl
- staging/konvoyconfig/templates/configmap.yaml
- staging/konvoyconfig/values.yaml
This chart provides an addon to Konvoy for the purpose of exposing user configurations to the kubeaddons namespace.
> Adding konvoyconfig

- stable/dex-controller/Chart.yaml
- stable/dex-controller/README.md
- stable/dex-controller/templates/_helpers.tpl
- stable/dex-controller/templates/certificates.yaml
- stable/dex-controller/templates/crd_connectors.yaml
- stable/dex-controller/templates/deployments.yaml
- stable/dex-controller/templates/mutating_webhook_configuration.yaml
- stable/dex-controller/templates/rolebindings.yaml
- stable/dex-controller/templates/roles.yaml
- stable/dex-controller/templates/serviceaccounts.yaml
- stable/dex-controller/templates/services.yaml
- stable/dex-controller/templates/validating_webhook_configuration.yaml
- stable/dex-controller/values.yaml
Dex controller allows users to configure Dex through Kubernetes API.
https://github.com/mesosphere/dex-controller/
> dex-controller: add 0.1.1 release

- staging/kubeaddons-catalog/Chart.yaml
- staging/kubeaddons-catalog/templates/deployment.yaml
- staging/kubeaddons-catalog/templates/service.yaml
Fixing namespace missing in metadata.
> [kubeaddons-catalog] add namespace to service and deployment

- stable/kommander/Chart.yaml
- stable/kommander/values.yaml
> chore: bump version of kommander-ui

- staging/traefik/Chart.yaml
- staging/traefik/templates/init-cert-job.yaml
Add annotation to delete the pod once it succeed.
> traefik: add annotations to job to delete the job once succeeded

- stable/dex-controller/Chart.yaml
- stable/dex-controller/templates/crd_clients.yaml
- stable/dex-controller/templates/roles.yaml
- stable/dex-controller/values.yaml
> dex-controller: bump chart to v0.2.0

- stable/kommander/Chart.yaml
- stable/kommander/templates/kommander-system-namespace.yaml
- stable/kommander/values.yaml
Fixes https://jira.mesosphere.com/browse/DCOS-59829.
> kommander: Add kommander system namespace federated to all clusters

- staging/kubeaddons-catalog/Chart.yaml
- staging/kubeaddons-catalog/templates/crd_addonrepository.yaml
addon repo crd needed some additional changes to pull in due to v1beta1
> catalog: addonrepo crd needed to be update

- stable/kommander/Chart.yaml
- stable/kommander/values.yaml
> kommander: fix grafana url

- stable/kommander-thanos/Chart.yaml
- stable/kommander-thanos/templates/federated-addon.yaml
- stable/kommander-thanos/values.yaml
We should add a flag to enable/disable the creation of federated addons.
> kommnader-thanos: add flag for the creation of the federated addon

- staging/kudo/Chart.yaml
- staging/kudo/templates/crds.yaml
- staging/kudo/values.yaml
This PR bump the KUDO chart from 0.7.4 to 0.8.0
> bump KUDO to 0.8.0

- stable/kommander/Chart.yaml
- stable/kommander/templates/federated-kubeaddons.yaml
- stable/kommander/values.yaml
allow kubeaddons version to be configurable.
> [kommander] federated kubeaddons version configurable

- stable/opsportal/Chart.yaml
- stable/opsportal/values.yaml
should fix issues with latest kubeaddons manager.
> opsportal: fixing 2.14 issue

- stable/dispatch/Chart.yaml
- stable/dispatch/charts/minio/templates/statefulset.yaml
- stable/dispatch/charts/tekton/templates/tekton.yaml
Part of https://jira.mesosphere.com/browse/DCOS-61056
Needed for Kubernetes v1.16.
> dispatch: use apps/v1 api

- stable/awsebscsiprovisioner/Chart.yaml
- stable/awsebscsiprovisioner/templates/storageclass.yaml
- stable/awsebscsiprovisioner/values.yaml
- stable/awsebsprovisioner/Chart.yaml
- stable/awsebsprovisioner/templates/storageclass.yaml
- stable/awsebsprovisioner/values.yaml
We will need to enable this to avoid having issues when volumes are small and we need to change them at some point.
> awsebs: add allow volume expansion to the storage class

- stable/awsebsprovisioner/Chart.yaml
- stable/awsebsprovisioner/templates/storageclass.yaml
Fix issue with property using an invalid value.
> awsebs: fix allow volume expansion property

- stable/kommander/Chart.yaml
- stable/kommander/values.yaml
- stable/opsportal/Chart.yaml
- stable/opsportal/values.yaml
> chore: bump kommander/opsportal to image 1.162.0

- staging/kudo/Chart.yaml
- staging/kudo/templates/crds.yaml
- staging/kudo/templates/deployment.yaml
- staging/kudo/values.yaml
> bump KUDO to v0.9.0

- stable/kommander/Chart.yaml
- stable/kommander/files/federated-addonsdeployments.yaml
- stable/kommander/templates/federated-crds.yaml
- stable/kommander/templates/federated-typeconfigs.yaml
refs https://jira.mesosphere.com/browse/DCOS-62180
> kommander: Add FederatedAddonsDeployment CRD

- staging/prometheus-operator/Chart.yaml
- staging/prometheus-operator/values.yaml
Addresses: https://jira.mesosphere.com/browse/DCOS-53598
> Fix grafana internal urls

- stable/kommander/Chart.yaml
- stable/kommander/values.yaml
- stable/opsportal/Chart.yaml
- stable/opsportal/values.yaml
```
commit 65e2f8b4e40a7d36848503583bcfe0c0c49043d8
Author: Renovate Bot <bot@renovateapp.com>
Date:   Tue Jan 7 19:27:59 2020 +0000
fix(deps): update dependency aws-sdk to v2.599.0
commit 3f33e06e1b7260bc6afb2087948ae61a6d2b04c9
Author: Renovate Bot <bot@renovateapp.com>
Date:   Wed Jan 8 08:48:01 2020 +0000
chore(deps): update graphqlcodegenerator monorepo to v1.11.1
commit 3edf840b66740a41461d1a6264e7903b6efd6361
Author: Renovate Bot <bot@renovateapp.com>
Date:   Wed Jan 8 05:40:00 2020 +0000
chore(deps): update dependency husky to v4.0.1
commit 060324420c78141055e2e8765bf0ac8acc7e0ec0
Author: georgi-minchev <georgi.minchev@haemimont.com>
Date:   Wed Jan 8 11:00:36 2020 +0200
fix: system test createCluster
commit 34b68d373ed5f2cf83f159d57fca4154f0238f66
Author: Brandon Croft …
```
> update kommander to 1.176.3

- Makefile
Deterministically create helm packages by:
- Using `helm package` to create the initial package (useful for
including chart dependencies properly)
- Untarring the package
- Recreate the package using `tar`, specifying time of the last git
commit to the package source as the files' `mtime`, as well as ordering
files deterministically, meaning that unchanged content will result in
the same output package.
> chore: Create helm packages deterministically

- staging/prometheus-operator/Chart.yaml
- staging/prometheus-operator/templates/prometheus-operator/crds.yaml
if the crds are installed, do not try to install them
- next steps will and may contain logic to "upgrade" them.
> [prometheus-operator] crd management part 1

- staging/prometheus-operator/Chart.yaml
- staging/prometheus-operator/templates/prometheus-operator/crds.yaml
make sure to not try to create if we have v1 of the resources 
- tested locally to deploy correctly.
> [prometheus-operator] crd management part 2

- stable/kommander/Chart.yaml
- stable/kommander/values.yaml
- stable/opsportal/Chart.yaml
- stable/opsportal/values.yaml
DCOS-61134 Azure Cloud Provider Queries
DCOS-61135 Create Cluster Form Azure support
DCOS-59111 Edit cluster: nodepools, etc.
DCOS-62622 Add link to "Please add Cloud Provider" error message.
DCOS-61513 Create on prem cluster mutation
DCOS-58455 Create on prem cluster form
DCOS-61622 Add all available kubernetes versions in the dropdown on Cluster Detail page
DCOS-61624 Dialog for updating kubernetes
DCOS-61625 Start kubernetes upgrade
DCOS-62710 Display upgrading version
DCOS-62857 Remove or Hide "Getting Started" sidebar link in Konvoy mode
DCOS-62849 "Konvoy UI" displays Kommander Top Bar
DCOS-62594 Deleting a row in cluster create form sometimes changes the URL and refreshes the page
DCOS-62656 Drop-downs "Select option" to not be selectable
DCOS-62699 Pressing Enter causes strange …
> chore: update kommander 1.182.8

- Makefile
Previously was not building from latest sources.
> fix: Fix publishing script

- Makefile
Previously this was using timestamp from target branch, which is different from the package source timestamp.
> chore: Ensure git log timestamp from source branch is used in publish

- stable/kommander/Chart.yaml
- stable/opsportal/Chart.yaml
last PR didnt increase chart version 🙈 Not sure why CI didnt catch it 🤔 "Merge" Button was all green
> fix: bump chart versions (kommander/opsportal)

- staging/traefik/templates/dashboard-roles.yaml
- staging/traefik/values.yaml
Adds view, edit, and admin roles for the traefik dashboard
> [traefik] add dashboard RBAC roles

- stable/azuredisk-csi-driver/Chart.yaml
- stable/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
Azure storage works but we should remove the mentioned flag. 
```
beaddons              elasticsearch-kubeaddons-master-2                                 0/1     Init:0/2    0          22s
kubeaddons              fluentbit-kubeaddons-fluent-bit-5gchj                             1/1     Running     0          33m
kubeaddons              fluentbit-kubeaddons-fluent-bit-5szrj                             1/1     Running     0          33m
kubeaddons              fluentbit-kubeaddons-fluent-bit-65lv2                             1/1     Running     0          33m
kubeaddons              fluentbit-kubeaddons-fluent-bit-6cgg5                             1/1     Running     0          33m
kubeaddons              fluentbit-kubeaddons-fluent-bit-6wjrd                             1/1     Running …
```
> chore: remove worker-threads flag

- staging/generic-ingress/Chart.yaml
- staging/generic-ingress/README.md
- staging/generic-ingress/templates/ingress.yaml
- staging/generic-ingress/templates/ingresses.yaml
- staging/generic-ingress/values.yaml
Slack conversation:
https://mesosphere.slack.com/archives/CMPPXKGKX/p1582871879114100
> feat: add support for multiple ingresses

- stable/cluster-autoscaler/.helmignore
- stable/cluster-autoscaler/Chart.yaml
- stable/cluster-autoscaler/OWNERS
- stable/cluster-autoscaler/README.md
- stable/cluster-autoscaler/templates/NOTES.txt
- stable/cluster-autoscaler/templates/_helpers.tpl
- stable/cluster-autoscaler/templates/clusterrole.yaml
- stable/cluster-autoscaler/templates/clusterrolebinding.yaml
- stable/cluster-autoscaler/templates/deployment.yaml
- stable/cluster-autoscaler/templates/pdb.yaml
- stable/cluster-autoscaler/templates/podsecuritypolicy.yaml
- stable/cluster-autoscaler/templates/role.yaml
- stable/cluster-autoscaler/templates/rolebinding.yaml
- stable/cluster-autoscaler/templates/secret.yaml
- stable/cluster-autoscaler/templates/service.yaml
- stable/cluster-autoscaler/templates/serviceaccount.yaml
- stable/cluster-autoscaler/templates/servicemonitor.yaml
- stable/cluster-autoscaler/values.yaml
JIRA: https://jira.d2iq.com/browse/D2IQ-65258
> cluster-autoscaler: initial commit

- CODEOWNERS
This will make it much easier to get chart changes merged.
> chore: assign individual CODEOWNERS

- stable/kommander/Chart.yaml
- stable/kommander/README.md
- stable/kommander/templates/grafana/hooks-home-dashboard.yaml
- stable/kommander/templates/grafana/opsportal-username-secret.yaml
- stable/kommander/values.yaml
- staging/prometheus-operator/Chart.yaml
- staging/prometheus-operator/templates/mesosphere-hooks/grafana-default-dashboard-hook.yaml
- staging/prometheus-operator/templates/mesosphere-hooks/prometheus-cluster-id-hooks.yaml
- Added readme file mostly for deploying
- Updated naming of hooks
- Made Changes to the values file. 
- Added retrieving service name dynamically without the use of a static values file
- Updated naming of hooks
> [kommander,prometheus] chore:  dynamically get grafana service url

- stable/azuredisk-csi-driver/Chart.yaml
- stable/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
- stable/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
- stable/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
- stable/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
- stable/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
- stable/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
- stable/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
- stable/azuredisk-csi-driver/values.yaml
> chore: azurecsi driver version bump

- stable/cluster-autoscaler/Chart.yaml
- stable/cluster-autoscaler/templates/deployment.yaml
- stable/cluster-autoscaler/values.yaml
We need this PR to enable autodiscovery for the autoscaler
> chore: use autodiscovery for konvoy provider

- stable/kommander/Chart.yaml
lets reflect appversion in chart too
> chore: update kommander appversion

- stable/cluster-autoscaler/Chart.yaml
- stable/cluster-autoscaler/templates/deployment.yaml
- stable/cluster-autoscaler/templates/service.yaml
- stable/cluster-autoscaler/values.yaml
Let's set the defaults to our own interest :)
> fix: metrics endpoint

- stable/kommander/Chart.yaml
- stable/kommander/values.yaml
- stable/opsportal/Chart.yaml
- stable/opsportal/values.yaml
- kommander added impersonation headers
- opsportal added impersonation headers
[D2IQ-67264]
[D2IQ-67264]: https://jira.d2iq.com/browse/D2IQ-67264
> chore: added impersonation headers

- stable/opsportal/Chart.yaml
- stable/opsportal/templates/ingress-opsportal-roles.yaml
- stable/opsportal/templates/kibana-roles.yaml
- aggregate roles to default roles
[D2IQ-67767]
[D2IQ-67767]: https://jira.d2iq.com/browse/D2IQ-67767
> feat(opsportal): aggregate roles

- staging/dex-k8s-authenticator/Chart.yaml
- staging/dex-k8s-authenticator/html-templates/kubectl-plugin-instructions.html
the context name should be profileName-clusterName
> fix(dka): D2IQ-67949

- stable/kommander/Chart.yaml
- stable/kommander/templates/grafana/ingress-roles.yaml
ClusterRole aggregation to the Grafana roles for Admin, Edit and View. And Bump.
> ClusterRole aggregation to Grafana roles

- staging/kubeaddons-catalog/Chart.yaml
- staging/kubeaddons-catalog/files/crd_addonrepository.yaml
- staging/kubeaddons-catalog/values.yaml
Chore
This PR bumps catalog image to the version with fixes to allow kuttl tests to be written
https://jira.d2iq.com/browse/D2IQ-68485
```release-note
```
**Checklist**
> [kubeaddons-catalog] chore: bump catalog image to version 0.8.6

- stable/kommander/Chart.yaml
- stable/kommander/charts/kommander-thanos/templates/query-stores-configmap.yaml
- stable/kommander/templates/kubecost/kubecost-query-stores-configmap.yaml
Bug
[More background here](https://github.com/mesosphere/charts/pull/656#discussion_r444405422) h/t @dlipovetsky . Basically subshells don't inherit `errexit` so we need to set it or else we may ignore the errors and inadvertently enter the block and overwrite the cm.
```release-note
NONE
```
**Checklist**
> kommander: cm script bash fix

- stable/opsportal/Chart.yaml
- stable/opsportal/templates/landing.yaml
- stable/opsportal/values.yaml
Feature
So that users can specify multiple replicas for the landing page deployment
no issue
```release-note
opsportal: allow configuring landing page replicas
```
**Checklist**
> opsportal: allow configuring landing page replicas

- staging/dex-k8s-authenticator/Chart.yaml
- staging/dex-k8s-authenticator/html-templates/kubectl-plugin-instructions.html
Bug
Fixes plugin instructions when used for multiple clusters
no issue
```release-note
NONE
```
**Checklist**
> fix: use the kommander cluster CA for additional clusters

- stable/kubecost/Chart.yaml
- stable/kubecost/values.yaml
Bug
- so that we won't hit a thanos-sidecar error
- enable admin-api
- enable wal-compression
- log.format set to json!
- log.level set to info
- latest prometheus version
- latest alertmanager version
- removed deprecated storage.tsdb.retention
[D2IQ-69703]
[D2IQ-69703]: https://jira.d2iq.com/browse/D2IQ-69703
```release-note
NONE
```
**Checklist**
> fix(kubecost): define extraFlags

- stable/dex-controller/Chart.yaml
- stable/dex-controller/templates/certificates.yaml
- stable/dex-controller/templates/crd_clients.yaml
- stable/dex-controller/templates/crd_connectors.yaml
- stable/dex-controller/templates/deployments.yaml
- stable/dex-controller/templates/mutating_webhook_configuration.yaml
- stable/dex-controller/templates/rolebindings.yaml
- stable/dex-controller/templates/roles.yaml
- stable/dex-controller/templates/serviceaccounts.yaml
- stable/dex-controller/templates/services.yaml
- stable/dex-controller/templates/validating_webhook_configuration.yaml
Bug
The field Release.name is incorrect causing issues with deploying in helm 3
https://jira.d2iq.com/browse/D2IQ-70207
```release-note
NONE
```
**Checklist**
> [dex-controller] fix: change Release.name to Release.Name

- staging/kube-oidc-proxy/Chart.yaml
- staging/kube-oidc-proxy/templates/secret_config.yaml
BUG
Validation fails due to nil values
https://jira.d2iq.com/browse/D2IQ-70239
tested this locally with v3 helm
```release-note
NONE
```
**Checklist**
> [kube-oidc-proxy] remove empty fields from secret

- Makefile
- test/e2e-kind.sh
Chore
no issue
```release-note
NONE
```
**Checklist**
> Misc. improvements to Makefile and e2e-kind.sh

- staging/kubefed/Chart.yaml
- staging/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
- staging/kubefed/templates/federatedtypeconfig.yaml
chore
This allows kubefed to deploy under helm3 and allow crds to be created properly. Note this is not a move towards helm3.
https://jira.d2iq.com/browse/D2IQ-70288
```release-note
NONE
```
**Checklist**
> [kubefed] chore: move template core resources to hooks

- Dispatchfile
Chore 
We're hitting a lot CPU throttling requests from this CI job, so it bumps the limits so that the CPU doesn't need to throttle the process
```release-note
```
**Checklist**
> Bumps CPU limits to avoid throttling

- staging/cert-manager-setup/Chart.yaml
- staging/cert-manager-setup/templates/certificates.yaml
- staging/cert-manager-setup/templates/clusterissuer.yaml
- staging/cert-manager-setup/templates/clusterissuers.yaml
- staging/cert-manager-setup/templates/issuers.yaml
Chore
We wish to have all CRD related resources (Issuers, clusterIssuer, certifiicates) to be deployed after crd creation/update (less weight than this job). 
Please identify any other places i may have missed. However, i believe i captured all instances. 
```release-note
NONE
```
**Checklist**
> [cert-manager] fix order of cert deployment

- Makefile
- test/e2e-kind.sh
Chore
- Prevent the containerized e2e test from polluting host directory
- Wait for deployments to be ready
- Fail on errors in bash pipelines in subshells
- Respect git remote name in the e2e-kind.sh script (it is already respected in the Makefile)
no issue
```release-note
NONE
```
**Checklist**
> chore: Misc. improvements to e2e-kind.sh

- Makefile
- test/e2e-kind.sh
> Revert "[testing] chart-testing v3.0.0 and allow variable helm version for testing"

- stable/azurediskprovisioner/Chart.yaml
- stable/azurediskprovisioner/templates/storageclass.yaml
- stable/azurediskprovisioner/values.yaml
- test/e2e-kind.sh
Chore
Fixes issue with the chart, the skuname was not properly filled in though it should be. 
```release-note
NONE
```
**Checklist**
> [azurediskprovisioner] fixing chart items/values that are broken

- Dispatchfile
- Makefile
- test/e2e-kind.sh
Chore
Migration to helm3 means we need to make sure we are deployable by helm3 continually as well as helm2. Here we make the changes to test against both.
https://jira.d2iq.com/browse/D2IQ-70711
```release-note
NONE
```
**Checklist**
> [testing] chart-testing v3.0.0 and allow variable helm version for testing 

- staging/istio/Chart.yaml
- staging/istio/crds/crd.yaml
Chore
Enable v3 deployment of istio by adding crds directory
https://jira.d2iq.com/browse/D2IQ-70994
```release-note
NONE
```
**Checklist**
> [istio] crds directory created to support helm v3

- Dispatchfile
```release-note
```
**Checklist**
> Publish with helm v2 by setting explicitly

- test/e2e-kind.sh
Bug
Adds retries to the curl requests in the e2e test to avoid failing the test suite in case of connectivity or other transient issues.
```
--max-time 10 # each retry waits up to 10s
--retry 10 # retry 10 times
--retry-max-time 60 # retry for total 60s before failing
--retry-connrefused # retry on connection refused errors
```
https://jira.d2iq.com/browse/D2IQ-70518
```release-note
NONE
```
**Checklist**
> test: Add retries to e2e test curls

- Dispatchfile
- Makefile
bug
helm calls fail because the binary doesn't exist at $(HELM)
https://jira.d2iq.com/browse/D2IQ-71191
```release-note
NONE
```
**Checklist**
> ensure helm is installed where it's executed

- Makefile
Chore
Repo indexes were not being published due to broken target dependencies. This PR fixes those so they will be generated as required again.
No issue.
```release-note
NONE
```
**Checklist**
> chore: Fix up index yaml target deps

- Makefile
chore
If helm is in the path, the Makefile would use it - regardless of whether it was a version that would work. This checks for the correct version and errors if it's wrong.
nada
```release-note
none
```
**Checklist**
> ensure we're using the correct helm

- stable/mtls-proxy/Chart.yaml
- stable/mtls-proxy/templates/service.yaml
Chore
We need to configure the chart to add service annotations such as `service.beta.kubernetes.io/aws-load-balancer-internal: "true"`
```release-note
```
**Checklist**
> chore: add service annotations

- .gitignore
- Makefile
Chore
To get probably the latest changes and probably the last fixes to 2.16.x we bump the version to 2.16.10
This is maintenance more than anything else. 
```release-note
NONE
```
**Checklist**
> chore: bump helm 2 version

- stable/kommander/Chart.yaml
- stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
- stable/kommander/charts/kommander-thanos/templates/federated-addon.yaml
- stable/kommander/templates/kubecost/federated-addon.yaml
Chore
Bump mtls-proxy to use latest version with service annotations being used.
```release-note
```
**Checklist**
> fix: bump mtls-proxy version

- stable/vsphere-csi-driver/Chart.yaml
- stable/vsphere-csi-driver/templates/NOTES.txt
- stable/vsphere-csi-driver/templates/_helper.tpl
- stable/vsphere-csi-driver/templates/controller.yaml
- stable/vsphere-csi-driver/templates/node.yaml
- stable/vsphere-csi-driver/templates/rbac.yaml
- stable/vsphere-csi-driver/templates/serviceaccount.yaml
- stable/vsphere-csi-driver/templates/storageclass.yaml
- stable/vsphere-csi-driver/values.yaml
- test/helm2/ct-e2e.yaml
- test/helm3/ct-e2e.yaml
Feature
- adapted from upstream manifests
[D2IQ-71493]
[D2IQ-71493]: https://jira.d2iq.com/browse/D2IQ-71493
```release-note
vsphere-csi-driver added
```
**Checklist**
> Feat: Add new vsphere-csi-driver chart

- staging/istio/Chart.yaml
- staging/istio/values.yaml
Chore
D2IQ-71816
```release-note
Bug Fixes
* Fixed HTTP match request without headers conflict
* Fixed Istio operator to watch multiple namespaces (Istio #26317)
* Fixed EDS cache when an endpoint appears after its service resource (Istio #26983)
* Fixed istioctl remove-from-mesh not removing init containers on CNI installations.
* Fixed istioctl add-to-mesh and remove-from-mesh commands from affecting OwnerReferences (Istio #26720)
* Fixed cleaning up of service information when the cluster secret is deleted
* Fixed egress gateway ports binding to 80⁄443 due to user permissions
* Fixed gateway listeners created with traffic direction outbound to be drained properly on exit
* …
```
> [D2IQ-71816] Update Istio Chart to v1.6.9

- stable/defaultstorageclass/Chart.yaml
- stable/defaultstorageclass/templates/certificate.yaml
bug
some services use less than fqdn to connect to this webhook. Support all possible short names.
```release-note
none
```
**Checklist**
> add dns name options for all possible short names

- staging/istio/Chart.yaml
- staging/istio/values.yaml
Chore
https://jira.d2iq.com/browse/D2IQ-72246
```release-note
- Security Fix - CVE-2020-25017: In some cases, Envoy only considers the first value when multiple headers are present. Also, Envoy does not replace all existing occurrences of a non-inline header. CVSS Score: 8.3 AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:L
```
**Checklist**
> Update Istio to v1.6.11

- staging/kubeaddons-catalog/Chart.yaml
- staging/kubeaddons-catalog/values.yaml
```release-note
```
**Checklist**
> chore: use latest Catalog API release in chart

- stable/dex-controller/Chart.yaml
- stable/dex-controller/values.yaml
Chore
During the MWT, we found that the dex-controller was killed due to OOM errors.
```release-note
```
**Checklist**
> chore: bump the dex-controller memory limit

- Makefile
Chore
Bump the Makefile to use the latest publish scripts including https://github.com/mesosphere/charts/commit/75f947e48219f3d0df13a4512a2fae767e8359c5.
This is in its own PR so that we don't squash this with actual chart changes.
No issue.
```release-note
NONE
```
**Checklist**
> chore: backport Makefile changes

- stable/cert-manager-setup/Chart.yaml
- stable/cert-manager-setup/templates/v1upgrade.yaml
Bug.
This was causing issues when upgrading the `cert-manager` addon.
No issue.
Related docs: https://helm.sh/docs/chart_template_guide/control_structures/#controlling-whitespace (thanks @makkes)
```release-note
NONE
```
**Checklist**
> fix: remove - from cert-manager v1upgrade.yaml

- Makefile
Chore
Sets the timezone to UTC for helm repo index building.
No issue.
```release-note
NONE
```
**Checklist**
> chore: Always use UTC for helm repo index building

- Makefile
Chore
Improve the Makefile to handle macOS a bit more gracefully.
No issue.
```release-note
NONE
```
**Checklist**
> chore: improve macOS handling in Makefile

- stable/dex-controller/Chart.yaml
- stable/dex-controller/templates/certificates.yaml
Bug
Fixes webhook dns names to conform to cainjector/coredns configuration
https://jira.d2iq.com/browse/D2IQ-72842
```release-note
NONE
```
**Checklist**
> fix: names used with cainjector

- stable/kommander/Chart.yaml
- stable/kommander/templates/grafana/opsportal-username-secret.yaml
- stable/kommander/templates/kubecost/kubecost-query-stores-configmap.yaml
Chore
Avoid failing out on cleanup jobs that delete cms/secrets that don't exist
```release-note
```
**Checklist**
> chore: Add --ignore-not-found to cm cleanup jobs

- stable/cert-manager-setup/Chart.yaml
- stable/cert-manager-setup/requirements.lock
- stable/cert-manager-setup/templates/v1upgrade.yaml
Bug
Adds a job to update apiserver annotation for authlister
no issue
```release-note
NONE
```
**Checklist**
> fix: temporary job to replace apiserver annotation

- Dispatchfile
CI Automation Chore
Auto syncs kommander catalog api in kommander chart's requirements 
https://jira.d2iq.com/browse/D2IQ-71918
```release-note
```
**Checklist**
> Do kommander catlog api bumps to kommander chart

- stable/awsebscsiprovisioner/Chart.yaml
- stable/awsebscsiprovisioner/templates/_helpers.tpl
- stable/awsebscsiprovisioner/templates/roles.yaml
- stable/awsebscsiprovisioner/templates/statefulset.yaml
- stable/awsebscsiprovisioner/values.yaml
Feature
- updated aws-ebs-csi-driver
- updated repository urls
- updated tags and were needed added compability tag and helpers script
no issue
```release-note
- aws-ebs-csi-driver v0.7.0
- CSI Container Images from k8s.gcr.io
```
**Checklist**
> feat(awsebscsiprovisioner): update aws-ebs-csi-driver

- stable/awsebscsiprovisioner/Chart.yaml
- stable/awsebscsiprovisioner/templates/roles.yaml
- stable/awsebscsiprovisioner/values.yaml
Bug
- added missing pods - get, watch, list permissions for csi-resizer
- bugfix release 0.7.1 of the aws-ebs-csi-driver is just a helm release tag
but to stay consistent with that I raised it here also
(https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG-0.x.md#v071)
no issue
```release-note
NONE
```
**Checklist**
> bug(awsebscsiprovisioner): update aws-ebs-csi-driver

- Dispatchfile
BUG 
Dispatch is getting the following error 
```
status:
34   buildCounter: 868
35   cronStatus:
36     dispatchfileChecksum: b517e8f180d5be154aef452d8302c4a9
37     dispatchfileRepoRevision: 8e092895731d4e53054e09261da79307ca673697
38     phase: Failed
39     reason: 'cron action name(s) exceeds the maximum length : "bump-kommander-catalog-api
40       -> exceeds by 4 char(s)". Fix these name(s) in "Dispatchfile" before cron actions
41       can be reconciled for "mesosphere/charts"
```
no issue 
```release-note
```
**Checklist**
> Fix cron condition

- staging/istio/Chart.yaml
- staging/istio/crds/crd.yaml
Bug
Fixes the istio operator CRD which was missing few fields
```release-note
```
**Checklist**
> fix: fixes the istio operator crd

- .gitignore
- Dispatchfile
- Makefile
Chore/Feature
Use helm 3.5 for testing. This includes, among other things, a more detailed linter that doesn't fail on api targets that will be deprecated in the future.
6:30 is the best time on a clock, hands down.
```release-note
none
```
**Checklist**
> Use helm 3.5 with ct

- stable/kibana/Chart.yaml
- stable/kibana/OWNERS
- stable/kibana/README.md
- stable/kibana/ci/initcontainers-all-values.yaml
- stable/kibana/ci/plugin-install.yaml
- stable/kibana/templates/NOTES.txt
- stable/kibana/templates/configmap-dashboardimport.yaml
- stable/kibana/values.yaml
- test/e2e-kind.sh
chore
Changes needed to ensure new version of kibana works and behaves properly
https://jira.d2iq.com/browse/D2IQ-73499
```release-note
Kibana chart updated to ensure we can deploy version 7.10.2
```
**Checklist**
> [kibana] ensure the latest version 7.x works including new image

- staging/gatekeeper/Chart.yaml
- staging/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
- staging/gatekeeper/templates/gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml
- staging/gatekeeper/templates/pre-delete-cleanup-job.yaml
Bug
1. Fixes the securityContext in delete job
2. The secret name is hard corded somewhere in the gatekeeper implementation
```release-note
```
**Checklist**
> fix: fixes the delete job and the secret name

- staging/prometheus-operator/Chart.yaml
- staging/prometheus-operator/patch/mesosphere/templates/grafana/cronjob-home-dashboard.yaml
- staging/prometheus-operator/templates/grafana/cronjob-home-dashboard.yaml
bug
An init script image version was updated. The new image does not have bash.
I can tell when people are being judgmental just by looking at them.
```release-note
none
```
**Checklist**
> use busybox sh instead of the no-longer-existing bash

- Makefile
- staging/prometheus-operator/Chart.yaml
- staging/prometheus-operator/patch/mesosphere/templates/grafana/cronjob-home-dashboard.yaml
- staging/prometheus-operator/patch/patch_6_mesosphere_values.sh
- staging/prometheus-operator/values.yaml
- test/ct.yaml
- test/e2e-kind.sh
- test/helm2/ct-e2e.yaml
- test/helm2/ct.yaml
- test/helm3/ct-e2e.yaml
- test/helm3/ct.yaml
bug (cve)
Update images to mitigate cve's. This is a patch on v9.3.x for federated addons in yakcl, since delete strategies for upgrades are not yet supported for federated addons. After this is merged, we need to run the publish job on the release branch to publish this patch chart version.
```release-note
```
**Checklist**
> [release/prometheus-operator-9.3.x] fix images (cve)

- stable/defaultstorageclass/Chart.yaml
- stable/defaultstorageclass/templates/deployment.yaml
Chore
Fix CVE-2019-14697.
```release-note
```
**Checklist**
> defaultstorageclass: bump kube-rbac-proxy

- stable/grafana/Chart.yaml
- stable/grafana/values.yaml
- stable/kommander/Chart.yaml
- stable/kommander/values.yaml
- staging/prometheus-operator/Chart.yaml
- staging/prometheus-operator/values.yaml
Chore
Bump kommander k8s-sidecar to 1.3.0 to align and fix CVEs
```release-note
NONE
```
**Checklist**
> chore: Bump k8s-sidecar to 1.3.0 to align and fix CVEs

- stable/kubecost/Chart.yaml
- stable/kubecost/values.yaml
bug
cve fix, same change as in https://github.com/mesosphere/charts/pull/980
```release-note
```
**Checklist**
> chore: Bump kubecost grafana sidecar image to fix cve

- stable/kibana/Chart.yaml
- stable/kibana/README.md
… community.
Chore
Explain what changes we done to this chart and why we are not using the upstream version.
```release-note
```
**Checklist**
> [kibana] chart docs to explain deviation from upstream. 

- README.md
Chore
Updates Readme links.
No issue.
```release-note
None
```
**Checklist**
> Fix Readme links in Charts repo.

- staging/gatekeeper/Chart.yaml
- staging/gatekeeper/patch/patch_1_mesosphere_values.sh
- staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml
- staging/gatekeeper/values.yaml
Chore
Allows us to exclude namespaces from proxy mutations
```release-note
NONE
```
**Checklist**
> [gatekeeper] chore: allow exclusion of namespaces in chart

- staging/gatekeeper/Chart.yaml
- staging/gatekeeper/patch/templates/gatekeeper-proxy-mutations.yaml
- staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml
- staging/gatekeeper/values.yaml
Chore
This allows more fine grain control over which namespaces will get mutations.
```release-note
NONE
```
**Checklist**
> [gatekeeper] chore: allow namespace selector for mutations

- Dispatchfile
Chore
Bumps Grafana Chart.
https://jira.d2iq.com/browse/D2IQ-74158
Bumps Grafana Chart.
```release-note
```
**Checklist**
> Add automation for auto-bump Grafana chart

- staging/gatekeeper/Chart.yaml
- staging/gatekeeper/patch/templates/gatekeeper-proxy-mutations.yaml
- staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml
Chore
Fixes the scope to allow deployments mutate properly
Tested this several times locally and this time with different resources not just pods. 
```release-note
None
```
**Checklist**
> chore: change scope of mutations since we use namespaceselector

- Dispatchfile
chore
allows a user to bump karma and thanos to the next version via chatops and cron
```release-note
NONE
```
**Checklist**
> feat: add bumps for thanos and karma

- stable/kommander/Chart.yaml
- stable/kommander/charts/kommander-karma/Chart.yaml
- stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
- stable/kommander/charts/kommander-thanos/Chart.yaml
- stable/kommander/charts/kommander-thanos/templates/federated-addon.yaml
- stable/kommander/requirements.lock
- stable/kommander/requirements.yaml
- stable/kommander/templates/kubecost/federated-addon.yaml
Feature
We do not deploy the mtls-proxy load balancers if the connection-type is of type `unidirectional` as this is not necessary.
https://jira.d2iq.com/browse/D2IQ-74659
```release-note
Do not deploy the mtls-proxy load balancers if the connection-type is of type `unidirectional`
```
**Checklist**
> feat: check connection-type label where necessary

- stable/mtls-proxy/Chart.yaml
- stable/mtls-proxy/templates/deployment.yaml
- stable/mtls-proxy/values.yaml
Feature
Adds ability to provide custom environment variables to `mtls-proxy` chart `ghostunnel` deployment.
https://jira.d2iq.com/browse/D2IQ-74659
```release-note
mtls-proxy accepts custom environment variables for ghostunnel deployment
```
**Checklist**
> [mtls-proxy] feat: add custom env variables support

- test/e2e-kind.sh
chore
bump dummylb
```release-note
none
```
**Checklist**
> bump dummylb which updated the k8s libraries to 0.20.5

- staging/gatekeeper/Chart.yaml
- staging/gatekeeper/patch/templates/gatekeeper-proxy-mutations.yaml
- staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml
- staging/gatekeeper/values.yaml
Bug
applyTo does not accept *, see https://open-policy-agent.github.io/gatekeeper/website/docs/mutation#extent-of-changes
no issue, but part of a new feature for D2IQ-70021
```release-note
NONE, since these changes aren't user facing yet.
```
**Checklist**
> bug: fix gatekeeper pod mutations

- stable/kommander/Chart.yaml
- stable/kommander/charts/kommander-karma/Chart.yaml
- stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
- stable/kommander/charts/kommander-thanos/Chart.yaml
- stable/kommander/charts/kommander-thanos/templates/federated-addon.yaml
- stable/kommander/requirements.lock
- stable/kommander/requirements.yaml
- stable/kommander/templates/kubecost/federated-addon.yaml
- stable/mtls-proxy/Chart.yaml
- stable/mtls-proxy/values.yaml
bug
mtls-proxy was using a nonexistent version of ghostunnel, fixed to use the correct one. Bumped mtls-proxy versions in kommander (kommander-thanos/karma)
```release-note
fix: Use correct ghostunnel version
```
**Checklist**
> [mtls-proxy] [kommander] fix ghosttunnel tag

- stable/dex/Chart.yaml
- stable/dex/patches/07-allow-issuer-customization.patch
- stable/dex/templates/certificate.yaml
- stable/dex/values.yaml
chore
```release-note
Allow certificate issuer customization
```
**Checklist**
> allow dex certificate issuer customization

- staging/dex-k8s-authenticator/Chart.yaml
- staging/dex-k8s-authenticator/templates/deployment.yaml
bug
Use the service account
```release-note
none
```
**Checklist**
> do not add extra permissions to the default serviceaccount

- stable/dex/Chart.yaml
- stable/dex/templates/certificate.yaml
- stable/dex/values.yaml
- staging/kube-oidc-proxy/Chart.yaml
- staging/kube-oidc-proxy/templates/certificate.yaml
- staging/kube-oidc-proxy/values.yaml
bug
need to be able to specify a different hostname for kommander 2
```release-note
none
```
**Checklist**
> make dnsNames configurable for dex and kube-oidc-proxy

- stable/kommander/Chart.yaml
- stable/kommander/charts/kommander-karma/Chart.yaml
- stable/kommander/charts/kommander-karma/templates/secret.yaml
- stable/kommander/charts/kommander-thanos/Chart.yaml
- stable/kommander/charts/kommander-thanos/templates/secret.yaml
- stable/kommander/requirements.lock
- stable/kommander/requirements.yaml
- stable/kommander/templates/kubecost/secret.yaml
Chore
(but would be a bug in the future)
SANs for all generated Certs
CNs are deprecated
- kubecost
- thanos
- karma
no issue
```release-note
NONE
```
**Checklist**
> chore(kommander): cert SANs

- Dispatchfile
Bug
Fixes the kubecost bump by setting the current name for the dependency 
```release-note
```
**Checklist**
> fix: kubecost bump

- staging/kube-prometheus-stack/Chart.yaml
- staging/kube-prometheus-stack/patch/mesosphere/templates/rules/mesosphere-rules/elasticsearch-rules.yaml
- staging/kube-prometheus-stack/patch/patch_6_mesosphere_values.sh
- staging/kube-prometheus-stack/templates/prometheus/rules/mesosphere-rules/elasticsearch-rules.yaml
- staging/kube-prometheus-stack/values.yaml
Chore
We have a need to alert users when their elasticsearch cluster is not healthy or running out of space
```release-note
kube-prometheus-stack: added rules for elasticsearch
```
**Checklist**
> [Kube-prometheus-stack] added elasticsearch rules

- test/e2e-kind.sh
Bug
Stakater reload deployment has changed name of app label, here we take care of this
```release-note
NONE
```
**Checklist**
> bug: reloader label app name has changed

- staging/gatekeeper/Chart.yaml
- staging/gatekeeper/templates/gatekeeper-audit-deployment.yaml
- staging/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
- staging/gatekeeper/values.yaml
Bug
https://jira.d2iq.com/browse/D2IQ-76829
```release-note
```
**Checklist**
> fix: gatekeeper affinity values

- staging/kube-oidc-proxy/Chart.yaml
- staging/kube-oidc-proxy/templates/service.yaml
- staging/kube-oidc-proxy/values.yaml
Chore
Adds the ability to configure annotations on kube-oidc-proxy service
https://jira.d2iq.com/browse/D2IQ-76896
```release-note
```
**Checklist**
> chore: parametrize annotations to kube-oidc-proxy service

- staging/velero/Chart.yaml
- staging/velero/charts/minio/templates/post-install-create-bucket-job.yaml
Chore
Makes the access Minio Endpoint to be resolvable using FQDN.
D2IQ-77416
Needed for having a cleaner `NO_PROXY` variable in gatekeeper configuration.
```release-note
```
**Checklist**
> chore: use fqdn for minio endpoint

- stable/dex/Chart.yaml
- stable/dex/templates/certificate.yaml
- stable/dex/values.yaml
- staging/kube-oidc-proxy/Chart.yaml
- staging/kube-oidc-proxy/templates/certificate.yaml
- staging/kube-oidc-proxy/values.yaml
chore
My prior change required manually setting the dnsNames. This more-reliably sets them automatically.
```release-note
none
```
**Checklist**
> do subject alt names automatically

- staging/traefik-forward-auth/Chart.yaml
- staging/traefik-forward-auth/values.yaml
Bumps tfa to 3.0.2 which adds a fix such that proxy configuration from environment is honored in oidc client.
[D2IQ-75648](https://jira.d2iq.com/browse/D2IQ-75648)
```release-note
```
**Checklist**
> chore: bump traefik-forward-auth to 3.0.2

- staging/nvidia/Chart.yaml
- staging/nvidia/charts/nvidia-dcgm-exporter/Chart.yaml
- staging/nvidia/charts/nvidia-dcgm-exporter/values.yaml
- staging/nvidia/requirements.yaml
Chore
https://jira.d2iq.com/browse/D2IQ-79233
```release-note
updates Nvidia DCGM exporter to 2.2.9
```
**Checklist**
> chore: bumps DCGM exporter to 2.2.9

- stable/kubecost/Chart.yaml
- stable/kubecost/values.yaml
Chore
Relates to https://github.com/mesosphere/kommander-applications/pull/82
```release-note
none
```
**Checklist**
> chore: Update k8s-sidecar image in kubecost chart

- staging/nvidia/Chart.yaml
- staging/nvidia/charts/nvidia-dcgm-exporter/Chart.yaml
- staging/nvidia/charts/nvidia-dcgm-exporter/templates/daemonset.yaml
- staging/nvidia/charts/nvidia-device-plugin/Chart.yaml
- staging/nvidia/charts/nvidia-device-plugin/templates/daemonset.yaml
- staging/nvidia/requirements.yaml
Bug
Our platform service values already try to make use of `affinity` - I missed the fact that the template didn't offer it.
https://jira.d2iq.com/browse/D2IQ-83955
```release-note
Fixes Nvidia GPU platform service placement constraints.
```
**Checklist**
> fix: Adds affinity to nvidia daemonsets

- staging/kube-prometheus-stack/Chart.yaml
- staging/kube-prometheus-stack/patch/patch_6_mesosphere_values.sh
- staging/kube-prometheus-stack/patch/patch_7_mesosphere_default_values.sh
- staging/kube-prometheus-stack/values.yaml
bug
aligns some images with those deployed by other addons in KBA to decrease image bundle
https://jira.d2iq.com/browse/COPS-6963
```release-note
NONE
```
**Checklist**
> [release/kube-prometheus-stack-15.4.x] bump images

- staging/traefik-forward-auth/Chart.yaml
- staging/traefik-forward-auth/values.yaml
feat
Bump TFA image in values to 3.1.0 (https://github.com/mesosphere/traefik-forward-auth/pull/54)
https://jira.d2iq.com/browse/D2IQ-84826
```release-note
```
**Checklist**
> feat: Bump TFA image to 3.1.0

- staging/kube-prometheus-stack/Chart.yaml
- staging/kube-prometheus-stack/templates/ingress-rbac/alertmanager.yaml
- staging/kube-prometheus-stack/templates/ingress-rbac/grafana.yaml
- staging/kube-prometheus-stack/templates/ingress-rbac/prometheus.yaml
chore
change the clusterrole names to prefix with dkp
https://jira.d2iq.com/browse/D2IQ-84281
```release-note
```
**Checklist**
> chore: put dkp in front

- stable/kubecost/Chart.yaml
- stable/kubecost/values.yaml
chore
Bump k8s-sidecar image in the kubecost chart
```release-note
```
**Checklist**
> chore(kubecost): bump k8s-sidecar

- stable/kubecost/Chart.yaml
- stable/kubecost/values.yaml
Chore 
Bumps the configmap-reload image to the latest version 
```release-note
```
**Checklist**
> chore(kubecost): Bump configmap-reload to v0.7.1

- staging/kube-prometheus-stack/Chart.yaml
- staging/kube-prometheus-stack/patch/mesosphere/templates/ingress-rbac/grafana.yaml
- staging/kube-prometheus-stack/templates/ingress-rbac/grafana.yaml
requires the * after /proxy due to https://grafana.com/docs/grafana/latest/http_api/data_source/#data-source-proxy-calls
https://jira.d2iq.com/browse/D2IQ-88865
```release-note
```
**Checklist**
> fix: grafana view only permission

- staging/kube-prometheus-stack/Chart.yaml
- staging/kube-prometheus-stack/patch/mesosphere/templates/ingress-rbac/grafana.yaml
- staging/kube-prometheus-stack/templates/ingress-rbac/grafana.yaml
https://jira.d2iq.com/browse/D2IQ-88865
backport for 2.2.1
```release-note
```
**Checklist**
> 2.2.1 backport for grafana view permission fix

- staging/velero/Chart.yaml
- staging/velero/charts/minio/README.md
```release-note
```
**Checklist**
> Update MinIO README.md

- test/e2e-kind.sh
Bug
Original container is not available in gitlab registry. This PR uses the build from from the original source.
```release-note
NONE
```
**Checklist**
> fix: use mhrabovcin/dummylb container

- staging/traefik-forward-auth/Chart.yaml
- staging/traefik-forward-auth/templates/clusterrole.yaml
- staging/traefik-forward-auth/templates/clusterstorage-role.yaml
- staging/traefik-forward-auth/templates/clusterstorage-rolebinding.yaml
Bug
Customer encountered issue for an undocumented feature https://jira.d2iq.com/browse/D2IQ-86169
solves the permission errors on deleting secrets when user set `clusterStorage.enabled` is set to true for TFA
```release-note
```
**Checklist**
> fix: add delete secrets permissions conditionally

- .github/workflows/scorecards.yml
Feature
Added scorecards to this repo. 
Scorecards is an automated tool that assesses a number of important heuristics (https://github.com/ossf/scorecard#scorecard-checks) associated with software security and assigns each check a score of 0-10.
https://jira.d2iq.com/browse/D2IQ-88112
```release-note
```
**Checklist**
> Added scorecards workflow

- .github/workflows/mergebot.yml
Update mergebot to work with new jira instance
```release-note
```
**Checklist**
> ci: Update mergebot.yml

- stable/object-bucket-claim/Chart.yaml
- stable/object-bucket-claim/templates/object-bucket-claim.yaml
- stable/object-bucket-claim/values.yaml
feature
project loki wont need this Job to check OBC. 
https://d2iq.atlassian.net/browse/D2IQ-92639
```release-note
```
**Checklist**
> feat: make the obc check job optional

- stable/object-bucket-claim/Chart.yaml
- stable/object-bucket-claim/templates/object-bucket-claim.yaml
Chore
we realized that no need for the job to check HelmReleases in other Namespace for workspace HR and project HR won't even need this check.
https://d2iq.atlassian.net/browse/D2IQ-92639
```release-note
```
**Checklist**
> chore: switch to use role

- stable/object-bucket-claim/Chart.yaml
- stable/object-bucket-claim/values.yaml
to make consuming k-app cleaner
Chore
better default values to make things look nicer in both workspace k-app and project k-app
https://d2iq.atlassian.net/browse/D2IQ-92639
```release-note
```
**Checklist**
> chore: remove defaults

- stable/object-bucket-claim/Chart.yaml
- stable/object-bucket-claim/templates/object-bucket-claim.yaml
bug
dkp upgrade stuck on grafana-loki due to helm deadlock
https://d2iq.atlassian.net/browse/D2IQ-92639
```release-note
```
**Checklist**
> fix: handle helm deadlock

- .gitignore
Chore
Add .idea/ directory to .gitignore
--
--
--
**Checklist**
> chore: add git ignore .idea/ directory

- Makefile
Chore
Lints makefile vars to make it more maintainable and easier to understand
--
--
--
**Checklist**
> refactor: lint makefile variables

- Makefile
Chore
Add help text to Makefile targets
--
--
--
**Checklist**
Depends on #1369
> chore: add help target to Makefile

- Makefile
Chore
Add some logs to make targets
--
--
--
**Checklist**
Depends on #1370
> chore: add some make execution logs

- .github/workflows/ct.yaml
CI
Adds chart testing(ct) workflow to lint and test charts
--
--
--
**Checklist**
Depends on #1372
> ci: add dev workflow

- .github/workflows/publish.yml
- Makefile
Ci Fix
Current  version of the publish workflow is not working properly
--
--
--
**Checklist**
> fix: adjust tool version handling for GHA worflows

- staging/kubefed/Chart.yaml
Chart metadata fix
Invalid repository value for dependency causing failures in dependency updates. 
--
--
--
**Checklist**
> fix: remove invalid dependency repository value [D2IQ-93788]

- .github/workflows/publish.yml
Chore
Uses merge bot token to push protected branch
--
--
--
**Checklist**
> fix: use mergebot token to push publish charts

- .gitignore
Chore
Adds local resource directory to .gitignore 
--
--
**Checklist**
> chore: add .local dir to gitignore

- staging/istio/Chart.yaml
bug
forgot to bump the chart version in istio fork bump
```release-note
```
**Checklist**
> feat: Bump istio chart version

- stable/kubecost/Chart.lock
- stable/kubecost/Chart.yaml
- stable/kubecost/charts/opencost/.helmignore
- stable/kubecost/charts/opencost/Chart.yaml
- stable/kubecost/charts/opencost/templates/NOTES.txt
- stable/kubecost/charts/opencost/templates/_helpers.tpl
- stable/kubecost/charts/opencost/templates/deployment.yaml
- stable/kubecost/charts/opencost/templates/rbac.yaml
- stable/kubecost/charts/opencost/templates/service.yaml
- stable/kubecost/charts/opencost/templates/serviceaccount.yaml
- stable/kubecost/charts/opencost/values.yaml
- stable/kubecost/values.yaml
Feature 
Add an opencost subchart to the kubecost parent chart. 
https://d2iq.atlassian.net/browse/D2IQ-94759
```release-note
```
**Checklist**
> feat: Add opencost subchart

- staging/istio/Chart.yaml
- staging/istio/charts/grafana/dashboards/istio-extension-dashboard.json
- staging/istio/charts/grafana/dashboards/istio-performance-dashboard.json
- staging/istio/templates/clusterrole.yaml
- staging/istio/templates/deployment.yaml
- staging/istio/values.yaml
feat
bump istio to latest upstream
```release-note
```
**Checklist**
> feat: Bump istio to 1.16.2

- stable/cert-manager-crds/Chart.yaml
- stable/cert-manager-crds/Makefile
- stable/cert-manager-crds/crds/cert-manager.crds.yaml
feat
We are bumping cert-manager to v1.11.0 - we need to bump cert-manager CRDs here as well
```release-note
```
**Checklist**
> feat: Bump cert-manager crds to v1.11.0

- staging/traefik-forward-auth/Chart.yaml
- staging/traefik-forward-auth/templates/deployment.yaml
- staging/traefik-forward-auth/values.yaml
feat
Add support to add priority class to TFA
https://d2iq.atlassian.net/browse/D2IQ-96287
```release-note
```
**Checklist**
> feat: Add priority class support to TFA

- stable/karma/Chart.yaml
- stable/karma/templates/deployment.yaml
- stable/karma/values.yaml
feat
Add support to add priority class to karma
https://d2iq.atlassian.net/browse/D2IQ-96279
```release-note
```
**Checklist**
> feat: Add priority class support to karma

- staging/dex-k8s-authenticator/Chart.yaml
- staging/dex-k8s-authenticator/templates/deployment.yaml
- staging/dex-k8s-authenticator/values.yaml
feat
add support for setting priority class for DKA
https://d2iq.atlassian.net/browse/D2IQ-96275
```release-note
```
**Checklist**
> feat: Add priority class support to DKA

- staging/knative/charts/serving/templates/net-istio.yaml
- staging/knative/charts/serving/templates/pre-upgrade-hook.yaml
- staging/knative/charts/serving/templates/serving-core.yaml
- staging/knative/charts/serving/templates/serving-hpa.yaml
- staging/knative/values.yaml
feat
depends on https://github.com/mesosphere/charts/pull/1406
Add support to set priority class on knative pods
https://d2iq.atlassian.net/browse/D2IQ-96280
We can merge this into https://github.com/mesosphere/charts/pull/1406
```release-note
```
**Checklist**
> feat: Add priorityClassName to knative manifests

- staging/knative/charts/eventing-sources/charts/github/templates/github.yaml
- staging/knative/charts/eventing/templates/eventing.yaml
feat
eventing charts were added back to https://github.com/mesosphere/charts/pull/1406 -- adding priority class support to those templates as well
```release-note
```
**Checklist**
> feat: Add priority class support to knative eventing subcharts

- stable/dex/Chart.yaml
- stable/dex/templates/job-grpc-certs.yaml
feature
this fails kommander upgrade -- `priorityClass` field is immutable on `Job`
```release-note
```
**Checklist**
> fix: remove priorityClass from job

- staging/nfs-server-provisioner/Chart.yaml
- staging/nfs-server-provisioner/templates/statefulset.yaml
- staging/nfs-server-provisioner/values.yaml
feat
Adds priority class support to nfs-server-provisioner
```release-note
```
**Checklist**
> feat: Add priority class support to nfs-server-provisioner

- stable/kommander-cert-federation/Chart.yaml
- stable/kommander-cert-federation/templates/cert-federation.yaml
- stable/kommander-cert-federation/values.yaml
feat
Add support to set priority class for kommander-cert-federation chart
https://d2iq.atlassian.net/browse/D2IQ-97320
```release-note
```
**Checklist**
> feat: Support priority class in kommander-cert-federation

- stable/mtls-proxy/Chart.yaml
- stable/mtls-proxy/templates/deployment.yaml
- stable/mtls-proxy/values.yaml
feat
add priority class support to mtls-proxy chart
https://d2iq.atlassian.net/browse/D2IQ-97328
```release-note
```
**Checklist**
> feat: Add priority class support to mtls-proxy

- staging/knative/Chart.yaml
- staging/knative/charts/serving/Chart.yaml
- staging/knative/charts/serving/templates/net-istio.yaml
feat
missed one 🥲 
https://d2iq.atlassian.net/browse/D2IQ-97328
```release-note
```
**Checklist**
> feat: Add missing priority class support to knative

- stable/object-bucket-claim/Chart.yaml
- stable/object-bucket-claim/templates/object-bucket-claim.yaml
- stable/object-bucket-claim/values.yaml
feature
set priority (with default to dkp-critical-priority) on OBC jobs
https://d2iq.atlassian.net/browse/D2IQ-97328
```release-note
```
**Checklist**
> feat: Set priority on OBC jobs

- stable/object-bucket-claim/Chart.yaml
- stable/object-bucket-claim/README.md
- stable/object-bucket-claim/templates/object-bucket-claim.yaml
- stable/object-bucket-claim/values.yaml
feat
Add config for setting ttl on Jobs. This is to avoid immutable errors during upgrades due to updating of certain spec fields considered to be immutable. (see https://github.com/mesosphere/kommander-applications/pull/1290#issuecomment-1563400916)
But since the ttl will not apply until the next release, will add a "pre-upgrade" job in k-apps to delete the job before upgrading
https://d2iq.atlassian.net/browse/D2IQ-97328
```release-note
```
**Checklist**
> feat: Support setting ttl on OBC Jobs

- stable/object-bucket-claim/Chart.yaml
- stable/object-bucket-claim/templates/object-bucket-claim.yaml
bug
woops, removing quotes from ttl field
```
ERR Invalid: K8s v1.27.0 | rook-ceph-cluster 1.11.4 | FluxKustomization: object-bucket-claims-helmrelease | HelmRelease: object-bucket-claims | batch/v1/Job check-dkp-loki: problem validating schema. Check JSON formatting: jsonschema: '/spec/ttlSecondsAfterFinished' does not validate with https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.27.0-standalone-strict/job-batch-v1.json#/properties/spec/properties/ttlSecondsAfterFinished/type: expected integer or null, but got string    err=<nil>
```
```release-note
```
**Checklist**
> fix: ttl field should be int not string

- stable/kubecost/Chart.yaml
- stable/kubecost/templates/hooks-clusterid.yaml
- stable/kubecost/values.yaml
feat
Was testing https://github.com/mesosphere/kommander-applications/pull/1333 and saw that there were a few hook jobs that didn't have priority set. Added priority to those jobs here
https://d2iq.atlassian.net/browse/D2IQ-97194
```release-note
```
**Checklist**
> feat: Add priority to kubecost hook jobs

- stable/mtls-proxy/Chart.yaml
- stable/mtls-proxy/values.yaml
Chore
Bumps ghost tunnel below mtls-proxy 
```release-note
```
**Checklist**
> chore: bumps ghosttunnel below mtls-proxy

- staging/knative/Chart.yaml
- staging/knative/charts/eventing/crds/eventing-crds.yaml
- staging/knative/charts/eventing/templates/eventing.yaml
- staging/knative/upgrade_knative.sh
Bug fix
```release-note
```
**Checklist**
> fix: Add new patch to Knative upgrade script

- stable/cert-manager-crds/Chart.yaml
- stable/cert-manager-crds/Makefile
- stable/cert-manager-crds/crds/cert-manager.crds.yaml
Needed for bumping cert-manager to v1.12.2 - See https://github.com/mesosphere/kommander-applications/pull/1362
```release-note
```
**Checklist**
> feat: bump cert-manager-crds to v1.12.2

- staging/dex-k8s-authenticator/Chart.yaml
- staging/dex-k8s-authenticator/html-templates/plugin.html
ref: [D2IQ-97878](https://d2iq.atlassian.net/browse/D2IQ-97878)
[D2IQ-97878]: https://d2iq.atlassian.net/browse/D2IQ-97878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add missing subcommand in docs

- staging/traefik-forward-auth/Chart.yaml
- staging/traefik-forward-auth/templates/deployment.yaml
- staging/traefik-forward-auth/values.yaml
feat
Make log level configurable, defaulting to "warn". then, we should remove https://github.com/mesosphere/kommander-applications/blob/f381665c8edc9d7e35d6dd8bfd237f4a5fa36594/services/traefik-forward-auth/0.3.9/defaults/cm.yaml#L60-L61
https://d2iq.atlassian.net/browse/D2IQ-98651
```release-note
```
**Checklist**
> feat(tfa): Make log level configurable

- .github/workflows/publish.yml
- CONTRIBUTING.md
feat / docs
Trigger publish workflow on pushes to `release/` branches, and add docs on how to release patch versions of helm charts
```release-note
```
**Checklist**
> ci(publish): Run on pushes to release branches

- staging/kube-prometheus-stack/Chart.yaml
- staging/kube-prometheus-stack/patch/mesosphere/templates/ingress-rbac/grafana.yaml
- staging/kube-prometheus-stack/templates/ingress-rbac/grafana.yaml
bug
backports https://github.com/mesosphere/charts/pull/1448 into previous KPS release (for dkp 2.4)
https://d2iq.atlassian.net/browse/D2IQ-98716
```release-note
```
**Checklist**
> fix: add required flag to be able to view grafana dashboard

- staging/kube-oidc-proxy/Chart.yaml
- staging/kube-oidc-proxy/templates/deployment.yaml
Bug
Fixes incorrect flag in deployment when required flags helm chart is used.
See: https://github.com/jetstack/kube-oidc-proxy/blob/v0.3.0/cmd/app/options/oidc.go#L69
https://d2iq.atlassian.net/browse/D2IQ-98909
```release-note
```
**Checklist**
> fix(kube-oidc-proxy): required claims CLI flag

- staging/dex-k8s-authenticator/Chart.yaml
- staging/dex-k8s-authenticator/html-templates/index.html
Bumps DKA chart to 1.3.0 to support multi tenancy.
```release-note
```
**Checklist**
> fix: bump dka

- staging/dex-k8s-authenticator/Chart.yaml
- staging/dex-k8s-authenticator/html-templates/plugin.html
Adds MT support on credentials plugin page.
https://d2iq.atlassian.net/browse/D2IQ-98909
```release-note
```
**Checklist**
> feat: support mt on plugin page

- stable/kommander-cert-federation/Chart.yaml
- stable/kommander-cert-federation/templates/cert-federation.yaml
- stable/kommander-cert-federation/values.yaml
Parametrize Kubectl to pilot the version easily
> fix: bump kubectl images

- staging/dex-k8s-authenticator/Chart.yaml
- staging/dex-k8s-authenticator/values.yaml
Bump DKA to the latest version.
```release-note
```
**Checklist**
> feat: update dka

- stable/object-bucket-claim/Chart.yaml
- stable/object-bucket-claim/templates/object-bucket-claim.yaml
bug
use correct root scope to get values
fixes this error `Error: failed to generate manifests: template: object-bucket-claim/templates/object-bucket-claim.yaml:93:28: executing "object-bucket-claim/templates/object-bucket-claim.yaml" at <.Values.kubectlImage>: nil pointer evaluating interface {}.kubectlImage`
```release-note
```
**Checklist**
> fix(obc): Use root scope for values

- stable/cert-manager-crds/Chart.yaml
- stable/cert-manager-crds/Makefile
- stable/cert-manager-crds/crds/cert-manager.crds.yaml
feat
Bump cert-manager to 1.14.2 which is the version we will be using in dkp 2.8.0
```release-note
```
**Checklist**
> feat(cert-manager): Update to 1.14.2

- stable/kommander-cert-federation/Chart.yaml
- stable/kommander-cert-federation/templates/cert-federation.yaml
Bug
`command` property of pod definition is array.
```release-note
```
**Checklist**
> fix(kommander-cert-federation): fix command definition

- stable/cert-manager-crds/Chart.yaml
- stable/cert-manager-crds/Makefile
- stable/cert-manager-crds/crds/cert-manager.crds.yaml
feature
keep up with the cert-manager version konvoy use in 2.12
https://jira.nutanix.com/browse/NCN-100545
```release-note
```
**Checklist**
> feat: bump to cert-manager 1.15

- staging/dex-k8s-authenticator/Chart.yaml
- staging/dex-k8s-authenticator/html-templates/kubectl-plugin-instructions.html
- staging/dex-k8s-authenticator/html-templates/plugin.html
- staging/dex-k8s-authenticator/values.yaml
Feature
Expands template support for amd and arm macOS kubectl plugin architectures.
```release-note
```
**Checklist**
> feat(dka): add support for macOS arm and amd archs

- staging/kafka-operator/Chart.yaml
- staging/kafka-operator/README.md
- staging/kafka-operator/templates/alertmanager-peerauthentication.yaml
- staging/kafka-operator/templates/alertmanager-service.yaml
- staging/kafka-operator/templates/crds.yaml
- staging/kafka-operator/templates/operator-deployment-with-webhook.yaml
- staging/kafka-operator/templates/operator-rbac.yaml
- staging/kafka-operator/templates/operator-service.yaml
- staging/kafka-operator/values.yaml
Bug
Adds `kafka-operator` chart from the repo that is having DNS resolution issue.
https://jira.nutanix.com/browse/NCN-103003
```release-note
```
**Checklist**
> feat(kafka-operator): add 0.23.0-dev.0

- staging/knative/Chart.yaml
- staging/knative/charts/serving/templates/pre-upgrade-hook.yaml
- staging/knative/charts/serving/values.yaml
Bug
Allows to upgrade knative without executing manual steps.
```release-note
```
**Checklist**
> fix(knative): delete webhook before upgrade

- config/ct/config.yaml
- test/ct.yaml
- test/helm3/ct-e2e.yaml
- test/helm3/ct.yaml
```release-note
```
**Checklist**
> fix: remove deprecated yakcl repository

- stable/logging-operator/Chart.yaml
Feature
Update logging operator to latest version.
```release-note
```
**Checklist**
> feat(logging-operator): bump logging operator to 4.10.1

- staging/knative/Chart.yaml
- staging/knative/charts/serving/templates/knative-ingress-gateway.yaml
- staging/knative/charts/serving/templates/net-istio.yaml
- staging/knative/charts/serving/values.yaml
- staging/knative/upgrade_knative.sh
- staging/knative/values.yaml
- test/e2e-kind.sh
Feature
```release-note
```
**Checklist**
> feat(knative): add net-istio

- staging/cosi-driver-nutanix/Chart.yaml
- staging/cosi-driver-nutanix/README.md
- staging/cosi-driver-nutanix/crds/crd.yaml
- staging/cosi-driver-nutanix/templates/_helpers.tpl
- staging/cosi-driver-nutanix/templates/cosi-controller.yaml
- staging/cosi-driver-nutanix/templates/deploy.yaml
- staging/cosi-driver-nutanix/templates/rbac.yaml
- staging/cosi-driver-nutanix/templates/sa.yaml
- staging/cosi-driver-nutanix/templates/secret.yaml
- staging/cosi-driver-nutanix/values.yaml
Copied the chart manifests from https://github.com/nutanix-cloud-native/cosi-driver-nutanix/tree/80171d20bac55fcea5a39c794702d4769022a00a/charts 
This is an interim solution until https://github.com/nutanix/helm/tree/master/charts can be updated with this chart (or kommander supports oci helm charts in airgapped).
```release-note
```
**Checklist**
> feat: add cosi-driver-nutanix helm chart

- staging/knative/Chart.yaml
- staging/knative/charts/eventing/Chart.yaml
- staging/knative/charts/eventing/crds/eventing-crds.yaml
- staging/knative/charts/eventing/templates/eventing-core.yaml
- staging/knative/charts/serving/Chart.yaml
- staging/knative/charts/serving/crds/serving-crds.yaml
- staging/knative/charts/serving/templates/net-istio.yaml
- staging/knative/charts/serving/templates/serving-core.yaml
- staging/knative/charts/serving/templates/serving-hpa.yaml
- staging/knative/upgrade_knative.sh
feat: bump Knative to v1.17.0
https://jira.nutanix.com/browse/NCN-105452
> feat: bump Knative to v1.17.0

- staging/cosi-driver-nutanix/Chart.yaml
- staging/cosi-driver-nutanix/templates/deploy.yaml
Follow-up for #1547.
```release-note
```
**Checklist**
> fix: Use templated name for COSI driver secret

- stable/cosi/Chart.yaml
- stable/cosi/templates/apps_v1_deployment_container-object-storage-controller.yaml
- stable/cosi/values.yaml
Feature
We want configure priorityClassName and toleration for the COSI controller. Like a CSI controller, we want the COSI controller to have critical priority, and tolerate any taint. 
```release-note
```
**Checklist**
> feat: Add priorityClassName and tolerations to Chart values

- stable/harbor-copy-secret/.helmignore
- stable/harbor-copy-secret/Chart.yaml
- stable/harbor-copy-secret/README.md
- stable/harbor-copy-secret/templates/_helpers.tpl
- stable/harbor-copy-secret/templates/deployment.yaml
- stable/harbor-copy-secret/templates/serviceaccount.yaml
- stable/harbor-copy-secret/values.yaml
Feature
Adds a new chart that can copy/watch secret and reflect its value in a different namespace.
```release-note
```
**Checklist**
> feat: add harbor-copy-secret chart

- staging/cosi-driver-nutanix/Chart.yaml
Fixes all Critical and High CVEs
```
➜  ~ trivy i ghcr.io/nutanix-cloud-native/cosi-driver-nutanix:v0.2.0 2025-02-12T14:16:41-08:00	INFO	[vuln] Vulnerability scanning is enabled 2025-02-12T14:16:41-08:00	INFO	[secret] Secret scanning is enabled 2025-02-12T14:16:41-08:00	INFO	[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning 2025-02-12T14:16:41-08:00	INFO	[secret] Please see also https://aquasecurity.github.io/trivy/v0.58/docs/scanner/secret#recommendation for faster secret detection 2025-02-12T14:16:42-08:00	INFO	Detected OS	family="wolfi" version="20230201" 2025-02-12T14:16:42-08:00	INFO	[wolfi] Detecting vulnerabilities...	pkg_num=3 2025-02-12T14:16:42-08:00	INFO	Number of language-specific files	num=1 2025-02-12T14:16:42-08:00	INFO	[gobinary] …
```
> fix: update COSI Nutanix driver version

- staging/cosi-driver-nutanix/Chart.yaml
- staging/cosi-driver-nutanix/templates/deploy.yaml
- staging/cosi-driver-nutanix/templates/rbac.yaml
- staging/cosi-driver-nutanix/values.yaml
- Adds a priorityclass config for cosi-driver-nutanix
- cherry picks changes from https://github.com/nutanix-cloud-native/cosi-driver-nutanix/pull/393
https://jira.nutanix.com/browse/NCN-105640
```release-note
```
**Checklist**
> chore: add priority class for cosi-driver-nutanix deployment

- stable/cosi-bucket-kit/Chart.yaml
- stable/cosi-bucket-kit/templates/bucketaccesses.yaml
- stable/cosi-bucket-kit/templates/bucketclaims.yaml
- stable/cosi-bucket-kit/values.yaml
Allows the downstream components to specify annotations on the cosi resources.
https://jira.nutanix.com/browse/NCN-105676
```release-note
```
**Checklist**
> feat(cosi): add annotations for BC and BA

- stable/cosi-bucket-kit/Chart.yaml
- stable/cosi-bucket-kit/templates/job-readiness.yaml
Bug
Use `initContainers` to ensure order of container execution.
```release-note
```
**Checklist**
> fix(cosi-bucket-kit): wait for bucketaccess secret

- stable/cosi-bucket-kit/Chart.yaml
- stable/cosi-bucket-kit/templates/job-readiness.yaml
```release-note
```
**Checklist**
> fix(cosi-bucket-kit): Correctly set S3 region from BucketInfo

- staging/cilium-hubble-relay-traefik/Chart.yaml
- staging/cilium-hubble-relay-traefik/templates/ingressroutetcp.yaml
Bug
Fixes a typo in a field name.
```release-note
```
**Checklist**
> fix: In cilium-hubble-relay-traefik, fix typo in field name

- stable/cert-manager-crds/Chart.yaml
- stable/cert-manager-crds/Makefile
- stable/cert-manager-crds/crds/cert-manager.crds.yaml
feat: bump cert-manager to 1.16.4
https://jira.nutanix.com/browse/NCN-105338
> feat: bump cert-manager to 1.16.4

- staging/docker-registry/Chart.yaml
- staging/docker-registry/patch/nutanix/patch_6_update-registry-image.patch
- staging/docker-registry/values.yaml
Picks up bug and CVE fixes.
```release-note
```
**Checklist**
> fix: update registry image version

- staging/cosi-driver-nutanix/Chart.yaml
- staging/cosi-driver-nutanix/templates/secret.yaml
Consumes https://github.com/nutanix-cloud-native/cosi-driver-nutanix/releases/tag/v0.6.0
https://jira.nutanix.com/browse/NCN-108099
```release-note
```
**Checklist**
> feat: bump to cosi-driver-nutanix:0.6.0

- stable/cosi-bucket-kit/Chart.yaml
- stable/cosi-bucket-kit/templates/job-readiness.yaml
Bug
Supports configuring Harbor with bucket endpoint over TLS.
```release-note
```
**Checklist**
> feat: support tls buckets for harbor config

- stable/cosi-bucket-kit/Chart.yaml
- stable/cosi-bucket-kit/templates/job-readiness.yaml
Bug
Add missing newline char
```release-note
```
**Checklist**
> fix(cosi-bucket-kit): missing line delimiter
