stable/localvolumeprovisioner/Chart.yaml
stable/localvolumeprovisioner/templates/NOTES.txt
stable/localvolumeprovisioner/templates/deployment.yaml
stable/localvolumeprovisioner/templates/storageclass.yaml
stable/localvolumeprovisioner/values.yaml

Modify the localvolumeprovisioner to specify a hardcoded StorageClass.
The StorageClass has a single configuration option,
'storageclassdefault: true|false' that specifies whether or not it
should be annotated as the default StorageClass.

localvolumeprovisioner: single storageclass with flag for default

---

staging/dex-k8s-authenticator/.helmignore
staging/dex-k8s-authenticator/Chart.yaml
staging/dex-k8s-authenticator/LICENSE
staging/dex-k8s-authenticator/README.md
staging/dex-k8s-authenticator/out.yaml
staging/dex-k8s-authenticator/templates/NOTES.txt
staging/dex-k8s-authenticator/templates/_helpers.tpl
staging/dex-k8s-authenticator/templates/ca_secrets.yaml
staging/dex-k8s-authenticator/templates/configmap.yaml
staging/dex-k8s-authenticator/templates/deployment.yaml
staging/dex-k8s-authenticator/templates/ingress.yaml
staging/dex-k8s-authenticator/templates/service.yaml
staging/dex-k8s-authenticator/values.yaml

This chart is copied from https://github.com/mintel/dex-k8s-authenticator which does not provide URL structure so that the chart can be directly added as a helm repo.
I've created `LICENSE` file which copies original license and adds a reference to the source repository.

charts/staging: add dex-k8s-authenticator repository

---

Makefile

PROBLEM: We found that the charts repo was overwriting the old published charts so old versions weren't respected for the same chart 😢 .
The master branch could have been checked out before and being out-dated. So I recommend to pull the latest changes and rebase taking the latest changes.
If we do so, we need to enforce GH to only allow merging PRs which has been rebased.
related to: https://jira.mesosphere.com/browse/DCOS-56035

Makefile: pull latest changes and rebase using our changes

---

Makefile

the pipeline is failing since we merged https://github.com/mesosphere/charts/pull/10, with the following error:` [19:06:32][Step 1/1] fatal: could not read Username for 'https://github.com': No such device or address`
https://teamcity.mesosphere.io/viewLog.html?buildId=2053248&buildTypeId=ClosedSource_Konvoy_Chart&tab=buildLog&_focus=255

Makefile: restore and fix old remote

---

stable/kommander/Chart.yaml
stable/kommander/templates/_helpers.tpl
stable/kommander/templates/crd.yaml
stable/kommander/templates/deployment.yaml
stable/kommander/templates/ingress.yaml
stable/kommander/templates/service.yaml
stable/kommander/templates/serviceaccount.yaml
stable/kommander/values.yaml

Add an ingress record so we can allow access to the kommander
application.
Changed to more closely follow chart design guidelines.

Add ingress to kommander

---

staging/traefik/Chart.yaml
staging/traefik/OWNERS
staging/traefik/README.md
staging/traefik/templates/NOTES.txt
staging/traefik/templates/_helpers.tpl
staging/traefik/templates/acme-pvc.yaml
staging/traefik/templates/config-files.yaml
staging/traefik/templates/configmap.yaml
staging/traefik/templates/dashboard-ingress.yaml
staging/traefik/templates/dashboard-service.yaml
staging/traefik/templates/default-cert-secret.yaml
staging/traefik/templates/deployment.yaml
staging/traefik/templates/dns-provider-secret.yaml
staging/traefik/templates/hpa.yaml
staging/traefik/templates/poddisruptionbudget.yaml
staging/traefik/templates/rbac.yaml
staging/traefik/templates/secret-files.yaml
staging/traefik/templates/service.yaml
staging/traefik/templates/storeconfig-job.yaml
staging/traefik/templates/tests/test-configmap.yaml
staging/traefik/templates/tests/test.yaml
staging/traefik/values.yaml

As a backup plan until https://github.com/helm/charts/pull/15511 is merged, we might want to use our own traefik chart which allows us defining auth response headers.

staging: temporary add traefik

---

staging/traefik-forward-auth/Chart.yaml
staging/traefik-forward-auth/templates/deployment.yaml
staging/traefik-forward-auth/values.yaml

This PR adds `initContainer` support to the `treafik-forward-auth` chart.

Add initContainers to traefik-forward-auth chart

---

staging/traefik-forward-auth/templates/secret.yaml

This is a temporary workaround for a problem with how we currently deploy the traefik-forward-auth addon. Follow up is [DCOS-56555](https://jira.mesosphere.com/browse/DCOS-56555).

Add temporary placeholder for traefik-forward-auth

---

stable/kommander/Chart.yaml
stable/kommander/templates/deployment.yaml

should fix:
`kommander: kommander failed: exit status 1 [stderr: Error: release kommander-kubeaddons failed: Deployment.apps "kommander-kubeaddons" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"kommander-kubeaddons"}: `selector` does not match template `labels``

fixing selector matchlabels and template name lable to match

---

stable/dex/.helmignore
stable/dex/Chart.yaml
stable/dex/OWNERS
stable/dex/config/openssl.conf
stable/dex/templates/NOTES.txt
stable/dex/templates/_helpers.tpl
stable/dex/templates/clusterrole.yaml
stable/dex/templates/clusterrolebinding.yaml
stable/dex/templates/config-openssl.yaml
stable/dex/templates/deployment.yaml
stable/dex/templates/ingress.yaml
stable/dex/templates/job-grpc-certs.yaml
stable/dex/templates/job-web-certs.yaml
stable/dex/templates/poddisruptionbudget.yaml
stable/dex/templates/role.yaml
stable/dex/templates/rolebinding.yaml
stable/dex/templates/secret.yaml
stable/dex/templates/service.yaml
stable/dex/templates/serviceaccount.yaml
stable/dex/values.yaml

JIRA: https://jira.mesosphere.com/browse/COPS-4881
Adds support for `initContainers` to official `stable/dex` helm chart. This is necessary in order to migrate `extrasteps` from `kubeadsons` repository.
The chart version has been bumped to `1.5.2` from `1.5.1`.

stable/dex: add dex chart with initContainers support

---

Makefile

Since we're now using the https uri for publishing, we no longer need these ssh commands.

remove ssh cruft

---

staging/traefik-forward-auth/Chart.yaml
staging/traefik-forward-auth/templates/configmap.yaml
staging/traefik-forward-auth/templates/secret.yaml
staging/traefik-forward-auth/values.yaml

I may be mistaken, but other tools will create this secret, we probably should not create it in production as it will break and fail to deploy.

should not deploy ops-portal-secret

---

stable/kommander/Chart.yaml
stable/kommander/templates/ingress.yaml
stable/kommander/values.yaml
stable/opsportal/Chart.yaml
stable/opsportal/templates/ingress-opsportal.yaml
stable/opsportal/templates/landing.yaml
stable/opsportal/values.yaml

still need to bump docker image version for whenever we get it

landing for ops portal and Traefik config

---

stable/kommander/Chart.yaml
stable/kommander/templates/crd.yaml
stable/kommander/values.yaml

We are seeing this error when installing konvoy-ui and kommander, we should install one time the CRD:
```
konvoy-ui                                                              [ERROR]
konvoy-ui: konvoy-ui failed: exit status 1 [stderr: Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "observableclusters.stable.mesosphere.com" already exists
]
```

kommander: add conditional to install the CRD

---

stable/kommander/Chart.yaml
stable/kommander/templates/ingress.yaml
stable/opsportal/Chart.yaml
stable/opsportal/templates/ingress-opsportal.yaml
stable/opsportal/templates/landing.yaml

Fix the traefik related annotations. Some traefik forward auth related
configurations should be moved to kubeaddons-configs.

chore: fix ops portal and kommander charts

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

Redirect to on logout `/` leads to 404. Redirect to `/landing` instead.

fix: change logout redirect to '/landing' in kommander

---

staging/dex-k8s-authenticator/Chart.yaml
staging/dex-k8s-authenticator/templates/deployment.yaml
staging/dex-k8s-authenticator/values.yaml

The cleanup of the subpath for this secret resulted in a problem when terminating the pod. This change should work the same without using `subPath`.
```
Jul 22 12:01:19 out-darwin-9d9b-worker-pool0-1 kubelet[686]: E0722 12:01:19.110863     686 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/5729f513-0433-4c56-a8b6-aafa9cbd4289-dex-k8s-authenticator-kubeaddons-dex-root-ca\" (\"5729f513-0433-4c56-a8b6-aafa9cbd4289\")" failed. No retries permitted until 2019-07-22 12:02:23.1108117 +0000 UTC m=+4373.047820401 (durationBeforeRetry 1m4s). Error: "error cleaning subPath mounts for volume \"dex-k8s-authenticator-kubeaddons-dex-root-ca\" (UniqueName: \"kubernetes.io/secret/5729f513-0433-4c56-a8b6-aafa9cbd4289-dex-k8s-authenticator-kubeaddons-dex-root-ca\") pod …
```

dex-k8s-authenticator: avoid using subPath for the secret

---

stable/kommander/Chart.yaml
stable/kommander/templates/service.yaml

Add the service monitor label to get kommander metrics automatically scraped by prometheus

Add service monitor label to kommander

---

stable/dex/Chart.yaml
stable/dex/templates/role.yaml

This enables Dex extrasteps logic to view the service for traefik to determine metadata needed to bootstrap our Dex implementation.

Add the ability to view services to dex sa

---

stable/awsebscsiprovisioner/Chart.yaml
stable/awsebscsiprovisioner/templates/daemonset.yaml
stable/awsebscsiprovisioner/values.yaml
stable/localvolumeprovisioner/Chart.yaml
stable/localvolumeprovisioner/templates/daemonset.yaml
stable/localvolumeprovisioner/values.yaml

During our mwt tests, we found that the pods were not deployed in all the nodes. Besides I found that the priority class of the localvolumeprovisioner pod is not set as a priority class.

stable/storage charts: set tolerations and critical priority

---

stable/awsebscsiprovisioner/Chart.yaml
stable/awsebscsiprovisioner/templates/statefulset.yaml
stable/awsebscsiprovisioner/values.yaml

The chart refactoring in https://github.com/mesosphere/charts/pull/26 got the image tag version wrong in a few places. I've gone through that PR and checked that the values in values.yaml all match the pre-refactoring values.
Fixes https://jira.mesosphere.com/browse/DCOS-56901 - further PRs required to update all the various upstream repositories.

Fix awsebscsiprovisioner chart values

---

stable/kommander/Chart.yaml
stable/kommander/templates/deployment.yaml
stable/kommander/values.yaml

Add env vars to kommander deployment that represent cluster polling interval (for kommander backend) and client polling interval (for kommander frontend).

Add polling interval env vars for kommander

---

stable/awsebscsiprovisioner/Chart.yaml
stable/awsebscsiprovisioner/templates/storageclass.yaml
stable/awsebscsiprovisioner/values.yaml
stable/awsebsprovisioner/Chart.yaml
stable/awsebsprovisioner/templates/storageclass.yaml

These parameters are supported by both, 'awsebsprovisioner' as well as
'awsebscsiprovisioner'.

add optional configuration parameters for AWS EBS volumes.

---

staging/dex-k8s-authenticator/Chart.yaml
staging/dex-k8s-authenticator/README.md
staging/dex-k8s-authenticator/templates/deployment.yaml

I proposed to stay away of subPath volumes in general to avoid issues when mounting/unmounting vols on multiple OS and environments.
related issues: 
https://github.com/kubernetes/kubernetes/issues/50345 
https://github.com/kubernetes/kubernetes/issues/72991#issuecomment-508132380
also this one #60

dex-k8s-authenticator: stop using subPath in general for dex-k8s-auth

---

stable/kommander/Chart.yaml
stable/kommander/templates/deployment.yaml

The env map in a deployment requires both name and value to be strings.
Always `quote` filter Values variables that are used for setting
env.value fields.

ensure env values are strings

---

stable/kommander/Chart.yaml
stable/kommander/templates/crd.yaml

When multiple deployments of Kommander would occur, here is the lifecycle of what would happen:
- First instance is deployed, CRD hook runs and installs CRD with hook-delete-policy: before-hook-creation
- CRD is running all is good in the world
-  Second instance is deployed. BY CRD hook-delete-policy, the previous hook has to be deleted.
- First hook deletes first instance of CRD, or tries to immediately
- If resources already exist, it may not delete immediately
- If the delete failed in timely manner Second instance CRD attempts to run anyway
- Error message that CRD already exists and something about deletion failing also
- We are in a sad place
To mitigate the above story, we should instead
- Remove that policy, try not to delete anything if possible for CRDS
- use the default policy …

[fixe] changed how crd deployment works for kommander

---

stable/opsportal/Chart.yaml
stable/opsportal/templates/hooks-roles.yaml
stable/opsportal/templates/hooks-secrets.yaml
stable/opsportal/values.yaml

made changes to automatically generate secrets for the credentials required by multiple tools. Should unblock CI when we delete extra steps. 
Blocked on: https://github.com/mesosphere/kubeaddons-extrasteps/pull/6

[extrasteps] opsportal updated with hooks for secrets generation

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

As observed in soak, we don't need to reserve 1000m CPU.
Reduce it to 100m, but still allows it to burst to 2000m CPU.

kommander: reduce default CPU request

---

stable/localvolumeprovisioner/Chart.yaml
stable/localvolumeprovisioner/templates/NOTES.txt
stable/localvolumeprovisioner/templates/configmap.yaml
stable/localvolumeprovisioner/templates/daemonset.yaml
stable/localvolumeprovisioner/templates/storageclass.yaml
stable/localvolumeprovisioner/values.yaml

Multiple storage classes allow defining a volume topology. For each item
in the configuration a `localvolumeprovisioner-%name%` storage class
will get created. Volumes mounted at `/mnt/%name%` on each host will be
detected and added as persistent volumes under this storage class.

localvolumeprovisioner: allow configuration of multiple storage classes

---

stable/awsebscsiprovisioner/Chart.yaml
stable/awsebscsiprovisioner/templates/storageclass.yaml
stable/awsebscsiprovisioner/values.yaml

Customers might want to configure the allowed topologies when deploying on a multi AZ cluster:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
annotations:
kubernetes.io/description: AWS EBS CSI provisioner StorageClass
storageclass.kubernetes.io/is-default-class: "true"
creationTimestamp: "2019-07-27T14:12:39Z"
name: awsebscsiprovisioner
resourceVersion: "2043"
selfLink: /apis/storage.k8s.io/v1/storageclasses/awsebscsiprovisioner
uid: 684d5b49-6704-4ef9-98d3-01e9c137bb45
parameters:
type: gp2
provisioner: ebs.csi.aws.com
allowedTopologies:
- matchLabelExpressions:
- key: topology.ebs.csi.aws.com/zone
values:
- us-west-2a
- us-west-2b
- us-west-2c
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

awsebscsiprovisioner: set allowed topologies values

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/traefikdashboard.yaml
staging/prometheus-operator/values.yaml

prometheus-operator: typo in the mesosphere resources

---

stable/localvolumeprovisioner/Chart.yaml
stable/localvolumeprovisioner/templates/NOTES.txt
stable/localvolumeprovisioner/templates/configmap.yaml
stable/localvolumeprovisioner/templates/daemonset.yaml
stable/localvolumeprovisioner/templates/storageclass.yaml
stable/localvolumeprovisioner/values.yaml

Reverts https://github.com/mesosphere/charts/pull/84 until the changes are integrated in `kubeaddons` and `konvoy`.

Revert 354e37bda91e18fb3645f88d1ed082794992f47c

---

stable/opsportal/Chart.yaml
stable/opsportal/values.yaml
staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/opsportaldashboard.yaml
staging/prometheus-operator/values.yaml

We need to rename konvoy-ui  dashboard to be consistent with the current name for it `ops portal`

dashboard: rename konvoy-ui to opsportal

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/opsportaldashboard.yaml

Fix for uptime panel in Ops Portal dashboard to show up green (instead of orange) when value is 1 (up).
vs

Modify Ops Portal dashboard uptime text to green when up

---

staging/velero/Chart.yaml
staging/velero/templates/service.yaml
staging/velero/templates/servicemonitor.yaml
staging/velero/values.yaml

- Commented out pod annotations because it looks like [prometheus-operator does not encourage annotation-based discovery of services anymore](https://github.com/helm/charts/tree/master/stable/prometheus-operator#prometheusioscrape) (in other charts, these annotations are commented out so following the pattern here).
- Added a `(.Capabilities.APIVersions.Has "monitoring.coreos.com/v1")` check in servicemonitor.yaml to avoid the case where velero's service monitor is enabled but the prometheus-operator isn't or has not yet deployed the `ServiceMonitor` CRD.
- Added config option to add service labels to enable discovery by service monitors already defined in prometheus ([our prom service monitor defs here](https://github.com/mesosphere/kubeaddons-configs/blob/master/templates/prometheus.yaml …

Add config for service labels to velero for service monitor discovery

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/calicodashboard.yaml
staging/prometheus-operator/values.yaml

Added a dashboard for Calico metrics.
Will need to bump version again after https://github.com/mesosphere/charts/pull/105 is merged (or bump version there depending on which is merged first)

Add Calico dashboard

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/elasticsearchdashboard.yaml
staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/grafanadashboard.yaml
staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/opsportaldashboard.yaml
staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/velerodashboard.yaml
staging/prometheus-operator/templates/prometheus/rules/mesosphere-rules/velero-rules.yaml
staging/prometheus-operator/values.yaml

- Updated a few dashboards (removed unnecessary/broken links)
- Added dashboard for Velero
- Added an alert rule for Velero (60min look back window on rate of # backup failures  metric)
Lmk if there are any additional graphs or rules that could be useful

Velero dashboard and alert rule

---

staging/gatekeeper/Chart.yaml
staging/gatekeeper/README.md
staging/gatekeeper/templates/NOTES.txt
staging/gatekeeper/templates/_helpers.tpl
staging/gatekeeper/templates/validatingwebhook.yaml
staging/gatekeeper/values.yaml

This defaults to skipping validation of gatekeeper components,
required for a Fail validation webhook policy.

feat: Allow configurable object selector for webhook

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/kibanadashboard.yaml
staging/prometheus-operator/values.yaml

Blocked on https://github.com/mesosphere/kubeaddons-configs/pull/201 which gets the kibana metrics exported and scraped by prometheus.

Add Kibana dashboard

---

staging/kubeaddons-catalog/Chart.yaml
staging/kubeaddons-catalog/templates/_helpers.tpl
staging/kubeaddons-catalog/templates/deployment.yaml
staging/kubeaddons-catalog/templates/service.yaml
staging/kubeaddons-catalog/values.yaml

This adds the Kubeaddons Catalog as a staging chart for testing use while the app itself is in alpha.
This chart was tested locally via port-forward (no ingress is wanted at this point, will be added in later iterations).
Resolves [DCOS-59097](https://jira.mesosphere.com/browse/DCOS-59097)

Add Kubeaddons Catalog Chart

---

stable/dex/Chart.yaml
stable/dex/templates/certificate.yaml
staging/cert-manager-setup/Chart.yaml
staging/cert-manager-setup/templates/issuers.yaml
staging/cert-manager-setup/templates/post-install-hook-job.yaml
staging/traefik/Chart.yaml
staging/traefik/templates/certificate.yaml

Add `pre-upgrade/post-upgrade` to all `pre-install/post-install` hooks in the `dex`, `traefik` and `cert-manager`.

Add pre-upgrade on all new hooks

---

Makefile

Rather than working around git to try to grab the archived history of
the docs directory, use curl to get it directly.

use curl to get docs archive

---

stable/awsebscsiprovisioner/Chart.yaml
stable/awsebscsiprovisioner/templates/roles.yaml
stable/awsebscsiprovisioner/templates/statefulset.yaml
stable/awsebscsiprovisioner/values.yaml

Adding `env: {}` to awsebscsi driver to be able to pass HTTP_PROXY settings.
Also fixed in roles since it was not creating `ebs-csi-snapshotter-binding` correctly. 
**Merging into `master` because it looks like thats the main branch now**

stable/awsebscsi: fix role not being created and add env to values

---

stable/kommander/Chart.yaml
stable/kommander/requirements.lock
stable/kommander/requirements.yaml
stable/kommander/templates/federated-addons.yaml
stable/kommander/templates/federated-rolebindings.yaml
stable/kommander/templates/federated-roles.yaml

This is the last bits of plumbing that will allow us to deploy kommander without any resources related to kubefed for that dep.

[chore] allow disabling kubefed

---

staging/traefik-forward-auth/Chart.yaml
staging/traefik-forward-auth/templates/deployment.yaml

WHITELIST is currently alwyas set on the traefik-forward-auth deployment even if it is not needed.
If it is set, then domain-based authentication will not work.
This allows users to use oauth with the following configuration in Konvoy:
```
- name: traefik-forward-auth
enabled: true
values: |
traefikForwardAuth:
extraConfig: |
domain = "d2iq.com"
whitelist: []
allowedUser:
valueFrom:
secretKeyRef:
```

Do not set WHITELIST in traefik-forward-auth if whitelist is empty.

---

staging/cert-manager-setup/Chart.yaml
staging/cert-manager-setup/templates/issuers.yaml

Bump the Kubernetes intermediate CA cert duration to 10 years. The
default value is 90 days, which is way too short. Until we figure out a
good cert rotation story, it's better to use a longer duration to be
safe.

cert-manager-setup: bump certs duration to 10years

---

stable/dex/Chart.yaml
stable/dex/templates/certificate.yaml

The default value is 90 days, which is way too short.  Until we figure
out a good cert rotation story, it's better to use a longer duration to
be safe.

dex: bump cert duration to 10 years

---

staging/velero/Chart.yaml
staging/velero/templates/deployment.yaml
staging/velero/values.yaml

Depends on https://github.com/mesosphere/kubeaddons-extrasteps/pull/19
Waiting on that PR to be merged and retag the image.

velero: add ability to provide service annotations to the minio service

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

using latest version, tested it locally:
```
Normal  Pulling    119s  kubelet, kind-control-plane  Pulling image "mesosphere/kommander:1.114.5"
Normal  Pulled     94s   kubelet, kind-control-plane  Successfully pulled image "mesosphere/kommander:1.114.5"
```
```
$ k get pods -n kommander
NAME                                          READY   STATUS    RESTARTS   AGE
kcl-cm-5cfbd75f4c-nstzw                       2/2     Running   0          10m
kcl-tfcb-5686c45448-wht9q                     1/1     Running   0          10m
kcl-webhook-b64b7584c-5sfxh                   1/1     Running   0          10m
kommander-845684767-xprd5                     1/1     Running   0          10m
kubefed-admission-webhook-7fdcc5b56f-c6b66    1/1     Running   0          10m …
```

[kommander] bump kommander image verison for kommander

---

staging/cert-manager-setup/Chart.yaml
staging/cert-manager-setup/templates/issuers.yaml
staging/cert-manager-setup/templates/post-install-hook-job.yaml

Currently, upgrade will fail with "already exists" because the hook
resources are not managed by helm.
To be backwards compatible, we'll have to add the following:
"helm.sh/hook-delete-policy": before-hook-creation
The side effect of this is that the certificates will be re-newed
everything we do upgrade. This is fine because all services including
API server are using root CA for TLS verficiation. Re-newing the
intermediate certs shouldn't affect running services.

cert-manager: fix upgrade issue with hooks

---

staging/traefik-forward-auth/Chart.yaml
staging/traefik-forward-auth/values.yaml

Update names in the traefik-forward-auth chart

Use D2iQ repo names in traefik-forward-auth chart

---

staging/kudo/.helmignore
staging/kudo/Chart.yaml
staging/kudo/README.md
staging/kudo/templates/_helpers.tpl
staging/kudo/templates/clusterrolebinding.yaml
staging/kudo/templates/crds.yaml
staging/kudo/templates/deployment.yaml
staging/kudo/templates/namespace.yaml
staging/kudo/templates/secret.yaml
staging/kudo/templates/service.yaml
staging/kudo/templates/serviceaccount.yaml
staging/kudo/values.yaml

This is a tested version of a kudo chart for v0.7.4.   
**Notes:**
1. install `helm install --name kudo  ./kudo`
2. kudo currently does NOT support being in a namespace other than `kudo-system`.  This chart creates that ns and all manifests directly use that ns (until some future time)
3. it is possible to use a different version... to do so pass a different image tag `helm install --name kudo  ./kudo --set image.tag=v0.7.3`
4. it is possible to install without CRDs... pass `--set installCRD=false`
Fixes: https://github.com/kudobuilder/kudo/issues/920

adding kudo as a chart

---

stable/dex-controller/Chart.yaml
stable/dex-controller/templates/deployments.yaml
stable/dex-controller/values.yaml

This removes the leader election flag to workaround a potential bug in
controller runtime that might cause leader election to stuck.

dex-controller: bump to 0.2.1

---

stable/kommander/Chart.yaml
stable/kommander/templates/deployment.yaml
stable/kommander/values.yaml

Not the beta2 version by any means just wanted to go ahead and fix the polling value and add the temporary hardcoding to support konvoy 1.3 clusters.

kommander: update version + increase polling interval

---

stable/kommander/Chart.yaml
stable/kommander/templates/deployment.yaml
stable/kommander/values.yaml
stable/opsportal/Chart.yaml
stable/opsportal/values.yaml

I noticed during MWT that when Kommander was very busy polling large numbers of clusters the default liveness timeout of 1 second was sometimes not enough time for kommander to respond and this would send the pod into a termination loop.
I also added and removed some env variables to reflect the actual env config.

kommander: increase timeout for liveness, env maintenance

---

stable/dex/Chart.yaml
stable/dex/templates/deployment.yaml
stable/dex/values.yaml
staging/dex-k8s-authenticator/Chart.yaml
staging/dex-k8s-authenticator/templates/deployment.yaml
staging/dex-k8s-authenticator/values.yaml
staging/kube-oidc-proxy/Chart.yaml
staging/kube-oidc-proxy/templates/deployment.yaml
staging/kube-oidc-proxy/values.yaml
staging/traefik-forward-auth/Chart.yaml
staging/traefik-forward-auth/templates/deployment.yaml
staging/traefik-forward-auth/values.yaml
staging/traefik/Chart.yaml
staging/traefik/templates/deployment.yaml
staging/traefik/templates/init-cert-job.yaml
staging/traefik/templates/init-cert-rbac.yaml
staging/traefik/values.yaml

* Add support for injecting custom annotations to multiple charts
* Fix wrong `TRAEFIK_KONVOY_ADDONS_CONFIG_MAP` value
* Allow traefik init container to update its end-entity certificate
This PR prepares for introducing new component - Reloader https://github.com/stakater/Reloader

Add support for custom annotations

---

stable/kommander/Chart.yaml
stable/kommander/templates/federated-kubeaddons.yaml
stable/kommander/templates/hooks-kubeaddons.yaml
stable/kommander/values.yaml

change allow federating kubeaddons controller
Tested locally, we assume by default we are deploying on a konvoy cluster, to avoid deleting the kubeaddons namespace when removing the chart.

kommander: enable federation of kubeaddons controller

---

stable/kommander-thanos/Chart.yaml
stable/kommander-thanos/templates/_helpers.tpl
stable/kommander-thanos/templates/federated-addon.yaml

This PR truncates the name of the `mtls-proxy` `FederatedAddon` in order to make sure that when the addon controller tries to install its Helm chart, it generates a release name within the 53-character limit imposed by Helm.
Without this PR, the generated name for the addon's chart release may be too long, resulting in no deployment and an error like this:
```
ERROR    controller-runtime.controller    Reconciler error    {"controller": "addon", "request": "kommander-system/kommander-kubeaddons-kommander-thanos-proxy", "error": "error running cli command `helm status`. stdout: ``, stderr: `Error: invalid release name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not be longer than 53\n`: could not check whether …
```

[stable/kommander-thanos] Truncate addon name

---

staging/traefik/Chart.yaml
staging/traefik/templates/certificate.yaml

https://jira.mesosphere.com/browse/DCOS-60297
https://support.apple.com/en-us/HT210176
Upstream cert-manager issue: jetstack/cert-manager#2168
All TLS server certificates issued after July 1, 2019 (as indicated in the NotBefore field of the certificate) must follow these guidelines:
TLS server certificates must contain an ExtendedKeyUsage (EKU) extension containing the id-kp-serverAuth OID.
TLS server certificates must have a validity period of 825 days or fewer (as expressed in the NotBefore and NotAfter fields of the certificate)
For issue 1, confirmed upstream that adding "server auth" to KeyUsage (in addition to default `digital signature` and `key encipherment`) is sufficient for now. 
For issue 2, reduced the validity duration in this PR to comply with the new regulations

traefik: adapt certificate for new macOS catalina

---

stable/kommander-thanos/Chart.yaml
stable/kommander-thanos/values.yaml

Adds a service label so that Prometheus can discover the metrics endpoint for Thanos Querier. I will open up another PR once this is merged to bump the kommander-thanos dependency in kommander.

kommander-thanos: Add service label for metrics

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

With latest KCL release, konvoy versions < 1.3 are no longer supported.
Note these should be removed or updated to beta4 tags once konvoy/kubeaddons beta4 released.

chore: remove version selection with konvoy < 1.3

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

> 2) The FederatedIngress type is currently disable for kommander: https://github.com/mesosphere/charts/blob/dev/stable/kommander/values.yaml#L80 ,  I've asked in the k8s-security channel if we can enable it. If not, then we'll need to come up with another way to federate ingress records to member clusters. A federated addon is an obvious solution, but that means the overrides would live in the wrong namespace so we'd have to clean that up explicitly when a cluster is removed.
Source: https://mesosphere.slack.com/archives/CMPPXKGKX/p1572930731128900

kommander: enable federated ingress

---

stable/kommander-karma/Chart.yaml
stable/kommander-karma/templates/_helpers.tpl
stable/kommander-thanos/Chart.yaml
stable/kommander-thanos/templates/_helpers.tpl

This PR increases the length of the shortnames for these charts, which reduces the likelihood that they will generate resources with the same name.
This is intended to fix an issue where deploying Konvoy leads to this Helm error: `Error: release kommander-kubeaddons failed: federatedaddons.types.kubefed.io \"kommander-kubeaddons-kommander-proxy\" already exists`. Without this change, the `kommander-karma` and `kommander-thanos` subcharts create `FederatedAddons` that coincidentally have the same name.

Prevent name collision of karma and thanos resources

---

staging/velero/Chart.yaml
staging/velero/templates/deployment.yaml
staging/velero/templates/miniobackend.yaml

when upgrading apps/v1 in #194, the labelSelectors and labels must match
see: https://stackoverflow.com/questions/48582951/deployment-invalid-spec-template-metadata-labels-invalid-value

fix velero deployments

---

staging/karma/.helmignore
staging/karma/Chart.yaml
staging/karma/OWNERS
staging/karma/README.md
staging/karma/ci/test-values.yaml
staging/karma/templates/NOTES.txt
staging/karma/templates/_helpers.tpl
staging/karma/templates/configmap.yaml
staging/karma/templates/deployment.yaml
staging/karma/templates/ingress.yaml
staging/karma/templates/service.yaml
staging/karma/templates/serviceaccount.yaml
staging/karma/values.yaml

This PR copies the karma chart from https://github.com/helm/charts/tree/master/stable/karma, and includes the `deployment.annotations` parameter from helm/charts#18686. Copying the chart to this repo is only necessary to pull in the changes from that PR; it can be removed once the PR is merged.
This is necessary in order to set annotations on the deployment that cause it to be restarted by [the Reloader addon](https://github.com/stakater/Reloader) when its configmap is updated.

Add karma chart with deployment.annotations parameter

---

staging/flagger/.helmignore
staging/flagger/Chart.yaml
staging/flagger/README.md
staging/flagger/charts/flagger-loadtester/.helmignore
staging/flagger/charts/flagger-loadtester/Chart.yaml
staging/flagger/charts/flagger-loadtester/README.md
staging/flagger/charts/flagger-loadtester/templates/NOTES.txt
staging/flagger/charts/flagger-loadtester/templates/_helpers.tpl
staging/flagger/charts/flagger-loadtester/templates/deployment.yaml
staging/flagger/charts/flagger-loadtester/templates/rbac.yaml
staging/flagger/charts/flagger-loadtester/templates/service.yaml
staging/flagger/charts/flagger-loadtester/templates/virtual-node.yaml
staging/flagger/charts/flagger-loadtester/values.yaml
staging/flagger/templates/NOTES.txt
staging/flagger/templates/_helpers.tpl
staging/flagger/templates/account.yaml
staging/flagger/templates/crd.yaml
staging/flagger/templates/dashboard.yaml
staging/flagger/templates/deployment.yaml
staging/flagger/templates/job.yaml
staging/flagger/templates/prometheus.yaml
staging/flagger/templates/psp.yaml
staging/flagger/templates/rbac.yaml
staging/flagger/values.yaml

This PR adds flagger.
In particular it,
- adds a flagger chart, with a flagger-loadtester subchart
- adds a grafana dashboard for tracking flagger deployments. The dashboard is called "Istio Canary" (that's the default name.) It is deployed to the `kubeaddons` namespace, regardless of where flagger is installed.
- adds a job to label the namespace in which flagger gets installed with `istio-injection=enabled` as flagger relies on istio.
- for the job to execute, we annotate the job, serviceaccount, clusterrole, clusterrolebinding with `helm.sh/hook: pre-install` so those actions are performed before pods are created.
The plan is to install flagger into a `kubeaddons-flagger` namespace, which canthen be marked with `istio-injection=enabled`. We don't want all pods in the `kubeaddons` …

flagger(,-loadtester): Add chart

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

This is needed to be overridable in kommander kubeaddon so we can test
with the betas.

feat(kommander): Update defaulting kubeaddons-configs values

---

stable/kommander/Chart.yaml
stable/kommander/templates/grafana/dashboards/k8s-resources-clusters.yaml

This is a kommander-only dashboard. CPU/Mem graphs taken from the `Kubernetes / Compute Resources / Cluster` community dashboard and reworked to show multiple clusters view. Pretty barebones, just want to get this out for the release; we should plan on fleshing out more dashboards in the future.

kommander: multi-cluster cpu/mem dashboard

---

stable/kommander/templates/federated-crds.yaml
staging/kubeaddons-catalog/Chart.yaml
staging/kubeaddons-catalog/files/crd_addonrepository.yaml
staging/kubeaddons-catalog/templates/crds.yaml
staging/kubeaddons-catalog/values.yaml

Manage crds correctly, catalog has been missing this. 
Tested this locally and works as expected.
bumped catalog to point to image version 0.5.3.

catalog: manage crd correctly for upgrades

---

stable/kommander/Chart.yaml
stable/kommander/templates/grafana/dashboards/thanos-query-dashboard.yaml
stable/kommander/values.yaml

This adds an additional datasource `KommanderPrometheus` to the centralized Grafana running on Kommander, which points to the Prometheus (kubeaddon) running on the Kommander cluster. The Thanos Querier dashboard is modified to use the datasource `KommanderPrometheus` instead of `ThanosQuery`, which Kommander cluster metrics don't roll up to (so currently this dashboard is empty).

kommander: Add kommander prom datasource for thanos querier dashboard

---

stable/dispatch/Chart.yaml
stable/dispatch/charts/minio/Chart.yaml
stable/dispatch/charts/minio/templates/deployment.yaml
stable/dispatch/charts/tekton/Chart.yaml
stable/dispatch/charts/tekton/templates/tekton.yaml

Follow up to https://github.com/mesosphere/charts/pull/275
Tested with Konvoy this time and a few other changes to support Kubernetes v1.16.

dispatch: fix api versions and app selectors

---

stable/kommander/Chart.yaml
stable/kommander/templates/deployment.yaml
stable/kommander/values.yaml

We need to overwrite our base address of the catalog. without the overwrite we assume it lives under http://kommander-kubeaddons-kubeaddons-catalog.kommander.svc. Running this kommander chart version won't work against konvoy without this fix

Set catalog address for kommander chart

---

staging/traefik/Chart.yaml
staging/traefik/README.md
staging/traefik/templates/default-cert-secret.yaml
staging/traefik/values.yaml

This disables the creation of default-cert-secret when an external
certificate manager is being used.
Addresses: https://jira.mesosphere.com/browse/DCOS-60978

Add useCertManager option to traefik

---

staging/traefik-forward-auth/Chart.yaml
staging/traefik-forward-auth/templates/deployment.yaml

TFA now uses sessions to store group claims

[traefik-forward-auth] reuse secret for session key

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/values.yaml

This reverts commit 97d023b2c998bb0976a58907ead4591da7ce2c6b.
Reverted because changes were made in the wrong repo.

Revert "Fix grafana internal urls"

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

These versions fail to install, I think because they are using older versions of konvoy configured [here](https://github.com/mesosphere/kubernetes-base-addons/blob/master/addons/kommander/1.163.x/kommander-1.yaml#L51).  We could maybe change that to use the latest konvoy? I'm not sure we need these versions so I am ok just removing as options.
thoughts @jimmidyson ?

[kommander] remove older versions of kubernetes

---

Makefile
stable/dex/Chart.yaml
stable/dex/templates/config-openssl.yaml
staging/cert-manager-setup/Chart.yaml
staging/cert-manager-setup/ci/test-values.yaml
test/ct-e2e.yaml
test/e2e-kind.sh
test/kind-config.yaml

* Adds a testing script that tests the charts using `ct lint-and-install --upgrade`.
* Backports a fix from upstream `dex` chart to allow install and upgrade to succeed (https://github.com/helm/charts/pull/18380)
* Clean up EOL whitespace

[test] Add chart install and upgrade testing

---

stable/opsportal/Chart.yaml
stable/opsportal/templates/landing.yaml

JIRA: https://jira.mesosphere.com/browse/DCOS-62720
Upgrade from `1.15-alpine` which contains critical security issues.

stable/opsportal: bump nginx container to 1.17-alpine

---

Makefile

Adds `test` and `lint` targets that pull in target deps. Add the `ct.test` target that calls the e2e test script.

make: add lint and test targets

---

stable/kommander-karma/Chart.yaml
stable/kommander-karma/README.md
stable/kommander-karma/values.yaml
stable/kommander-thanos/Chart.yaml
stable/kommander-thanos/README.md
stable/kommander-thanos/values.yaml

https://jira.mesosphere.com/browse/DCOS-62153
We are modifying karma and thanos (and grafana, done in followup PR) links to be behind `/ops/portal/kommander/monitoring/<>` instead of `/kommander/monitoring/<>`. Those ingress changes are done here along with chart bumps. After this PR is merged, I will open up a followup PR to do the following:
1. bump the thanos/karma dependencies in the Kommander chart
1. change the Kommander ui to point to `/ops/portal/kommander/ui` (see https://jira.mesosphere.com/browse/DCOS-62690 and we can close this PR https://github.com/mesosphere/charts/pull/338)
1. modify the grafana ingress to point to the new url
1. bump kommander chart version
Following the above PR, I will close out this ticket by bumping kommander to the updated version^ in …

[kommander-karma] [kommander-thanos] Modify UI links

---

staging/traefik/Chart.yaml
staging/traefik/templates/certificate.yaml
staging/traefik/templates/init-cert-job.yaml

Tested via `helm install /Users/armand/Code/charts/staging/traefik --dry-run --values=/Users/armand/Desktop/traefik.yaml`.

traefik: add objects depending on useCertManager

---

Makefile
test/e2e-kind.sh

Fixes the integration test script such that it successfully runs on TC (see last run in https://github.com/mesosphere/charts/pull/346).
Also consolidates the version of the `chart-testing` docker image to a single variable held in the `Makefile`

 test: detect teamcity and mount git 

---

stable/kommander-karma/Chart.yaml
stable/kommander-karma/README.md
stable/kommander-karma/values.yaml

My bad, the trailing slash shouldn't have been added - fixing this here and will follow the same protocol as https://github.com/mesosphere/charts/pull/347

kommander-karma: Remove trailing slash from ingress path

---

staging/velero/Chart.yaml
staging/velero/templates/miniobackend.yaml

JIRA: https://jira.mesosphere.com/browse/DCOS-62691
Our `velero` chart is modified and includes `minio` deployemnt. The `minio` is not included in upstream `velero` chart - https://github.com/vmware-tanzu/helm-charts/blob/f721d7a7138e0c3138a89fe9c097c35d9e4ee2cd/README.md
Builds:
- aws - https://teamcity.mesosphere.io/viewLog.html?buildId=2547553&buildTypeId=ClosedSource_MkeLite_MkeLiteE2e
- azure - https://teamcity.mesosphere.io/viewLog.html?buildId=2547551&buildTypeId=ClosedSource_Konvoy_KonvoyE2eAzure
- docker - https://teamcity.mesosphere.io/viewLog.html?buildId=2547555&buildTypeId=ClosedSource_Konvoy_KonvoyE2eDocker

staging/velero: bump minio k8s operator to 1.0.6 (security update)

---

Makefile

This works in combination with the master cleanup (see #372) to keep a clean master branch, with only chart repo packages and no chart sources.
Please merge #372 first so I don't have to rebase that, although that wouldn't be too hard anyway.

chore: Do not add chart sources to master

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

The Kommander CPU limit is a little too loose for its actual requirements. Javascript is single-threaded, after all.

fix: reduce kommander CPU limit

---

stable/kommander/Chart.yaml

appVersion field is supposed to be the Kommander version we're going to communicate, so it should start with 1.0.0 when we release GA.
https://helm.sh/docs/topics/charts/#the-appversion-field

Reset Kommander appVersion to 1.0.0

---

stable/kommander/Chart.yaml

All PRs are failing claiming that the kommander chart version needs bumped. The last commit did not bump the chart version but somehow passed CI. This fixes the CI failures.

Add chart version bump to fix lint failure

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/mesosphere-hooks/post-install-hooks.yaml

https://jira.mesosphere.com/browse/DCOS-62216
This fixes an issue that may cause the Grafana home dashboard to be empty. If the job that sets Grafana's home dashboard runs before Grafana's API is ready, it will fail after one attempt. This PR changes the job to retry requests that fail with transient errors.
I tested this PR by deploying a Konvoy cluster with the prometheus and prometheusadapter addons disabled, deploying the prometheus-operator chart from this branch, browsing to `/ops/portal/grafana`, and observing that the home dashboard is set to "Kubernetes / Compute Resources / Cluster".

Retry requests when setting Grafana's home dashboard

---

stable/opsportal/Chart.yaml
stable/opsportal/templates/hooks-roles.yaml
stable/opsportal/templates/ingress-opsportal.yaml
stable/opsportal/values.yaml

Removed ingress records of apps from opsportal, these will be now produced in each application. Added deprecation notice, and remove ingress records.
https://jira.d2iq.com/browse/DCOS-63429

[opsportal] remove application ingress records

---

stable/kommander-karma/Chart.yaml
stable/kommander-karma/templates/cleanup-configmap.yaml
stable/kommander-thanos/Chart.yaml
stable/kommander-thanos/templates/query-stores-configmap.yaml

Change the cleanup job hook weights for kommander-thanos and kommander-karma, so that sa/clusterroles are all set up prior to these cleanup scripts to avoid permission errors.
Please see the Testing section of https://github.com/mesosphere/charts/pull/386

kommander-thanos/karma: Cleanup job hook weights

---

staging/traefik/Chart.yaml
staging/traefik/templates/tests/test-configmap.yaml
staging/traefik/templates/tests/test.yaml
staging/traefik/values.yaml

We were deploying the test resources, that should not happen on production.

chore: add enabled property to deploy tests

---

staging/cert-manager-setup/Chart.yaml
staging/cert-manager-setup/ci/general-test-values.yaml
staging/cert-manager-setup/ci/test-values.yaml
staging/cert-manager-setup/requirements.yaml
staging/cert-manager-setup/templates/certificates.yaml
staging/cert-manager-setup/templates/clusterissuer.yaml
staging/cert-manager-setup/templates/clusterissuers.yaml
staging/cert-manager-setup/templates/clusterrole.yaml
staging/cert-manager-setup/templates/clusterrolebinding.yaml
staging/cert-manager-setup/templates/issuers.yaml
staging/cert-manager-setup/templates/post-install-hook-job.yaml
staging/cert-manager-setup/values.yaml

This change allows one to define multiple certificates, issuers and clusterissuers. Note that it maintains backwards compatibility. 
- fixes a job issue where SA is not defined and so task cannot complete, this is particularly harmful for upgrades
- removes job that contains a sleep, that isnt necessary.
tested out the chart as mentioned below

[cert-manager-setup] allow for multiple clusterissuers

---

staging/nfs-server-provisioner/Chart.yaml
staging/nfs-server-provisioner/OWNERS
staging/nfs-server-provisioner/README.md
staging/nfs-server-provisioner/templates/NOTES.txt
staging/nfs-server-provisioner/templates/_helpers.tpl
staging/nfs-server-provisioner/templates/clusterrole.yaml
staging/nfs-server-provisioner/templates/rolebinding.yaml
staging/nfs-server-provisioner/templates/service.yaml
staging/nfs-server-provisioner/templates/serviceaccount.yaml
staging/nfs-server-provisioner/templates/statefulset.yaml
staging/nfs-server-provisioner/templates/storageclass.yaml
staging/nfs-server-provisioner/values.yaml

This chart is derived from the upstream chart:
https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner
The reason we put it here is because the upstream chart seems
unmaintained. The stable head is broken. We need to apply the following
patch to make it work:
https://github.com/helm/charts/pull/19260
Tested locally with a Konvoy cluster:
```bash
helm install --name nfs-server-provisioner .
```
And apply the following PVCs:
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: nfs-test
spec:
storageClassName: nfs
accessModes:
- ReadWriteMany
resources:
requests:
storage: 100Mi
```
```bash
k get pvc
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nfs-test     Bound …
```

nfs-server-provisioner: add base chart

---

stable/kommander/Chart.yaml
stable/kommander/templates/grafana/opsportal-username-secret.yaml
stable/kommander/templates/hooks-kubeaddons.yaml

There's a [bug](https://mesosphere.slack.com/archives/CN5S0UKAA/p1580762260057800) in upgrading kommander chart to >=0.3.21
```
$ kubectl -n kommander describe pod set-kommander-grafana-home-dashboard-td4s2
...  
Warning  Failed     57s (x8 over 2m20s)  kubelet, ip-10-0-128-187.us-west-2.compute.internal  Error: secret "ops-portal-username" not found
```
I added a `pre-upgrade` hook to the `copy-ops-portal-username` job to ensure that the username secret is copied over in upgrades as well as installs. Also modified the kubectl command to ensure that it does not fail if the resource already exists.
I tested this by hosting the chart on my GH. I `konvoy up` with base addons version `stable-1.15.6-4`, then redeployed with the hosted updated kommander chart 0.3.25 (`kubernetes-base-addons` …

kommander: Fix upgrade bug

---

stable/opsportal/templates/ingress-opsportal-roles.yaml
stable/opsportal/templates/kibana-roles.yaml
stable/opsportal/values.yaml

This adds the base /ops/portal roles as well as roles for /ops/portal/kibana. We need to add kibana roles in the opsportal chart until https://jira.d2iq.com/browse/D2IQ-63746 is completed.

[opsportal] add opsportal and kibana RBAC roles

---

Makefile
test/ct-e2e.yaml
test/ct.yaml

I am seeing a lot of runs against charts that were not changed, and this is because we have not updated CI to point to master branch and instead it has been pointing to the dev branch. This should fix these issues.

CI: changed branch since we are working off master now

---

stable/opsportal/Chart.yaml
stable/opsportal/templates/ingress-opsportal-roles.yaml
stable/opsportal/values.yaml
staging/kube-oidc-proxy/Chart.yaml
staging/kube-oidc-proxy/templates/clusterrole.yaml
staging/kube-oidc-proxy/values.yaml

* Enable posting in /ops/portal/graphql
* Required for the operations portal to load with only the `view` role
* Enable token passthrough
* https://jira.d2iq.com/browse/D2IQ-63673

[opsportal, kube-oidc-proxy] Chart updates

---

stable/opsportal/Chart.yaml
stable/opsportal/values.yaml

Fixes https://jira.d2iq.com/browse/D2IQ-63789
Fix from https://github.com/mesosphere/kubeaddons-extrasteps/pull/56
Bumps the addon-initializer image.

opsportal: bump extra-steps to fix RBAC bug

---

stable/kommander/Chart.yaml
stable/kommander/templates/grafana/dashboards/k8s-resources-clusters.yaml

https://jira.d2iq.com/browse/D2IQ-64541
Add cluster filter to the overview grafana dashboard and add a stat to the top with current number of managed clusters.

kommander: Add cluster filter and # managed clusters to overview dashboard

---

staging/dex-k8s-authenticator/Chart.yaml
staging/dex-k8s-authenticator/templates/deployment.yaml
staging/dex-k8s-authenticator/values.yaml

This is done to fix constant restart when dex-k8s-auth is under load of >= 50 konvoyclusters.
related to: https://jira.d2iq.com/browse/D2IQ-56464

fix: probe values under high load

---

Makefile

`make ct.lint` was failing on OSX due to /var/folders not having file
sharing permissions for Docker on Mac. The problem is OSX symlinks /var
to /private/var. Adding the folder to Docker shared paths didn't seem to
fix the issue either.
Without fix:  
```sh
> make ct.lint
docker run -t --rm -u 502:20 -v /Users/samtran/Dev/mesosphere/k8s/svt-charts:/charts -v /Users/samtran/Dev/mesosphere/k8s/svt-charts/test/ct.yaml:/etc/ct/ct.yaml -v /var/folders/12/6g69fhjn06v3l_l9nyjl33700000gp/T/tmp.gw5rmN1F:/.helm -w /charts quay.io/helmpack/chart-testing:v2.4.0 ct lint
docker: Error response from daemon: Mounts denied:
The path /var/folders/12/6g69fhjn06v3l_l9nyjl33700000gp/T/tmp.gw5rmN1F
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... …
```

fix: Add /private prefix for OSX docker mount

---

stable/kommander/Chart.yaml
stable/kommander/templates/grafana/dashboards/k8s-resources-clusters.yaml
stable/kommander/templates/grafana/hooks-home-dashboard.yaml
stable/kommander/values.yaml

Fixed the cluster summary dashboard which wasn't getting automatically imported correctly (reworked the query to use the same datasource instead of trying to use two on the same dashboard which seems to be causing issues) and also added `[Global]` to the dashboard name and changed the uid so it's different from the konvoy-equivalent dashboard's name/uid (just to avoid potential name and uid collisions if someone were to ever deploy a grafana that pulls in both sets of dashboards).
I'll be opening another PR later today adding more central dashboards (porting over the base k8s dashboards from konvoy), wanted to keep them separate since this one's a bug fix.

kommander: Fixes to the clusters summary dashboard

---

README.md
TESTING.md

This adds a `TESTING.md` guide to test local chart changes against a running Konvoy cluster.

chore: Add testing instructions for Konvoy

---

staging/traefik-forward-auth/Chart.yaml
staging/traefik-forward-auth/templates/deployment.yaml
staging/traefik-forward-auth/values.yaml

Provide an option to skip installing the TFA deployment. TFA will
refuse to start up if the OIDC provider is not ready. This chart option
allows us to stage TFA to the cluster and then later update it with
proper OIDC provider information when available.
https://jira.d2iq.com/browse/D2IQ-64824

tfa: add an option to stage TFA

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

When attaching kommander to itself, we observed an issue that the
kommander UI route (/ops/portal/kommander/ui, priority 2) will be
overrided by the ops portal overrides (/ops/portal, priority 3).
Apparently, traefik will first evaluate priority and then do the longest
prefix match on the route path. As a result, we won't be able to see
Kommander UI after self attaching.
This patch fixed the issue by bumping kommander UI route priority to 4.
Tested on a live cluster and problem goes away after this change.

kommander: bump kommander-ui ingress priority

---

stable/kommander-karma/Chart.yaml
stable/kommander-karma/values.yaml
stable/kommander-thanos/Chart.yaml
stable/kommander-thanos/values.yaml

The reason is the same as that in
https://github.com/mesosphere/charts/pull/474
When attaching kommander to itself, we observed an issue that the
kommander karma and thanos route (/ops/portal/kommander/monitoring/...,
priority 2) will be overrided by the ops portal overrides (/ops/portal,
priority 3).
Apparently, traefik will first evaluate priority and then do the longest
prefix match on the route path. As a result, we won't be able to see
Kommander karma and thanos UIs after self attaching.
This patch fixed the issue by bumping route priorities to 4.

chore: bump ingress priority for karma and thanos

---

stable/kommander-karma/Chart.yaml
stable/kommander-thanos/Chart.yaml

using quotes in appversions breaks consuming templates (ingress-roles in this case)

fix: unquote appversion values

---

staging/generic-ingress/templates/ingresses.yaml

The YAML is not valid due to `---` being aligned to the wrong place.
This patch fixed it.
Tested with the following:
```
helm template -f new-values.yaml . | yamllint -
```
`new-values.yaml` the same we use in KCL
https://github.com/mesosphere/kommander-cluster-lifecycle/blob/mh/kubefed/ops-portal-ingress/chart/kommander-cluster-lifecycle/templates/federatedaddon_ops_portal_ingress.yaml#L27-L75

chore: fix generic-ingress chart

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/prometheus-operator/crds.yaml

The original crd management had a check to not install crds if they exist, this was removed in a huge update and so was missed.

[prometheus-operator] fix: revert update that removed crds installation check.

---

Dispatchfile
test/e2e-kind.sh
test/kind-config.yaml

This reverts commit 44fef52.
and adds a simple fix at this line: https://github.com/mesosphere/charts/compare/fix_dispatchfile?expand=1#diff-37eda1430799e62f92596aa54fae0596R49
This initially was reverted because the Dispatch build was failing and causing TeamCity CI to fail as well. The problem was a certain entrypoint.sh that was being downloaded. That file was in a private repo and required a token in its URL. That token was not a security hazard; it only exposed that single revision of that single file. However, little did I know, that token expires after a few days, which was causing the failure. We are also trying to upstream that file in the kubernetes-sigs/kind repo, so there is no harm in making it public. I added it as a gist for the d2iq-dispatch user so we can download it from …

Readd Dispatchfile

---

Dispatchfile

The base image already has those packages installed, anyway.

fix: don't install packages as they're already installed

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver-error.yaml

This is a workaround for the `PrometheusRuleFailures` alert and Prometheus slowness [observed](https://mesosphere.slack.com/archives/CPF8FQ4PN/p1583179108061300)  on the Soak cluster.
- Deleting the `status_class:apiserver_request_total:rate3d` record.
- Deleting the `status_class_5xx:apiserver_request_total:ratio_rate3d` record.
- Modifying the `ErrorBudgetBurn` alert.
- Changing the `prometheus-operator` chart version from `8.7.3` to `8.7.4`
Jira ticket: https://jira.d2iq.com/browse/D2IQ-65026.
GH issue on the upstream repository: https://github.com/coreos/prometheus-operator/issues/3036

Workaround for PrometheusRuleFailures alert #D2IQ-65026

---

staging/traefik/Chart.yaml
staging/traefik/README.md
staging/traefik/templates/configmap.yaml
staging/traefik/templates/service.yaml
staging/traefik/values.yaml

Allow extra entrypoints to be defined (and the front end ports).
Tested with
```yaml
extraServicePorts:
- name: velero-minio
port: 9000
protocol: TCP
targetPort: 9000
extraConfigEntrypoints: |
[entryPoints.velero]
address = ":9000"
[entryPoints.velero.tls]
[entryPoints.velero.tls.defaultCertificate]
certFile = "/ssl/tls.crt"
keyFile = "/ssl/tls.key"
```

traefik: allow extra entrypoints

---

stable/awsebscsiprovisioner/Chart.yaml
stable/awsebscsiprovisioner/ci/annotations-kube2iam-usage.yaml
stable/awsebscsiprovisioner/ci/more-specific-settings.yaml
stable/awsebscsiprovisioner/templates/_helpers.tpl
stable/awsebscsiprovisioner/templates/csidriver.yaml
stable/awsebscsiprovisioner/templates/daemonset.yaml
stable/awsebscsiprovisioner/templates/roles.yaml
stable/awsebscsiprovisioner/templates/statefulset-snapshot-controller.yaml
stable/awsebscsiprovisioner/templates/statefulset.yaml
stable/awsebscsiprovisioner/templates/storageclass.yaml
stable/awsebscsiprovisioner/values.yaml
test/ct-e2e.yaml
test/e2e-kind.sh

[Documentation](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/v0.5.0/docs/README.md)
filename  | sha512 hash
--------- | ------------
[v0.5.0.zip](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/archive/v0.5.0.zip) | `c53327e090352a7f79ee642dbf8c211733f4a2cb78968ec688a1eade55151e65f1f97cd228d22168317439f1db9f3d2f07dcaa2873f44732ad23aaf632cbef3a`
[v0.5.0.tar.gz](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/archive/v0.5.0.tar.gz) | `ec4963d34c601cdf718838d90b8aa6f36b16c9ac127743e73fbe76118a606d41aced116aaaab73370c17bcc536945d5ccd735bc5a4a00f523025c8e41ddedcb8`
* Add a cmdline option to add extra volume tags ([#353](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/353), [@jieyu](https://github.com/jieyu))
* Switch to use kustomize for manifest …

chore: update awsebscsiprovisioner chart

---

stable/awsebscsiprovisioner/Chart.yaml
stable/awsebscsiprovisioner/templates/roles.yaml
stable/awsebscsiprovisioner/templates/statefulset-snapshot-controller.yaml

- the snapshot controller is working beginning with kubernetes version 1.17
- changed / updated the permissions for the `ebs-external-attacher-role` as the `patch` permission is a must have now.
- changed / updated the `apiGroups` and `resources` for `ebs-external-attacher-role` as these are the ones from upstream and we have same here https://github.com/mesosphere/charts/pull/511/files#diff-2deb8043c4fff4cb398fc42fad8e771fR45-R46
more details see https://kubernetes-csi.github.io/docs/csi-node-object.html
quote: ```In the move from alpha to beta, the API Group for this object changed from csi.storage.k8s.io/v1alpha1 to storage.k8s.io/v1beta1.```
[D2IQ-64990]
[D2IQ-64990]: https://jira.d2iq.com/browse/D2IQ-64990

fix: disable awsebscsiprovisioner snapshot-controller and correct ebs-external-attacher-role

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

first step to address kommander chart not being able to install w/o addon. I was _not_ able to install the chart on its own, but that is no change to before. we need to fix that going forward
This PR adds everything from addon to chart, companioning PR removing these things from addon:

chore: move values from addon to chart

---

staging/dex-k8s-authenticator/Chart.yaml
staging/dex-k8s-authenticator/html-templates/linux-mac-common.html
staging/dex-k8s-authenticator/templates/configmap.yaml
staging/dex-k8s-authenticator/values.yaml

This is for the case when the traefik ingress uses a valid Let's Encrypt
cert that can be trusted by the system default root CA bundles.
Currently, we always display the k8s root CA in the /token page for the
kubectl setup instructions. And k8s root CA cannot validate the Let's
Encrypt cert, leading to authentication errors. See more details in:
https://jira.d2iq.com/browse/D2IQ-65233
This patch introduces an option to use system default CA bundles. This
requires an extra step change in the corresponding repo (coming soon).

dka: allow using system default CA

---

staging/traefik/Chart.yaml
staging/traefik/values.yaml

dcca37fe Prepare release v1.7.23
a610f0b2 Force http/1.1 for upgrade (Traefik v1)
ded285be Fix sameSite (Traefik v1)
4b31d330 fix: max TLS version.
5a6652fc Prepare release v1.7.22
91b0e2e4 Complete TLS example for Kubernetes Ingress in user guide
554bceb7 Skip redirection with invalid regex syntax.
ce762126 fix: manual provider code name.
d474c87c Updated rbac and demonset example bloc
86277223 Update to go1.14
09fa1e65 Fix typo in user guide.
c3125104 Clear closed hijacked h2c connections
31786f71 Prepare release v1.7.21
d7ed42d6 Fix sample for ssl-header in docs
4c709c2f Improve rate-limiting doc
8dac0767 Fix finding proper provided certificate when ACME is enabled
0b039499 don't create http client in each request in forward auth
21249754 Fix dnspod update.
e4725619 Update the k8s api …

chore: bump traefik image from 1.7.12 to 1.7.23

---

staging/kube-oidc-proxy/Chart.yaml
staging/kube-oidc-proxy/templates/deployment.yaml
staging/kube-oidc-proxy/values.yaml

Allow to use system default CA in the image or a bundle from the hosting OS.
Tested with the following combinations by checking `helm template` output:
```yaml
oidc:
caSystemDefault: true
```
```yaml
oidc:
caCertPemHostPath: /etc/ssl/certs/ca-bundle.crt
```
```yaml
oidc:
caSystemDefault: true # This will take precedence.
caCertPemHostPath: /etc/ssl/certs/ca-bundle.crt
```
[D2IQ-65234]: https://jira.d2iq.com/browse/D2IQ-65234

feat(kube-oidc-proxy): added caSystemDefault and caCertPemHostPath

---

stable/kommander/Chart.yaml
stable/kommander/charts/kommander-karma/Chart.yaml
stable/kommander/charts/kommander-karma/templates/federated-addon.yaml

Previously we federated karma-proxy to non-Konvoy clusters without reason. Now that we can differentiate cluster types we are able to fix this with this PR.
https://jira.d2iq.com/browse/D2IQ-65932

fix: federate karma-proxy only to Konvoy clusters

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/mesosphere-hooks/grafana-default-dashboard-hook.yaml

This affects the prometheus-operator by not deploying the job grafana-default-dashboard if we set defaultDashboardsEnabled to false.
Related ticket: https://jira.d2iq.com/browse/D2IQ-66014
This was tested by deploying the updated chart combined with a `values.yaml` specifying:
```
grafana:
defaultDashboardsEnabled: false
```

fix: grafana dashboard job only if defaultDashboardsEnabled

---

stable/kommander/Chart.yaml
stable/kommander/templates/grafana/hooks-home-dashboard.yaml
staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/mesosphere-hooks/grafana-default-dashboard-hook.yaml
staging/prometheus-operator/values.yaml

hook should not point to static service name, it's now dynamic, and should fail silently to allow prometheus to deploy. This latter point is quite specific as for the hook to actually succeed it requires a specific configuration of grafana allowing for automatic creation of a user.

[prometheus-operator] fix: hook should not call static service name

---

staging/cert-manager-setup/Chart.yaml
staging/cert-manager-setup/ci/general-test-values.yaml
staging/cert-manager-setup/templates/certificates.yaml
staging/cert-manager-setup/templates/clusterissuer.yaml
staging/cert-manager-setup/values.yaml

- `usages` is not part of an Issuer / IssuerRef, it belongs to the Certificate
see https://docs.cert-manager.io/en/release-0.10/reference/api-docs/index.html#certificate-v1alpha1
[D2IQ-65995]
[D2IQ-65995]: https://jira.d2iq.com/browse/D2IQ-65995

fix(cert-manager-setup): `usages` definition

---

stable/awsebscsiprovisioner/Chart.yaml
stable/awsebscsiprovisioner/templates/roles.yaml

[D2IQ-66019]
The missing `volumesnapshots/status` permission for `ebs-csi-controller-sa` leads to the following error message:
```
E0325 13:03:34.201182       1 goroutinemap.go:150] Operation for "create-kubeaddons/ebs-volume-snapshot[33fd69c5-4c65-497b-ab32-096e98c0e27c]" failed. No retries permitted until 2020-03-25 13:05:36.201159485 +0000 UTC m=+4622.225139898 (durationBeforeRetry 2m2s). Error: "snapshot controller failed to update kubeaddons/ebs-volume-snapshot on API server: volumesnapshots.snapshot.storage.k8s.io \"ebs-volume-snapshot\" is forbidden: User \"system:serviceaccount:kube-system:ebs-csi-controller-sa\" cannot update resource \"volumesnapshots/status\" in API group \"snapshot.storage.k8s.io\" in the namespace \"kubeaddons\""
I0325 13:06:34.100708       1 …
```

missing volumesnapshots/status permission

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/crds/crd-prometheus.yaml
staging/prometheus-operator/patch/README.md
staging/prometheus-operator/patch/patch.sh
staging/prometheus-operator/patch/patch_50_prometheus_crd.sh
staging/prometheus-operator/patch/patch_prometheus_crd.sh

This is a hack to work around a deficiency in controller-gen with
sub-components.
With subcomponents, the only option controller-gen gives
is for top-level api types, to mark them with
kubebuilder:validation:EmbeddedResource which creates a
x-kubernetes-embedded-resource marker causing the validator to reject
the resource if it's missing the ApiType and Kind for the subresource.
Since volumeClaimTemplate doesn't actually _require_ those, this causes
the templated resource to fail validation.
This hack is a workaround pending a fix of https://github.com/coreos/prometheus-operator/issues/3093

bug: fix missing metadata name parameter

---

staging/kubeaddons-catalog/Chart.yaml
staging/kubeaddons-catalog/values.yaml

Per D2IQ-64149, we are experiencing the following error when requesting cert from Lets Encrypt:
`{"level":"info","msg":"legolog: [INFO] [catalog.kubeaddons.localhost] acme: Obtaining bundled SAN certificate","time":"2020-02-11T20:42:58Z"} {"level":"error","msg":"Unable to obtain ACME certificate for domains \"catalog.kubeaddons.localhost\" detected thanks to rule \"Host:catalog.kubeaddons.localhost\" : unable to generate a certificate for the domains [catalog.kubeaddons.localhost]: acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"catalog.kubeaddons.localhost\": Domain name does not end with a valid public suffix (TLD), url: …

Disable Ingress by default as discussed per D2IQ-64149

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/mesosphere-hooks/grafana-default-dashboard-hook.yaml

This fixes the error:
```
warning: Release prometheus-kubeaddons post-upgrade prometheus-operator/templates/mesosphere-hooks/grafana-default-dashboard-hook.yaml failed: Job.batch "prometheus-kubeaddons-\"grafana-default-dashboard\"" is invalid: [metadata.name: Invalid value: "prometheus-kubeaddons-\"grafana-default-dashboard\"": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.labels: Invalid value: "prometheus-kubeaddons-\"grafana-default-dashboard\"": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end …
```

bug: fix misplaced quotes

---

staging/knative/Chart.yaml
staging/knative/charts/serving/Chart.yaml
staging/knative/charts/serving/templates/custom-metrics-apiservice.yaml
staging/knative/charts/serving/templates/gateway.yaml
staging/knative/charts/serving/templates/namespace.yaml
staging/knative/charts/serving/values.yaml
staging/knative/requirements.yaml
staging/knative/values.yaml

Added configurable options to knative chart:
- Added requirements.yaml to allow turn on/off individual knative components.
- Made knative serving api service configurable, which may conflict with the konvoy custom metrics api service.
- Made knative serving gateway https host configurable, which may conflict with the default istio gateway.
- Made knative serving namespace metadata label configurable, which allows operators to add istio ca override or any additional labels.
helm install:
```
➜  kubeflow-poc git:(gilbert/dev) ✗ helm install --name knative-kubeaddons ~/workspace/mesosphere/charts/staging/knative
NAME:   knative-kubeaddons
LAST DEPLOYED: Wed Mar 25 22:23:56 2020
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1/ClusterRole
NAME                                AGE …
```

knative: Added requirements.yaml and enable/disable switches to knative

---

stable/cluster-autoscaler/Chart.yaml
stable/cluster-autoscaler/templates/clusterrole.yaml

The cluster-autoscaler cannot handle konvoyclusters.

fix: add permissions to handle konvoycluster resources

---

test/e2e-kind.sh

As of Dec 11, 2019: https://github.com/kubernetes-sigs/kind/issues/118 Kind supports PVC, as such we do not need to install a new storage class. In addition the new storage class we do install is not set as default, which is a bug.

fix: Kind already supports PVC (e2e tests)

---

staging/velero/Chart.yaml
staging/velero/charts/minio/Chart.yaml
staging/velero/charts/minio/templates/_helpers.tpl
staging/velero/charts/minio/templates/deployment.yaml
staging/velero/charts/minio/templates/statefulset.yaml
staging/velero/requirements.lock
staging/velero/requirements.yaml

This is a backport of https://github.com/helm/charts/pull/20091/ In the currently used charts the `extraArgs` chart option does not work, hence we cannot pass the `--json` option to the minio server.
Having enabled the json logging, we will be able to properly correlate log eventsas described in [1]. 
[1] https://jira.d2iq.com/browse/D2IQ-66612

velero: backport of extraArgs fix: #20091

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/values.yaml

The purpose of this task is to update our prometheus operator to v0.35.1 as per D2IQ-66835.

[D2IQ-66835] Prom Operator v0.35.1

---

stable/kommander/Chart.yaml
stable/kommander/templates/kommander-ui/ingress-roles.yaml
stable/kommander/values.yaml
stable/opsportal/Chart.yaml

Currently the opsportal-kommander-view ClusterRole results in a 401 when trying to reach the Kommander UI with the following error due to not being allowed to POST to:
`/ops/portal/kommander/ui/graphql`
This is similar to the opsportal-view ClusterRole where the user needs to be able to POST to graphql. 
[D2IQ-66861]
[D2IQ-66861]: https://jira.d2iq.com/browse/D2IQ-66861

[D2IQ-66836] opsportal-kommander-view ClusterRole 401 viewing Kommander UI

---

stable/opsportal/Chart.yaml
stable/opsportal/templates/kibana-roles.yaml

Per D2IQ-66863, Adding additional nonResourceURLs to the opsportal-kibana that will allow a user "view" type of permissions within Kibana addon.
Currently a user is not able:
- To use the Discover tab which is a requirement in our Product for viewing logs for Kubernetes, Konvoy and Kommander by default.
- Use the Timelion app which comes preinstalled in our Kibana. 
The following nonResourceURLs have been inspected to ensure that users with the ClusterRole are not able create/delete Indexes or use the Dev Tools tool to do anything that would be considered destructive in Elasticsearch.

Additional nonResourceURLS to opsportal-kibana-view ClusterRole

---

Makefile

Now that Dispatch is publishing helm repo, I noticed that the sort
order is different when I run builds locally due to different
LC_COLLATE. Setting this to LC_COLLATE=C to be consistent on all hosts
regardless of local environment ensures reproducible builds on all
hosts.

fix: Fix consistent sort ordering for publish

---

CODEOWNERS

- Removed `/stable/kommander-karma` and `/stable/kommander-thanos` because those charts 
were moved directly into kommander chart
- Add @mesosphere/sig-ksphere-observability to `/stable/kommander` chart
- Add @mesosphere/sig-ksphere-observability to `/stable/kubecost` chart

chore: Modify kommander codeowners, add kubecost codeowners

---

stable/kommander/Chart.yaml
stable/kommander/templates/grafana/dashboards/apiserver.yaml
stable/kommander/templates/grafana/dashboards/cluster-total.yaml
stable/kommander/templates/grafana/dashboards/controller-manager.yaml
stable/kommander/templates/grafana/dashboards/etcd.yaml
stable/kommander/templates/grafana/dashboards/k8s-coredns.yaml
stable/kommander/templates/grafana/dashboards/k8s-resources-cluster.yaml
stable/kommander/templates/grafana/dashboards/k8s-resources-namespace.yaml
stable/kommander/templates/grafana/dashboards/k8s-resources-node.yaml
stable/kommander/templates/grafana/dashboards/k8s-resources-pod.yaml
stable/kommander/templates/grafana/dashboards/k8s-resources-workload.yaml
stable/kommander/templates/grafana/dashboards/k8s-resources-workloads-namespace.yaml
stable/kommander/templates/grafana/dashboards/kubelet.yaml
stable/kommander/templates/grafana/dashboards/namespace-by-pod.yaml
stable/kommander/templates/grafana/dashboards/namespace-by-workload.yaml
stable/kommander/templates/grafana/dashboards/node-cluster-rsrc-use.yaml
stable/kommander/templates/grafana/dashboards/node-rsrc-use.yaml
stable/kommander/templates/grafana/dashboards/nodes.yaml
stable/kommander/templates/grafana/dashboards/pod-total.yaml
stable/kommander/templates/grafana/dashboards/pods.yaml
stable/kommander/templates/grafana/dashboards/prometheus-remote-write.yaml
stable/kommander/templates/grafana/dashboards/prometheus.yaml
stable/kommander/templates/grafana/dashboards/proxy.yaml
stable/kommander/templates/grafana/dashboards/scheduler.yaml
stable/kommander/templates/grafana/dashboards/statefulset.yaml
stable/kommander/templates/grafana/dashboards/workload-total.yaml

https://jira.d2iq.com/browse/D2IQ-65414
To match the language in the kommander ui wrt monitoring id exposed there used to correlate cluster to its metrics in the centralized grafana, made some changes to the grafana dashboards. Renamed the `cluster` filter display name to `Cluster (Monitoring ID/clusterId)` and also fixed some inconsistencies with capitalization of `Cluster`.
kommander ui:

kommander: Grafana updates to cluster label

---

stable/awsebscsiprovisioner/Chart.yaml
stable/awsebscsiprovisioner/files/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
stable/awsebscsiprovisioner/files/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
stable/awsebscsiprovisioner/files/snapshot.storage.k8s.io_volumesnapshots.yaml
stable/awsebscsiprovisioner/templates/_helpers.tpl
stable/awsebscsiprovisioner/templates/install-crds.yaml
stable/awsebscsiprovisioner/templates/statefulset-snapshot-controller.yaml
stable/awsebscsiprovisioner/templates/statefulset.yaml
stable/awsebscsiprovisioner/values.yaml

- fixing a wrong image usage for snapshot-controller
- logic for same image tag being used for snapshotter as
snapshot-controller
- updated images to compatible latest
- added replicas for SnapshotController
- only leader-election enabled if replicas > 1
- added CRD install for v1beta1
- added nodeSelector, priorityClassName and tolerations for
SnapshotController
Notes:
atm with this an "upgrade" would fail, and there would be the need to
manual remove the v1alpha1 snapshot CRDs. Which would also purge
snapshots. This must be documented.
Closes #578
[D2IQ-68177] #comment See GitHub
[D2IQ-68177]: https://jira.d2iq.com/browse/D2IQ-68177

feat(awsebscsiprovisioner): update images

---

stable/kubecost/Chart.yaml
stable/kubecost/templates/hooks-clusterid.yaml

Was seeing that there was something wonky going on with the service accounts when kubecost was getting deployed on managed clusters - occasionally the sa token secret couldn't be found which caused other required hook jobs to fail which depended on the sa/roles, which in turn caused kubecost deployment to fail. Removed `hook-succeeded` from the sa hook deletion policy and thus the post- hooks. This seemed to stop kubecost deployments from failing.
```
3m32s       Warning   Failed                   pod/kubecost-kubeaddons-cluster-i
d-configmap-tr88l             Error: cannot find volume "kubecost-kubeaddons-hoo
k-token-7mdbp" to mount into container "kubectl"
<unknown>   Normal    Scheduled                pod/kubecost-kubeaddons-cluster-i
d-configmap-wjrg2             Successfully assigned …
```

kubecost: Fix sa hook delete-policy

---

staging/traefik/Chart.yaml
staging/traefik/templates/configmap.yaml
staging/traefik/values.yaml

This change improves the charts by allowing extra SSL entrypoints being
defined, and inherit SSL configurations from global SSL config. We
observed that in some customer environment, they are using advanced
configurations for their ingress, including turning on proxy protocol on
the ingress.
Previously, we use `extraConfigEntrypoints` to add the additional velero
minio entrypoints for the velero addon. This basically means if they
have any customization on the ingress entrypoint, we'll have to ask them
to manually specifying those configs `extraConfigEntrypoints` again for
the velero-minio entrypoint, which creates a very bad user experience.
This patch improves this experiecne by introducing `extraSSLEntrypoints`
that will inherit global configurations so that the user does not have
to …

traefik: support extra SSL entrypoints [D2IQ-68705]

---

staging/kubeaddons-catalog/Chart.yaml
staging/kubeaddons-catalog/templates/deployment.yaml
staging/kubeaddons-catalog/values.yaml

Allow users to specify environment variables for the container (e.g.,
setting up proxy related environment variables).
Tested with this values file:
```yaml
env:
foo: bar
zoo: now
```
Result:
```yaml
env:
- name: "foo"
value: "bar"
- name: "zoo"
value: "now"
```

kubeaddons-catalog: add env support

---

stable/azuredisk-csi-driver/Chart.yaml
stable/azuredisk-csi-driver/files/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
stable/azuredisk-csi-driver/files/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
stable/azuredisk-csi-driver/files/snapshot.storage.k8s.io_volumesnapshots.yaml
stable/azuredisk-csi-driver/templates/_helper.tpl
stable/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
stable/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
stable/azuredisk-csi-driver/templates/install-crds.yaml
stable/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
stable/azuredisk-csi-driver/values.yaml

- logic for same image tag being used for snapshotter as
snapshot-controller
- updated images to compatible latest
- added replicas for SnapshotController
- only leader-election enabled if replicas > 1
- added CRD install for v1beta1
- added nodeSelector, priorityClassName and tolerations for
SnapshotController
Notes:
atm with this an "upgrade" would fail, and there would be the need to
manual remove the v1alpha1 snapshot CRDs. Which would also purge
snapshots. This must be documented.
changes as for #580
[D2IQ-68177] #comment See GitHub
[D2IQ-68177]: https://jira.d2iq.com/browse/D2IQ-68177

feat(azuredisk-csi-driver): update images

---

stable/gcpdisk-csi-driver/Chart.yaml
stable/gcpdisk-csi-driver/files/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
stable/gcpdisk-csi-driver/files/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
stable/gcpdisk-csi-driver/files/snapshot.storage.k8s.io_volumesnapshots.yaml
stable/gcpdisk-csi-driver/templates/_helper.tpl
stable/gcpdisk-csi-driver/templates/csi-gcpdisk-controller.yaml
stable/gcpdisk-csi-driver/templates/csi-gcpdisk-snapshot-controller.yaml
stable/gcpdisk-csi-driver/templates/install-crds.yaml
stable/gcpdisk-csi-driver/templates/rbac-csi-gcpdisk-controller.yaml
stable/gcpdisk-csi-driver/templates/rbac-csi-gcpdisk-snapshot-controller.yaml
stable/gcpdisk-csi-driver/templates/serviceaccount-csi-gcpdisk-snapshot-controller.yaml
stable/gcpdisk-csi-driver/values.yaml

- logic for same image tag being used for snapshotter as
snapshot-controller
- updated images to compatible latest
- added replicas for SnapshotController
- only leader-election enabled if replicas > 1
- added CRD install for v1beta1
- added tolerations
Notes:
atm with this an "upgrade" would fail, and there would be the need to
manual remove the v1alpha1 snapshot CRDs. Which would also purge
snapshots. This must be documented.
changes as for #580 #581
[D2IQ-68177] #comment See GitHub
[D2IQ-68177]: https://jira.d2iq.com/browse/D2IQ-68177

feat(gcpdisk-csi-driver): update images

---

stable/gcpdiskprovisioner/Chart.yaml
stable/gcpdiskprovisioner/templates/_helpers.tpl
stable/gcpdiskprovisioner/templates/snapshotclass.yaml
stable/gcpdiskprovisioner/values.yaml

- added detection for Kubernetes >= Minor 17
plays with to #584
[D2IQ-68177] #comment gcpdiskprovisioner chart changes done.
[D2IQ-68177]: https://jira.d2iq.com/browse/D2IQ-68177

feat(gcpdiskprovisoner): updated snapshotclass

---

stable/gcpdisk-csi-driver/Chart.yaml
stable/gcpdisk-csi-driver/templates/csi-gcpdisk-controller.yaml
stable/gcpdisk-csi-driver/templates/rbac-csi-gcpdisk-controller.yaml

- accidently we lost old snapshotter 
functionality
- set metrics address not for old snapshotter
version
- readded back needed permissions for old 
snapshotter version
```
STAGE [Deploying Enabled Addons]
gatekeeper                                                             [OK]
velero                                                                 [OK]
defaultstorageclass-protection                                         [OK]
kube-oidc-proxy                                                        [OK]
traefik-forward-auth                                                   [OK]
konvoyconfig                                                           [OK]
dashboard                                                              [OK]
prometheus …
```

fix: gcpdisk-csi-driver old snapshotter

---

stable/azuredisk-csi-driver/Chart.yaml
stable/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
stable/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml

- they changed to check only /dev insteaf of /devhost
(which was what the driver did before)
- added needed permissions csi-attacher
```
I0529 13:34:18.236308       1 utils.go:119] GRPC response: capabilities:<rpc:<type:STAGE_UNSTAGE_VOLUME > > capabilities:<rpc:<type:EXPAND_VOLUME > > capabilities:<rpc:<type:GET_VOLUME_STATS > >
I0529 13:34:18.241424       1 utils.go:112] GRPC call: /csi.v1.Node/NodePublishVolume
I0529 13:34:18.241489       1 utils.go:113] GRPC request: volume_id:"/subscriptions/b1ed8f2f-ceda-41d5-a0a8-95960b5340c2/resourceGroups/sbrandt-konvoy-93fa-rg/providers/Microsoft.Compute/disks/pvc-58b1803c-96cb-475a-8501-791832a002dc" publish_context:<key:"LUN" value:"1" > staging_target_path:"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-58b1803c-96cb-475a-8501-791832a002dc/ …
```

fix: azuredisk-csi-driver

---

Dispatchfile
stable/kommander/Chart.yaml
stable/kommander/values.yaml

https://jira.d2iq.com/browse/D2IQ-68887
We should override kommander kubecost component names to include "kubecost" in the name to make it clear which components are deployed as part of kubecost.
Tested by hosting the chart and deploying it.
```
$ k get deployments -nkommander | grep kommander-
kommander-kubeaddons-grafana                       1/1     1            1           69s
kommander-kubeaddons-karma                         0/1     1            0           69s
kommander-kubeaddons-kommander-ui                  0/1     1            0           69s
kommander-kubeaddons-kubeaddons-catalog            1/1     1            1           69s
kommander-kubeaddons-thanos-query                  0/1     1            0           69s
kommander-kubecost-cost-analyzer                   0/1     1 …
```

kommander: Override kubecost component names

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

https://jira.d2iq.com/browse/D2IQ-68100
Kubecost assumes its URL has a trailing slash. If served without a trailing slash, the web app doesn't work. This PR causes Traefik to redirect `/ops/portal/kommander/kubecost` to `/ops/portal/kommander/kubecost/` so that Kubecost's URL always has a trailing slash.
I tested this PR by deploying a Konvoy cluster with the kommander addon disabled, then installing a local copy of this branch's kommander chart with the chart values defined in the kommander addon. Then I browsed to `/ops/portal/kommander/kubecost`, saw that I was redirected to `/ops/portal/kommander/kubecost/`, and saw that the resulting Kubecost page listed this cluster and its projected cost.

[kommander] Rewrite Kubecost URL to include trailing slash

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

This is now set at the same value as for karma, `4`.
This resolves the bug https://jira.d2iq.com/browse/D2IQ-68570
which was making Grafana inacessible from the Kommander UI
after self-attaching a Konvoy cluster.
This change was tested manually by updating the ingress
kommander-kubeaddons-grafana on a running Konvoy
cluster after self-attachment.

kommander: update ingress priority for Grafana

---

staging/traefik/Chart.yaml
staging/traefik/templates/init-cert-job.yaml

Otherwise, Helm will try to patch the last job and K8s doesn't allow that for certain fields (e.g. the image field is immutable).
Upon an upgrade of the release comprised of this chart, the previous job will get removed. Thus, we won't be having old jobs hanging around on clusters.
This is how I tested this:
1. Spin up a Konvoy cluster with all Addons except cert-manager disabled
1. From the `staging/traefik` directory of the [mesosphere/charts](https://github.com/mesosphere/charts) repo, install the traefik chart:
```
helm install --name traefik-kubeaddons --namespace kubeaddons -f values-override.yaml .
```
The contents of the `values-override.yaml` file can be derived directly from the [traefik Addon](https://github.com/mesosphere/kubernetes-base-addons/tree/master/addons/traefik/1.7.x) …

fix: traefik job name must be unique for upgrades to succeed

---

stable/kommander/Chart.yaml
stable/kommander/templates/kubecost/kubecost-query-stores-configmap.yaml

Fixes https://jira.d2iq.com/browse/D2IQ-69505
Note: If the configmap already exists and has the `pre-upgrade` hook annotation, the annotation will remain, because the configmap will not be deleted/re-created during the upgrade. This seems correct, but also non-intuitive, and I'm still trying to understand it.

kommander: do not recreate the kubecost-query-stores configmap on upgrade

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

Bug
Allows /kubecost/query to be matched prior to the /kubecost/(.*) regex in
kommander-kubecost-cost-analyzer ingress.
Fixes https://jira.d2iq.com/browse/D2IQ-69510
```release-note
NONE
```
**Checklist**

fix: increase priority of kommander-kubecost-thanos ingress

---

stable/opsportal/Chart.yaml
stable/opsportal/templates/kibana-roles.yaml

Signed-off-by: Dimitri Koshkin <dimitri.koshkin@gmail.com>
Bug
Upgrade fails with below, installs worked:
```
2020-06-22T16:07:47.730Z	ERROR	kubeaddons-controller.Addon	could not upgrade addon	{"Addon": "opsportal", "namespace": "kubeaddons", "chart": "opsportal", "version": "0.3.18", "valuesCRC32": "6ba99a12", "error": "error running cli command `helm upgrade`. stdout: `UPGRADE FAILED\nError: failed to create patch: failed to create two-way merge patch: unable to find api field in struct ObjectMeta for the json field \"lables\" && failed to create patch: failed to create two-way merge patch: unable to find api field in struct ObjectMeta for the json field \"lables\" && failed to create patch: failed to create two-way …
```

opsportal: fix a typo that prevents upgrades

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-apps.yaml

Bug
We started seeing a lot of rule evaluation errors in SOAK:
```
level=warn ts=2020-06-23T16:59:50.051Z caller=manager.go:570 component="rule manager" group=kubernetes-apps msg="Evaluating rule failed" rule="alert: KubePodNotReady\nexpr: sum by(namespace, pod) (max by(namespace, pod) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=~\".*\",phase=~\"Pending|Unknown\"})\n  * on(namespace, pod) group_left(owner_kind) max by(namespace, pod, owner_kind) (kube_pod_owner{owner_kind!=\"Job\"}))\n  > 0\nfor: 15m\nlabels:\n  severity: critical\nannotations:\n  message: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state\n    for longer than 15 minutes.\n  runbook_url: …
```

prometheus-operator: Fix KubePodNotReady prometheus rule

---

staging/konvoyconfig/Chart.yaml
staging/konvoyconfig/templates/configmap.yaml
staging/konvoyconfig/values.yaml

Feature
This PR adds a new field to konvoyconfig addon to take a secret name which holds custom certificate CA bundle. This is needed by Kommander to populate appropriate CA bundle in the federated addons. In order to do that it needs to know the name of the secret that holds the CA bundle.
https://jira.d2iq.com/browse/COPS-6173
related to https://github.com/mesosphere/yakcl/pull/101
```release-note
konvoyconfig has a new field `caSecretName` to support custom certificate in managed cluster
```
**Checklist**

feat: adds caSecretName key to konvoyconfig

---

staging/istio/Chart.yaml
staging/istio/charts/prometheus-operator/templates/servicemonitors.yaml
staging/istio/charts/security/templates/istio-cacert-job.yaml

Bug
Adds the right `release` label on the service monitor
no issue
```release-note
```
**Checklist**

fix: update release label in service monitors

---

staging/traefik/Chart.yaml
staging/traefik/templates/service.yaml
staging/traefik/values.yaml

Signed-off-by: Dimitri Koshkin <dimitri.koshkin@gmail.com>
Bug
Revert the changes made in https://github.com/mesosphere/charts/pull/614#discussion_r446304599 which broke `velero` and metrics collection.
Tested locally with the patch
~https://ad3721e184e2349bbbc7c80f94b8568d-1341071842.us-west-2.elb.amazonaws.com:9000/minio/login is working again~ my cluster timed out, here is a screenshot I had open.
Before the fix:
```
➜  dkkonvoyrc1 k get svc -n kubeaddons     traefik-kubeaddons
NAME                 TYPE           CLUSTER-IP   EXTERNAL-IP                                                               PORT(S)                      AGE
traefik-kubeaddons   LoadBalancer   10.0.56.24 …
```

traefik: revert change to include extraServicePorts for velero and metrics

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/grafana/dashboards-1.14/apiserver.yaml
staging/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver.rules.yaml
staging/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml

Bug
Revert the apiserver rules change from 30d to 7d intervals. The evaluation duration did not decrease significantly and was still triggering `PrometheusRuleFailures` alerts. Instead, separate out the "availability" rules which are taking a long time to evaluate into its own group and set the evaluation interval to 3m (up from default of 30s). So - these rules are evaluated every 3min now instead of every 30s. Previously, the rules were taking longer than 30s to get evaluated so they were triggering the alert.
https://jira.d2iq.com/browse/D2IQ-69672
```release-note
```
**Checklist**

prometheus-operator: Move apiserver availability rules to new group with 3m interval

---

.gitignore
Makefile
staging/traefik/Chart.yaml
staging/traefik/ci/test-values.yaml
staging/traefik/templates/configmap.yaml
staging/traefik/templates/tests/test-certificate.yaml
staging/traefik/templates/tests/test-configmap.yaml
staging/traefik/templates/tests/test-customCertificate.yaml
staging/traefik/templates/tests/test-reloadTrigger.yaml
staging/traefik/templates/tests/test.yaml
test/ct-e2e.yaml
test/e2e-kind.sh

Bug
- defaultCertificate back for traefik
- added tests to prove it works
- slightly needed to modifiy e2e to make it possible
- tiller has a bug in 2.16.5 of a SIGSEGV, so we need to make sure to update and are using now 2.16.9 in ct container
- hint: kind 0.8.1 atm not working as of a resolv.conf issue with 
127.0.0.1, so atm we stay with 0.7.0
[D2IQ-69838]
[D2IQ-62818]
[D2IQ-69838]: https://jira.d2iq.com/browse/D2IQ-69838
[D2IQ-62818]: https://jira.d2iq.com/browse/D2IQ-62818
```release-note
NONE
```
**Checklist**

fix: bring back defaultCertificate for traefik

---

staging/istio/Chart.yaml
staging/istio/charts/security/templates/cert-delete-job.yaml
staging/istio/charts/security/templates/istio-cacert-job.yaml
staging/istio/templates/install-crd-job.yaml
staging/istio/values.yaml

Bug
It adds a certificate deletion job so that future installation doesn't error out
https://jira.d2iq.com/browse/D2IQ-69875
Verified by running manual test
```
1. helm install ./git/staging/istio --namespace istio-system -n istio-kubeaddons
2. helm delete --purge istio-kubeaddons
3. Verified that certificate is not left behind
```
```release-note
```
**Checklist**

fix: removes a left behind certificate upon istio addon deletion

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

The image of catalog was forced by the values file of kommander, this should never have been the case and we should avoid this. Removing the value explicitly should not break previous or future versions as this value still exists in the catalog's value file
Bug
This PR resolves the issue of updating the catalog chart but image of catalog remaining the same. This should not happen at this level.
https://jira.d2iq.com/browse/D2IQ-69905
```release-note
```
**Checklist**

[kommander] fix: kommander should not force a value of catalog image

---

staging/traefik/Chart.yaml
staging/traefik/README.md
staging/traefik/templates/prometheus-service.yaml
staging/traefik/values.yaml

Chore
Add option to define labels for the prometheus service. The prometheus addon targets this service via label selectors, so we'll need to define that label.
no issue
```release-note
Add option in traefik config to define labels for the prometheus service.
```
**Checklist**

traefik: Add prometheus service labels option

---

staging/traefik/Chart.yaml
staging/traefik/templates/prometheus-service.yaml

Bug
We were seeing `Error: YAML parse error on traefik/templates/prometheus-service.yaml: error converting YAML to JSON: yaml: line 9: did not find expected key\n` which led to the yaml indentation bug in the template 😢  I think the other fix would be to unindent `{{ toYaml .Values.metrics.prometheus.service.labels | indent 4 }}` but to keep the indentation consistent in the file, chose to go with the current fix instead.
https://jira.d2iq.com/browse/D2IQ-70138
Tested on new cluster using testing kba branch `gracedo/test_traefik` - verified that targets are coming up in service monitor and traefik dashboards are populating
**Does this PR introduce a …

traefik: Fix yaml indentation bug

---

staging/cert-manager-setup/Chart.yaml
staging/cert-manager-setup/templates/certificates.yaml

Bug
The certificates are not created with the right namespace, because the certificate template does not define a namespace. Where helm v2 used the release namespace (correct), helm v3 uses the kubeaddons-controller namespace (incorrect).
https://jira.d2iq.com/browse/D2IQ-70273
```release-note
NONE
```
**Checklist**

fix[cert-manager-setup]: deploy Certificate CRs in the release namespace

---

staging/velero/Chart.yaml
staging/velero/crds/crds.yaml
staging/velero/templates/backupstoragelocation.yaml
staging/velero/templates/schedule.yaml
staging/velero/templates/volumesnapshotlocation.yaml

BUG
https://jira.d2iq.com/browse/D2IQ-70289
```release-note
NONE
```
**Checklist**

[velero] fix: allow velero to deploy on helm2&3 without needing install hooks

---

Makefile

BUG
CT Testing should be consistent with helm version, here we fix that by setting the correct version for helm2
This is an important followup to https://github.com/mesosphere/charts/pull/729
```release-note
NONE
```
**Checklist**

[test] set ct version for helm2 correctly

---

Makefile

BUG
Helm2 is currently used for publishing, we will force this to be the case for now. 
```release-note
NONE
```
**Checklist**

[BUG] force `make publish` use helm2

---

Dispatchfile
test/ct.yaml

Lint is broken because we need to have the ct file in a particular location, reverting back to 3.0.0 but using the right ct file.
```release-note
NONE
```
**Checklist**

fix: lint requires ct.yaml to be in test dir

---

Makefile

Chore
Only adds new files when publishing the helm repo with checks for updated files before trying to publish.
```release-note
NONE
```
**Checklist**

chore: Only add new files on publish of helm repo

---

staging/kubeaddons-catalog/Chart.yaml
staging/kubeaddons-catalog/values.yaml

Chore
This bumps the image used in the kubeaddons-catalog to v0.10.0, a version of kubeaddons-catalog which uses kubeaddons as a a backend. This will be followed by a PR updating the kommander chart.
https://jira.d2iq.com/browse/D2IQ-70803
```release-note
NONE
```
**Checklist**

chore: bump kubeaddons-catalog image to v0.10.0

---

Makefile

chore
Use helm 3.3.0 for the make publish target
https://jira.d2iq.com/browse/D2IQ-71191
tested this up-to the push. All tarballs will be recreated to change the chart file permissions from 744 to 644. This is expected behavior.
```release-note
NONE
```
**Checklist**

Use 3.3.0 for publish

---

test/e2e-kind.sh

CHORE
Default timeout is 30s to wait for deployment of dummylb, this will try to mitigate the failing of deploying dummlb by giving us more time 
https://jira.d2iq.com/browse/D2IQ-71273
```release-note
NONE
```
**Checklist**

chore: Change dummylb timeout to 3mins

---

staging/knative/Chart.yaml
staging/knative/charts/serving/Chart.yaml
staging/knative/charts/serving/templates/serving.yaml
staging/knative/charts/serving/values.yaml
staging/knative/requirements.yaml
staging/knative/values.yaml

Feature
KNative Serving resolves image tags to their digests when service deployment is created. This doesn't work for air-gapped installations and we need an option to exclude registries for which it doesn't work.
[D2IQ-71478: pods launched by kfserving use image SHA instead of tags](https://jira.d2iq.com/browse/D2IQ-71478)
N/A
NONE
**Checklist**

Exposing 'registriesSkippingTagResolving' parameter for KNative Serving

---

staging/cert-manager-setup/Chart.yaml
staging/cert-manager-setup/templates/install-crds.yaml
staging/cert-manager-setup/templates/post-install-hook-job.yaml
staging/flagger/Chart.yaml
staging/flagger/templates/job.yaml
staging/traefik/Chart.yaml
staging/traefik/templates/tests/test-certificate.yaml
staging/traefik/templates/tests/test-customCertificate.yaml

Bug
Generally, we should NOT use `latest` tag due to multiple reason. But today, the `latest` tag is breaking the Konvoy airgapped bundle generation due to the lack of repository tags when pulling it. Latest tag is 1.18.8 but 1.18.4 doesn't have that problem and should work as well.
```release-note
none
```
**Checklist**

fix: usage of kubectl:latest

---

staging/nvidia/Chart.yaml
staging/nvidia/charts/nvidia-driver/Chart.yaml
staging/nvidia/charts/nvidia-driver/templates/configmap.yaml
staging/nvidia/requirements.yaml

Bug
Konvoy 1.5 uses Centos 7.7 AMI be default. The kernel headers for the version used by Centos 7.7 AMI is not in standard Centos repos. This leads to nvidia driver container to fail on default install unless tagged with appropriate tag. I think we need this since this reduces friction for a default install.  
https://jira.d2iq.com/browse/COPS-6483
@Gilbert88 @joejulian 
If this is merged I can send a PR for addons repo to use this version of chart.  
Yes
```release-note
No need to specify nvidia-driver tag when using th default AMI for GPU nodes.
```
**Checklist**

fix:[nvidia] Add Centos 7.7 Vault Repo for Konvoy 1.5 support

---

stable/kubecost/Chart.yaml
stable/kubecost/values.yaml

Bug
Latest version of kubecost added a new prom recordingrule to values file. I originally included the block in our parent values, so this overwrote the block in the updated kubecost base values, excluding the new rule. Instead here I remove our block altogether since we don't need to customize on top of the base chart.
Excluding the extra rule had resulted in error messages in the kubecost UI:
no issue
Verified that new rule is included in the configmap
```
rules: |
groups:
- name: CPU
rules:
- expr: sum(rate(container_cpu_usage_seconds_total{container_name!=""}[5m]))
record: cluster:cpu_usage:rate5m
- expr: …
```

kubecost: Include new savings rule

---

Dispatchfile

When the kommander chart gets updated, a PR will automatically be created on mesosphere/kubeaddons-kommander. The same logic will easily be applied to kubernetes-base-addons and kubeaddons-enterprise. I will add those in a future PR.
Proof it works: https://github.com/mesosphere/kubeaddons-kommander/pull/160
https://jira.d2iq.com/browse/D2IQ-70923
**Checklist**

Dispatchfile: track kommander bumps

---

Dispatchfile

Any chart that gets updated and has a matching addon in kubernetes-base-addons will automatically generate a pull request to update the addon.
**Checklist**

Dispatchfile: add task to bump any addon to kba

---

staging/cert-manager-setup/Chart.yaml
staging/cert-manager-setup/README.md
staging/cert-manager-setup/ci/test-values.yaml
staging/cert-manager-setup/values.yaml

Bug (CI)
`clusterissuer` value is deprecated, but the test-values.yaml is still using it instead of `clusterissuers`, which is causing downstream chart tests dependent on this clusterissuer to fail (e.g. traefik).
no issue
```release-note
NONE
```
**Checklist**

cert-manager: Use clusterissuers instead of deprecated clusterissuer

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

Chore
At some point the thanos loglevel was set to `error` but this has made debugging really difficult, as the log file is completely empty. I would like to reset the level back to the default value, which is `info`, and moving forward we should configure this value in the kubeaddons-kommander config layer instead.
no issue
```release-note
NONE
```
**Checklist**

kommander: Reset kubecost thanos loglevel to default (info)

---

staging/istio/Chart.yaml

Bug
We mistakenly added a `helm` binary into the chart and started seeing `create: failed to create: Request entity too large: limit is 3145728` errors when installing the chart. This PR fixes the issue by removing it.
no issue
```release-note
NONE
```
**Checklist**

istio: Remove helm binary

---

staging/kubeaddons-catalog/Chart.yaml
staging/kubeaddons-catalog/values.yaml

Chore
bump kubeaddons-catalog chart to latest release
https://jira.d2iq.com/browse/D2IQ-72080
```release-note
fixed bug with catalog items not showing up
```
**Checklist**

chore: bump kubeaddons-catalog chart to latest release

---

stable/external-dns/Chart.yaml
stable/external-dns/templates/service.yaml
stable/external-dns/values-production.yaml
stable/external-dns/values.yaml

Feature/chore
Add option to define service labels, mainly so we can use a label to get its metrics discovered and scraped by prom. This func was already added to a later version in the upstream chart (https://github.com/bitnami/charts/commit/41d917aba5946d290580c96afb295b9b9207dc59#diff-b37fd4e4217d56abe479147564c4c1afc64d680c8c0612701f6e14ba7e3a8ef7) but we should not jump a major version so close to the release date in case something breaks. So, since we already have this fork, I've ported over this func here and will point us to this fork in KBA.
https://jira.d2iq.com/browse/D2IQ-72698 …

external-dns: Add service.labels option

---

stable/defaultstorageclass/Chart.yaml
stable/defaultstorageclass/templates/service.yaml

Bug
Annotation-based service discovery has been deprecated in prometheus-operator so these metrics were no longer getting collected. Switch to use the service monitor model by adding this label to allow it to get scraped by Prometheus. This requires a change to the Prometheus addon config to add this metrics endpoint (will put up kba pr for this later after including all other necessary prom config changes to get metrics collected from other components):
```diff
--- a/addons/prometheus/prometheus.yaml
+++ b/addons/prometheus/prometheus.yaml
@@ -100,6 +100,24 @@ spec:
- targetPort: 10902
interval: 30s
+          - name: kubeaddons-service-monitor-metrics-defaultstorageclass
+            selector:
+ …
```

defaultstorageclass: Enable metrics collection

---

stable/metallb/Chart.yaml
stable/metallb/templates/service.yaml
stable/metallb/values.yaml

Feature
Add option to set service labels for prom scraping. The only KBA change requires setting the label `servicemonitor.kubeaddons.mesosphere.io/path: "metrics"` and metallb metrics will automatically get scraped using an existing servicemonitor.
https://jira.d2iq.com/browse/D2IQ-72697
```release-note
feat: Add option to set service labels
```
**Checklist**

chore: Add config to set svc labels for metric collection

---

staging/flagger/Chart.yaml
staging/flagger/charts/flagger-loadtester/Chart.yaml
staging/flagger/charts/flagger-loadtester/README.md
staging/flagger/charts/flagger-loadtester/templates/service.yaml
staging/flagger/charts/flagger-loadtester/values.yaml
staging/flagger/templates/crd.yaml
staging/flagger/templates/rbac.yaml

Chore
This adds a chart value that can be used to apply labels to the service created by the flagger-loadtester chart. This is done to enable applying labels that allow Prometheus to discover flagger-loadtester's metrics endpoint.
https://jira.d2iq.com/browse/D2IQ-72693
```release-note
flagger-loadtester: Adds chart value `service.labels`.
```
**Checklist**

flagger-loadtester: Add chart value service.labels

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/mesosphere-hooks/prometheus-cluster-id-hooks.yaml
staging/prometheus-operator/templates/prometheus/rules/mesosphere-rules/etcd-rules.yaml
staging/prometheus-operator/templates/prometheus/rules/mesosphere-rules/velero-rules.yaml

bug
Cleanup job fails if configmap doesn't exist. Don't fail, we didn't want it to exist anyway.
https://jira.d2iq.com/browse/D2IQ-72743
```release-note
none
```
**Checklist**

Fix for cleanup job failure when configmap not present

---

staging/flagger/Chart.yaml
staging/flagger/templates/crd.yaml

Chore
This reverts a change from #860 that breaks installation of this chart. See https://jira.d2iq.com/browse/D2IQ-72803 for more information on why this PR is necessary.
https://jira.d2iq.com/browse/D2IQ-72694
Lint is failing because it's complaining about the deprecated resource version:
```
[ERROR] templates/crd.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiextensions.k8s.io/v1 CustomResourceDefinition"
```
```release-note
flagger: Fix chart install
```
**Checklist**

flagger: Revert CRD version upgrade

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

Bug
This simplifies the ingress by removing path rewrites that are no longer
necessary due to a fix in the cost analyzer. It also fixes a possible
authz error that may be encountered if a user with a role that includes
any restrictions on authorized URLs tries to browse to the cost
analyzer UI.
https://jira.d2iq.com/browse/D2IQ-71985
I tested this by browsing to `/ops/portal/kommander/kubecost/frontend` (no trailing slash) and observing that I was redirected to `/ops/portal/kommander/kubecost/frontend/` (with trailing slash) and that the UI loaded with no errors. Here's a screenshot from Chrome's dev tools to demonstrate:
**Does this PR introduce a …

kommander: Fix cost analyzer ingress path

---

stable/kommander/Chart.yaml
stable/kommander/templates/hooks-roles.yaml

bug
When trying to delete kommander, it failed with:
```
Error creating: pods "cleanup-kommander-kubeaddons-ops-portal-username-" is forbidden: error looking up service account kommander/kommander-kubeaddons: serviceaccount "kommander-kubeaddons" not found
```
This was because the install failed (for k8s envioronmental reasons)
which left the helm release in an error state and the service account
not installed.
By adding this hook to the delete phase, this will prevent the cleanup
job from not having its service account.
A friend told my wife she drew her eyebrows too high. She seemed surprised. …

create the serviceaccount needed for deletion jobs on delete

---

stable/vsphere-csi-driver/Chart.yaml
stable/vsphere-csi-driver/templates/storageclass.yaml
stable/vsphere-csi-driver/values.yaml

Chore
- Added `storageclass.parameters` to values. Needed e.g. for vSphere storagepolicy usage, where a customer would define a storage policy like `bronze-nfs` on vSphere and must tell the storageclass to use it. The only situation where it is not needed is in a default vSAN setup, which may not all customers have.
- raised appVersion to get bugfix for vSphere 6.7U3
(https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.0.1)
[D2IQ-71493]
[D2IQ-71493]: https://jira.d2iq.com/browse/D2IQ-71493
https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-89091D59-D844-46B2-94C2-35A3961D23E7.html
**Does this PR …

chore(vsphere-csi-driver): storageclass addition + driver version update

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

Closes  D2IQ-72789
Refactoring (if you think about the addon and chart as a union)
This enables us to install the chart directly without the addon indirection and therefore we can test the chart as the product
D2IQ-72789
I'm a bit unsure if the ingress part needs to be nested under global 🤔 Currently I just merged it all on the respective level 
```release-note
```
**Checklist**

D2IQ-72789: move kubeaddons-kommander values into kommander chart

---

staging/flagger/Chart.yaml
staging/flagger/README.md
staging/flagger/templates/deployment.yaml
staging/flagger/values.yaml

feature
This adds a chart value for setting labels on Flagger pods. This is necessary in order to allow Prometheus to scrape Flagger metrics by defining a `PodMonitor` that can discover Flagger pods by their labels.
https://jira.d2iq.com/browse/D2IQ-72693
I tested this chart by deploying it to a cluster with `podLabels` set and observing that the Flagger pods had those labels.
```release-note
[flagger] Adds chart value `podLabels`.
```
**Checklist**

flagger: Add podLabels value

---

stable/kommander/Chart.yaml
stable/kommander/values.yaml

Bug
new config block was added to the wrong location and caused the below grafana block to be put in the wrong location (bug intro'd in previous version https://github.com/mesosphere/charts/pull/904/files#diff-27ff036ff511571cd28603ccf34d46b315397788280fb0b35d6aaae9c451080eR253). this ended up with another grafana instance installation attempt which caused issues
```release-note
```
**Checklist**

kommander: Fix wrong config block location

---

stable/vsphere-csi-driver/Chart.yaml
stable/vsphere-csi-driver/templates/controller.yaml
stable/vsphere-csi-driver/templates/storageclass.yaml
stable/vsphere-csi-driver/values.yaml

Chore
- updated repositories to point to k8s.gcr.io instead of quay.io
- updated image versions
- set the extend / expanse volume to false as default
it is only available from vSphere 7 on, and we support initial v6.7U3
[D2IQ-71493]
[D2IQ-71493]: https://jira.d2iq.com/browse/D2IQ-71493
```release-note
NONE
```
**Checklist**

chore(vsphere-csi-driver): repository and image updates

---

stable/kommander/Chart.yaml
stable/kommander/charts/kommander-karma/Chart.yaml
stable/kommander/charts/kommander-karma/templates/_helpers.tpl
stable/kommander/charts/kommander-karma/templates/cleanup-configmap.yaml
stable/kommander/charts/kommander-karma/templates/hooks-roles.yaml
stable/kommander/charts/kommander-karma/values.yaml
stable/kommander/charts/kommander-thanos/Chart.yaml
stable/kommander/charts/kommander-thanos/templates/_helpers.tpl
stable/kommander/charts/kommander-thanos/templates/hooks-roles.yaml
stable/kommander/charts/kommander-thanos/templates/query-stores-configmap.yaml
stable/kommander/charts/kommander-thanos/values.yaml
stable/kommander/templates/_helpers.tpl
stable/kommander/templates/grafana/opsportal-username-secret.yaml
stable/kommander/templates/hooks-kubeaddons.yaml
stable/kommander/templates/hooks-kubecost.yaml
stable/kommander/templates/hooks-roles.yaml
stable/kommander/templates/kubecost/kubecost-query-stores-configmap.yaml
stable/kommander/values.yaml

Chore
Create SAs/roles per chart instead of reusing SA's created in parent charts (new SA/roles per subchart, create new SA for kommander chart instead of using the same one also defined in kommander-ui). This also allows us to finally get rid of the hardcoded SA names we were passing into the subcharts.
no issue
I tested this by hosting it on my GH - config branch `gracedo/kommander_0132`. Tested upgrade from prev version + fresh install on kommander cluster
```release-note
```
**Checklist**

kommander: Clean up SAs/roles

---

stable/awsebscsiprovisioner/Chart.yaml
stable/awsebscsiprovisioner/values.yaml

Feat
- updated aws-ebs-csi-driver
- new location for aws-ebs-csi-driver
- same version of csi-provisioner for K8sUpMinor17, as latest seems to 
have problems
no issue
✅ Approved that it works on the broken daily cluster. ✅
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/b013566a153b022bf06aff788a5ade455227bfca/CHANGELOG-0.x.md#v080
```release-note
- aws-ebs-csi-driver v0.8.0
```
**Checklist**

feat(awsebscsiprovisioner): update aws-ebs-csi-driver

---

stable/vsphere-csi-driver/Chart.yaml
stable/vsphere-csi-driver/templates/_helper.tpl
stable/vsphere-csi-driver/templates/controller.yaml
stable/vsphere-csi-driver/values.yaml

Chore
- updated image versions
- downgraded csi-provisioner, as we seem to have the same issue with 
latest version as we had with AWS
[D2IQ-71493]
[D2IQ-71493]: https://jira.d2iq.com/browse/D2IQ-71493
```release-note
NONE
```
**Checklist**

chore(vsphere-csi-driver): image updates

---

staging/istio/Chart.yaml
staging/istio/templates/deployment.yaml
staging/istio/templates/serviceaccount.yaml
staging/istio/values.yaml

Chore 
Bump istio from 1.8.1 to 1.8.2
https://github.com/istio/istio/issues/29566
This PR brings a fix for the issue that blocks Kaptain from running on istio-1.8.1
```release-note
```
**Checklist**

chore: upgrade istio from 1.8.1 to 1.8.2

---

stable/kommander/Chart.yaml
stable/kommander/charts/kommander-karma/templates/cleanup-configmap.yaml
stable/kommander/charts/kommander-thanos/templates/query-stores-configmap.yaml
stable/kommander/templates/grafana/opsportal-username-secret.yaml
stable/kommander/templates/kubecost/kubecost-query-stores-configmap.yaml
stable/kommander/templates/pre-deletion-purger.yaml
stable/kubecost/Chart.yaml
stable/kubecost/README.md
stable/kubecost/values.yaml
staging/gatekeeper/Chart.yaml
staging/gatekeeper/templates/install-crds.yaml
staging/kubeaddons-catalog/Chart.yaml
staging/kubeaddons-catalog/templates/crds.yaml
staging/local-path-provisioner/Chart.yaml
staging/local-path-provisioner/templates/post-install-job.yaml
staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/patch/mesosphere/templates/hooks/v9-to-v11-upgrade-part1.yaml
staging/prometheus-operator/patch/mesosphere/templates/hooks/v9-to-v11-upgrade-part2.yaml
staging/prometheus-operator/patch/patch_6_mesosphere_values.sh
staging/prometheus-operator/templates/mesosphere-hooks/v9-to-v11-upgrade-part1.yaml
staging/prometheus-operator/templates/mesosphere-hooks/v9-to-v11-upgrade-part2.yaml
staging/prometheus-operator/values.yaml
staging/velero/Chart.yaml
staging/velero/templates/install-crds.yaml

Fix
In related to CVE-2017-14062, used in bitnami/kubectl@1.16 is normally used in one-liners to talk to the API. I am not sure how critical is the usage of libidn2 for those one-run calls. 
```
Integer overflow in the decode_digit function in puny_decode.c in Libidn2 before 2.0.4 allows remote attackers to cause a denial of service or possibly have unspecified other impact.
```
```release-note
```
**Checklist**

CVE-2017-14062: bump bitname/kubectl 1.16 images

---

stable/defaultstorageclass/Chart.yaml
stable/defaultstorageclass/templates/deployment.yaml
stable/defaultstorageclass/templates/service.yaml

Signed-off-by: Dimitri Koshkin <dimitri.koshkin@gmail.com>
Bug
[Recent gatekeeper PR](https://github.com/mesosphere/charts/pull/956) made this chart flaky.
See [JIRA](https://jira.d2iq.com/browse/D2IQ-73956) for the issue details.
Because the selectors are changing, the KBA addon resource will now need to use a `delete` strategy. (PR to follow)
https://jira.d2iq.com/browse/D2IQ-73956
```release-note
defaultstorageclass: use unique Service selectors to avoid selecting unwanted endpoints from other charts.
```
**Checklist**

defaultstorageclass: use better selectors

---

stable/kommander/Chart.yaml
stable/kommander/templates/grafana/cronjob-home-dashboard.yaml

Signed-off-by: Dimitri Koshkin <dimitri.koshkin@gmail.com>
Bug
Similar change as https://github.com/mesosphere/charts/pull/964/files
```
k logs -n kommander      kommander-kubeaddons-set-grafana-home-dashboard-trigger-7gs2h
sh: /bin/bash: not found
```
```release-note
Kommander: fix set-grafana-home-dashboard after it was updated to a new jq image.
```
**Checklist**

chore: use /bin/sh in kommander-set-grafana job

---

stable/kubecost/Chart.yaml
stable/kubecost/values.yaml

bug
Patch kubecost 0.5.x chart to use older functioning kubecost release + add cve fix on top (https://github.com/mesosphere/charts/commit/6e3d7be63b4dc41c094cda249d741cb256c542f1#diff-478557e8a9ca4fd77b8f3ac5c7e109a7670090e32c03464ec2804a0b54abe1b3)
When this is merged to the release branch `release/kubecost-0.5.x` I will run the publish job to get this patched chart published, then update kommander chart and yakcl to downgrade kubecost to this version instead.
https://jira.d2iq.com/browse/D2IQ-74109
```release-note
```
**Checklist**

[release/kubecost-0.5.x] kubecost: Bump grafana sidecar image

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/patch/mesosphere/templates/hooks/prometheus-cluster-id-hooks.yaml
staging/prometheus-operator/templates/mesosphere-hooks/prometheus-cluster-id-hooks.yaml

bug (COPS)
A prometheus pre-delete SA hook was missing, which was required for the pre-delete jobs, causing addon deletion/cleanup to fail. Will open another PR to backport this fix to 9.3.x
https://jira.d2iq.com/browse/D2IQ-74181
https://jira.d2iq.com/browse/COPS-6807
```release-note
fix(prometheus): Adds a missing service account which caused addon deletion/cleanup to fail
```
**Checklist**

prometheus: Add missing pre-delete hook to SA

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/patch/mesosphere/templates/hooks/prometheus-cluster-id-hooks.yaml
staging/prometheus-operator/templates/mesosphere-hooks/prometheus-cluster-id-hooks.yaml

bug (backport)
Backports #993 to pull into Konvoy 1.6 (and 1.5?) patch release. My concern is that we have already applied a patch to 9.3.x here: https://github.com/mesosphere/charts/pull/970 which was done for konvoy 1.7 to mitigate some CVEs; this patch was pulled into yakcl federated prometheus to avoid upgrading the federatedaddon. So these extra CVE mitigations would be pulled into a konvoy 1.6/1.5 patch.
```release-note
```
**Checklist**

[release/prometheus-operator-9.3.x] Add missing pre-delete hook to SA

---

stable/kubecost/Chart.yaml
stable/kubecost/templates/hooks-clusterid.yaml

bug
Prevent chart from failing uninstall in case the cm has already been deleted (has occurred with kommander which pulls this chart in as subchart, and oftentimes undergoes multiple uninstall attempts)
https://jira.d2iq.com/browse/COPS-6821
https://jira.d2iq.com/browse/D2IQ-74255
```release-note
fix(kubecost): Ensure kubectl deletes do not fail if resource already deleted
```
**Checklist**

kubecost: Use --ignore-not-found in kubectl delete

---

stable/kubecost/Chart.yaml
stable/kubecost/templates/hooks-clusterid.yaml

bug
Prevent chart from failing uninstall in case the cm has already been deleted (has occurred with kommander which pulls this chart in as subchart, and oftentimes undergoes multiple uninstall attempts). This is a backport of https://github.com/mesosphere/charts/pull/1000 for komm1.3/konv1.7
https://jira.d2iq.com/browse/COPS-6821
https://jira.d2iq.com/browse/D2IQ-74255
```release-note
fix(kubecost): Ensure kubectl deletes do not fail if resource already deleted
```
**Checklist**

[release/kubecost-0.5.x] fix: Use --ignore-not-found in kubectl delete

---

stable/kubecost/Chart.yaml
stable/kubecost/templates/hooks-clusterid.yaml

bug
Prevent chart from failing uninstall in case the cm has already been deleted (has occurred with kommander which pulls this chart in as subchart, and oftentimes undergoes multiple uninstall attempts). This is a backport of https://github.com/mesosphere/charts/pull/1000 for komm1.1/konv1.5
https://jira.d2iq.com/browse/COPS-6821
https://jira.d2iq.com/browse/D2IQ-74255
```release-note
fix(kubecost): Ensure kubectl deletes do not fail if resource already deleted
```
**Checklist**

[release/kubecost-0.1.x] fix: Use --ignore-not-found in kubectl delete

---

stable/kommander/Chart.yaml
stable/kommander/README.md

chore
Following kommander 1.3.0 GA, we should bump the chart's minor version for v1.16.0. patches for v1.3 should patch this chart's 0.15.x versions. Also, wrote up some chart patching instructions in the readme, please review
https://jira.d2iq.com/browse/D2IQ-70979
```release-note
```
**Checklist**

kommander: Bump kommander to 0.16.0 following v1.3.0 release

---

staging/gatekeeper/Chart.yaml
staging/gatekeeper/patch/templates/gatekeeper-proxy-mutations.yaml
staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml

Chore
Wildcard scope does not seem to work consistently, and doesnt seem to be handled in code.
This was tested with velero and other static pods, the scope and exclusion now work consistently.
```release-note
None
```
**Checklist**

[gatekeeper] chore: change scope of proxy items as wildcard does not work consistently

---

staging/gatekeeper/Chart.yaml
staging/gatekeeper/patch/templates/gatekeeper-proxy-mutations.yaml
staging/gatekeeper/templates/gatekeeper-audit-deployment.yaml
staging/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml
staging/gatekeeper/values.yaml

Chore
We are moving to set mutations only having the ability to set proxy settings, remove these from gatekeeper itself.
```release-note
None
```
**Checklist**

chore: fix gatekeeper so only proxy settings are for mutations

---

staging/kubefed/Chart.yaml
staging/kubefed/README.md
staging/kubefed/charts/controllermanager/Chart.yaml
staging/kubefed/charts/controllermanager/crds/crds.yaml
staging/kubefed/charts/controllermanager/templates/_helpers.tpl
staging/kubefed/charts/controllermanager/templates/aggregate_clusterroles.yaml
staging/kubefed/charts/controllermanager/templates/clusterrole.yaml
staging/kubefed/charts/controllermanager/templates/clusterrolebindings.yaml
staging/kubefed/charts/controllermanager/templates/deployments.yaml
staging/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
staging/kubefed/charts/controllermanager/templates/rolebindings.yaml
staging/kubefed/charts/controllermanager/templates/roles.yaml
staging/kubefed/charts/controllermanager/templates/service.yaml
staging/kubefed/charts/controllermanager/templates/serviceaccounts.yaml
staging/kubefed/charts/controllermanager/templates/webhook.yaml
staging/kubefed/crds/crds.yaml
staging/kubefed/templates/_helpers.tpl
staging/kubefed/templates/federatedtypeconfig.yaml
staging/kubefed/values.yaml
test/ct.yaml
test/helm2/ct-e2e.yaml
test/helm2/ct.yaml
test/helm3/ct-e2e.yaml
test/helm3/ct.yaml

Signed-off-by: Hector Fernandez <hectorj@gmail.com>
Chore
While we are waiting to get https://github.com/kubernetes-sigs/kubefed/pull/1377 merged, we need to workaround that delay by getting our internal kubefed version based on v0.5.1.
```release-note
```
**Checklist**

chore: add kubefed fork

---

stable/kommander/Chart.yaml
stable/kommander/charts/kommander-karma/Chart.yaml
stable/kommander/charts/kommander-karma/values.yaml
stable/kommander/requirements.lock
stable/kommander/requirements.yaml

Feature
Adds support for tunneled clusters to karma. The karma must be deployed with a custom version from https://github.com/mesosphere/karma/tree/v0.55-d2iq-proxy
https://jira.d2iq.com/browse/D2IQ-74658
```release-note
Support tunneled clusters in karma configuration
```
**Checklist**

[kommander] feat: use custom built karma version with proxy support

---

staging/istio/Chart.yaml
staging/istio/charts/grafana/dashboards/istio-extension-dashboard.json
staging/istio/charts/grafana/dashboards/istio-mesh-dashboard.json
staging/istio/charts/grafana/dashboards/istio-service-dashboard.json
staging/istio/charts/grafana/dashboards/istio-workload-dashboard.json
staging/istio/charts/grafana/dashboards/pilot-dashboard.json
staging/istio/templates/clusterrole.yaml
staging/istio/values.yaml

Chore
Bumps istio to the latest version
no issue
Manually did the upgrade testing by spinning up a konvoy 1.7.1 cluster with istio enabled and then used this chart to upgrade istio to 1.9.1. Verified that the applications that were running prior to upgrade continued to run after upgrade as well.
```release-note
istio version upgraded to 1.9.1
```
**Checklist**

chore: bump istio from 1.8.2 to 1.9.1

---

stable/kommander/Chart.yaml
stable/kommander/charts/kommander-karma/Chart.yaml
stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
stable/kommander/charts/kommander-thanos/Chart.yaml
stable/kommander/charts/kommander-thanos/templates/secret.yaml
stable/kommander/requirements.lock
stable/kommander/requirements.yaml
stable/kommander/templates/kubecost/secret.yaml

Feature
In addition to existing `FederatedSecrets` with TLS certificate and key for `mtls-proxy` create also a local copy of server certificate data that can be used for local management cluster `mtls-proxy` instances.
https://jira.d2iq.com/browse/D2IQ-74659
```release-note
```
**Checklist**

[kommander] feat: create local secrets with server proxy certificates

---

stable/mtls-proxy/Chart.yaml
stable/mtls-proxy/templates/deployment.yaml
stable/mtls-proxy/values.yaml

Bug
Fixes indentation error that casues YAML parsing error when providing custom ENV variables:
```
YAML parse error on mtls-proxy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 44: block sequence entries are not allowed in this context
```
no issue
```release-note
NONE
```
**Checklist**

[mtls-proxy] fix: env values indentation

---

staging/traefik/Chart.yaml
staging/traefik/templates/init-cert-job.yaml
staging/traefik/templates/tests/test-certificate.yaml
staging/traefik/values.yaml

Feature
For kommander 2 we need to be able to change the default env vars for
the traefik init cert Job, this adds the ability to set values for the
Job's env vars via the chart.
In support of [D2IQ-74604](https://jira.d2iq.com/browse/D2IQ-74604)
```release-note
NONE
```
**Checklist**

D2IQ-74604 feat(traefik): allow overriding int cert vars

---

stable/kommander/Chart.yaml
stable/kommander/charts/kommander-karma/Chart.yaml
stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
stable/kommander/charts/kommander-thanos/Chart.yaml
stable/kommander/charts/kommander-thanos/templates/federated-addon.yaml
stable/kommander/requirements.lock
stable/kommander/requirements.yaml
stable/kommander/templates/kubecost/federated-addon.yaml

Chore
Bumps mtls-proxy chart to latest version 0.1.4
no issue
```release-note
bump the mtls-proxy to 0.1.4
```
**Checklist**

[kommander] chore: bump mtls-proxy version in kommander

---

staging/traefik/Chart.yaml
staging/traefik/templates/certificate.yaml

Bug
update the certificate template to check for the issuer value and
fallback to "kubernetes-ca" only if it is not set.
This is a follow-up to #1067 as I missed that issuer was also hard-coded in the certificate template.
```release-note
- allow traefik ca issuer to be set from a value, but default to kubernetes-ca if not set
```
**Checklist**

fix(traefik): use issuer value if available

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/templates/grafana/cronjob-home-dashboard.yaml

Bug
This backports #964 to prometheus-operator 9.3.x.
The copy of the script at `staging/prometheus-operator/patch/mesosphere/templates/grafana/cronjob-home-dashboard.yaml` is already updated.
```release-note
[prometheus-operator] Fixes the cronjob that sets the Grafana home dashboard.
```
**Checklist**

(release/prometheus-operator-9.3.x) use busybox sh instead of the no-longer-existing bash

---

Dispatchfile
staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/patch/mesosphere/patch/11_use_existing_storage_definitions.patch
staging/prometheus-operator/patch/patch_11_mesosphere_patch_storage.sh
staging/prometheus-operator/templates/NOTES.txt
staging/prometheus-operator/templates/alertmanager/alertmanager.yaml
staging/prometheus-operator/templates/prometheus/prometheus.yaml

bug
backports https://github.com/mesosphere/charts/pull/1038
If either prometheus or alertmanager resources exist and have a storage
attribute defined in their spec, reuse that instead of what's defined
in the values.
This prevents the accidental redefinition of the volumeClaimTemplate and
the abandonment of old data.
https://jira.d2iq.com/browse/COPS-6870
```release-note
Fixed an upgrade issue that occurred when upgrading from a prior chart version to a version >=9.3.0 and <=9.3.7 which had a bug where the desired PVC name prefix was being discarded. This bug caused upgrades to that version to create …
```

[release/prometheus-operator-9.3.x][BACKPORT] use existing storagespec

---

Dispatchfile
stable/kommander/Chart.yaml
stable/kommander/README.md

chore
Now, we run the publish job automatically on pushes to `release/*` branches so that we no longer need to manually run `make publish` on those branches on updates. This has been tested on this PR https://github.com/mesosphere/charts/pull/1104 going into `release/kommander-0.15.x` which ran the Dispatch publish job, resulting in the chart publish to `gh-pages` 🥳 https://github.com/mesosphere/charts/commit/f199f12d4b6c8bf1d34758c70828028c1ef902cc. FYI, for any other existing release branches, we still need to cherry-pick this Dispatchfile change to get this triggered on that branch. So far, this has been added to `release/kommander-0.15.x` and `release/prometheus-operator-9.3.x`
h/t @faiq for the help :D 
**Which …

chore: Update Dispatchfile to publish on release/* branches

---

stable/opsportal/Chart.yaml
stable/opsportal/templates/landing.yaml

Chore
nginx:1.18-alpine uses Alpine 3.11.11 which has a fix for CVE-2020-1971.
https://jira.d2iq.com/browse/D2IQ-75532
```release-note
Bump nginx version used for opsportal-landing, from 1.17-alpine to 1.18-alpine, for security reasons.
```
**Checklist**

chore: bump nginx for opsportal-landing

---

staging/kube-prometheus-stack/Chart.yaml
staging/kube-prometheus-stack/patch/mesosphere/patch/12_set_pathtype_only_when_supported.patch
staging/kube-prometheus-stack/patch/patch_12_set_pathtype_only_when_supported.sh
staging/kube-prometheus-stack/templates/_helpers.tpl
staging/kube-prometheus-stack/templates/alertmanager/ingress.yaml
staging/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml
staging/kube-prometheus-stack/templates/prometheus/ingress.yaml
staging/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml
staging/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml

bug
Setting pathType on an Ingress path is unsupported prior to k8s 1.16, supported in networking.k8s.io/v1beta1 with k8s 1.18, and required in networking.k8s.io/v1. Setting pathType only when it is supported allows using the same set of chart values across this range of k8s versions.
https://jira.d2iq.com/browse/D2IQ-75500
```release-note
[kube-prometheus-stack] Omits Ingress pathType when unsupported, preventing validation errors.
```
**Checklist**

[kube-prometheus-stack] Set pathType on Ingress only when supported

---

stable/kubecost/Chart.yaml
stable/kubecost/values.yaml

bug
CBP ran into issues with the kubecost cost-analyzer PVC size getting set to an extremely large number, which was reported in kubecost here: https://github.com/kubecost/cost-analyzer-helm-chart/issues/507. To resolve this, the team increased the default pv size from 0.2Gi (causes issues with some storage providers, in CBP case they use portworx, I think) to 32Gi. We originally avoided making this change due to concerns around upgrades whether the disk would handle automatic resizing with no loss of data, but Kubecost has a helpful doc on how to deal with such issues that we can reference in our upgrade docs as well https://github.com/kubecost/docs/blob/master/storage.md. The bulk of the data stored in this PVC is …

[kubecost] fix: Set default pvc size to 32Gi

---

staging/kube-prometheus-stack/Chart.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/grafana/dashboards/elasticsearchdashboard.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/grafana/dashboards/fluentbitdashboard.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/grafana/dashboards/grafanadashboard.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/grafana/dashboards/kibanadashboard.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/grafana/dashboards/localvolumeprovisioner.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/grafana/dashboards/opsportaldashboard.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/grafana/dashboards/traefikdashboard.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/grafana/dashboards/velerodashboard.yaml
staging/kube-prometheus-stack/templates/grafana/dashboards/mesosphere-dashboards/elasticsearchdashboard.yaml
staging/kube-prometheus-stack/templates/grafana/dashboards/mesosphere-dashboards/fluentbitdashboard.yaml
staging/kube-prometheus-stack/templates/grafana/dashboards/mesosphere-dashboards/grafanadashboard.yaml
staging/kube-prometheus-stack/templates/grafana/dashboards/mesosphere-dashboards/kibanadashboard.yaml
staging/kube-prometheus-stack/templates/grafana/dashboards/mesosphere-dashboards/localvolumeprovisioner.yaml
staging/kube-prometheus-stack/templates/grafana/dashboards/mesosphere-dashboards/opsportaldashboard.yaml
staging/kube-prometheus-stack/templates/grafana/dashboards/mesosphere-dashboards/traefikdashboard.yaml
staging/kube-prometheus-stack/templates/grafana/dashboards/mesosphere-dashboards/velerodashboard.yaml

chore
We renamed addons to platform services in konvoy 1.8
https://jira.d2iq.com/browse/D2IQ-76286
```release-note
NONE
```
**Checklist**

kube-prometheus-stack: Rename "Addons" to "Platform Services" in grafana dashboards

---

staging/velero/Chart.yaml
staging/velero/templates/backupstoragelocation.yaml

- fix(velero): Duplicate s3ForcePathStyle config key
- chore(velero): Bump chart version to 3.1.2
Bug
When specifying `s3ForcePathStyle`, the helm template renders a duplicate key which breaks with helm 3.6.0:
```bash
$ helm template m-staging/velero --set configuration.backupStorageLocation.config.s3ForcePathStyle=true 2>/dev/null | grep -B 1 s3ForcePathStyle 2>/dev/null
config:
s3ForcePathStyle: true
s3ForcePathStyle: "true"
```
```release-note
Fix duplicate keys in velero backupstoragelocation configuration.
```
**Checklist**

Fix velero chart for helm 3.6.0

---

staging/thanos-traefik/.helmignore
staging/thanos-traefik/Chart.yaml
staging/thanos-traefik/templates/_helpers.tpl
staging/thanos-traefik/templates/ingressroutetcp.yaml
staging/thanos-traefik/values.yaml
test/helm3/ct-e2e.yaml

Feature
This is a new chart that will be used by Kommander 2 to expose Thanos GRPC endpoint for metrics scraping from attached (managed) clusters. The traefik will be configured to perform TLS termination and verification.
https://jira.d2iq.com/browse/D2IQ-76605
```release-note
NONE
```
**Checklist**

feat: add thanos-traefik chart

---

stable/dex-controller/templates/certificates.yaml
stable/dex/Chart.yaml

CN is not used in any modern software for cert validation and
`dnsNames` is properly specified for validation. Using a fixed
CN here ensures cert-manager does not reject the Certificate.

fix: Use fixed CN for dex controller cert

---

stable/kubecost/Chart.yaml
stable/kubecost/templates/hooks-clusterid.yaml

Bug
If prometheus is disabled, we still want to run the cluster-info configmap creation job, just not the prometheus edit config job. Moved some conditionals so that if prometheus is disabled, we still run the cm create job.
```release-note
NONE
```
**Checklist**

kubecost: Fix prom job hooks

---

staging/nvidia/Chart.yaml
staging/nvidia/charts/nvidia-dcgm-exporter/templates/default-counters.yaml

Bug
It puts some commas and removes a blank comment line. `dcgm-exporter` requires all the lines should have two commas, even in the comments.
[D2IQ-78131](https://jira.d2iq.com/browse/D2IQ-78131)
```release-note
NONE
```
**Checklist**

Fix missing commas in dcgm-exporter configuration

---

staging/knative/Chart.yaml
staging/knative/charts/serving/Chart.yaml
staging/knative/charts/serving/templates/serving.yaml
staging/knative/charts/serving/values.yaml
staging/knative/requirements.yaml
staging/knative/values.yaml

chore
This is a follow-up PR for exposing GC configuration for Knative Serving https://github.com/mesosphere/charts/pull/1207. This PR exposes V2 GC settings which are more functional compared to the old GC and V2 GC becomes the default in the future versions of Knative Serving. Parameter names stay the same.
```release-note
NONE
```
**Checklist**

chore: add V2 GC configuration for Knative Serving

---

CODEOWNERS

Chore
Update CODEOWNERS to point to new github ui team

chore: update CODEOWNERS to point to new ui-team

---

staging/traefik-forward-auth/Chart.yaml
staging/traefik-forward-auth/templates/hooks.yaml

Bug
Bumping to TFA >3.0.0 caused below error in YAKCL https://github.com/mesosphere/yakcl/pull/438
```
auth/templates/hooks.yaml failed: Job.batch \"traefik-forward-auth-kommander-kubeaddons-session-key-pre-install\" is invalid: spec.template.labels: Invalid value: \"traefik-forward-auth-kommander-kubeaddons-session-key-pre-install\": must be no more than 63 characters"}
```
I did not find any examples of using `generateName` in our charts and an upstream issue https://github.com/helm/helm/issues/3348 so decided to go with the safer route and just shorten the name to something that will be <=63 characters
```
traefik-forward-auth-kommander-kubeaddons-sess-key-pre-install …
```

fix: shorten TFA hooks names

---

staging/kube-prometheus-stack/Chart.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/hooks/v9-to-v11-upgrade-part1.yaml
staging/kube-prometheus-stack/templates/mesosphere-hooks/v9-to-v11-upgrade-part1.yaml

bug
`crd-alertmanager.yaml` was renamed to `crd-alertmanagers.yaml` in chart version v11.0.0, but we didn't catch this change in any of our upgrade scripts so any users on v11+ will run into outdated alertmanager CRDs upon upgrading. I traced this back to any version including and over konvoy 1.6.2.
https://jira.d2iq.com/browse/COPS-6842
https://jira.d2iq.com/browse/D2IQ-79666
```release-note
[prometheus] Prometheus addon upgrades now upgrade the alertmanager CRD (COPS-6842)
```
**Checklist**

[release/kube-prometheus-stack-15.4.x] Fix alertmanager crd filename

---

staging/prometheus-operator/Chart.yaml
staging/prometheus-operator/patch/mesosphere/templates/hooks/v9-to-v11-upgrade-part1.yaml
staging/prometheus-operator/templates/mesosphere-hooks/v9-to-v11-upgrade-part1.yaml
staging/prometheus-operator/templates/mesosphere-hooks/v9-to-v11-upgrade-part2.yaml

bug
`crd-alertmanager.yaml` was renamed to `crd-alertmanagers.yaml` in chart version v11.0.0, but we didn't catch this change in any of our upgrade scripts so any users on v11+ will run into outdated alertmanager CRDs upon upgrading. I traced this back to any version including and over konvoy 1.6.2. I will backport this also to the affected `kube-prometheus-stack` versions used in 1.8.
Running the patch script also caught another hook update that hadn't been applied.
https://jira.d2iq.com/browse/COPS-6842
https://jira.d2iq.com/browse/D2IQ-79666
```release-note
[prometheus] Prometheus addon upgrades now …
```

[release/prometheus-operator-12.11.x] Fix alertmanager crd filename

---

stable/metallb/Chart.yaml
stable/metallb/templates/speaker.yaml

Bug
Duplicate keys cause Flux to fail, see https://github.com/fluxcd/helm-controller/issues/283 Additionally, the `node-role.kubernetes.io/master` will no longer be removed/lost in case when new tolerations are defined.
* https://jira.d2iq.com/browse/D2IQ-81473
```release-note
Defining custom tolerations for metallb speaker no longer results in removing/forgetting of `node-role.kubernetes.io/master` toleration.
```
**Checklist**

fix: remove duplicate tolerations keys for metallb chart

---

staging/velero/Chart.yaml
staging/velero/charts/minio/templates/_helpers.tpl
staging/velero/charts/minio/templates/ingress.yaml
staging/velero/charts/minio/templates/networkpolicy.yaml
staging/velero/crds/crds.yaml
staging/velero/files/crds.yaml

Chore
It modifies the `velero` chart to make it compatible with Kubernetes version 1.22
[D2IQ-82367](https://jira.d2iq.com/browse/D2IQ-82367)
NONE
**Checklist**

chore: update velero chart as per k8s 1.22

---

stable/kommander/Chart.yaml
stable/kommander/templates/grafana/cronjob-home-dashboard.yaml
staging/kube-prometheus-stack/Chart.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/grafana/cronjob-home-dashboard.yaml
staging/kube-prometheus-stack/templates/grafana/cronjob-home-dashboard.yaml

Bug
Adds the concurrency policy `Replace` configuration to the set home dashboards `CronJob` to avoid potentially creating an unbound number of pods if a pod is failing to start.
https://jira.d2iq.com/browse/COPS-7105
```release-note
NONE
```
**Checklist**

add concurrency limit to grafana home dashboard cronjob

---

staging/kube-prometheus-stack/Chart.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/grafana/cronjob-home-dashboard.yaml
staging/kube-prometheus-stack/templates/grafana/cronjob-home-dashboard.yaml

Bug
Adds the concurrency policy `Replace` configuration to the set home dashboards `CronJob` to avoid potentially creating unbound number of pods if a pod is failing to start.
https://jira.d2iq.com/browse/COPS-7105
```release-note
NONE
```
**Checklist**

[release/kube-prometheus-stack-15.4.x] kube-prometheus-stack: add concurrency limit to home dashboard cronjob

---

staging/velero/Chart.yaml
staging/velero/charts/minio/Chart.yaml
staging/velero/charts/minio/values.yaml
staging/velero/requirements.lock
staging/velero/requirements.yaml

Bump the minio images used in minio subchart (pulled into velero)
in order to mitigate CVE-2021-2128i7.
bug
Bump minio images to ones that include the fix for https://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-21287. Since this minio subchart is forked off an older/deprecated chart, I bumped it to the latest image used in that chart https://github.com/minio/charts/commit/032712dbd3a5cd717dcb524e3fcdf5eb85db8ab4#diff-5791b6226743c56f44f8274cc67b8beb9751b6403e697243ad00fd37af5635e3. It doesn't jump too many versions but still includes the CVE fix. 
https://jira.d2iq.com/browse/COPS-7134
```release-note …
```

[velero] fix: Bump minio subchart images to mitigate CVE-2021-2128i7

---

staging/gatekeeper/Chart.yaml
staging/gatekeeper/patch/templates/gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml
staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml
staging/gatekeeper/templates/gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml
staging/gatekeeper/values.yaml

bug
Missing a `sideEffects: None` in the `mutatingwebhookconfiguration` which is required for flux (komm 2.x). Adding `mutations.sideEffects` field to allow configuring `sideEffects` without potentially breaking backwards-compat with 1.x if gatekeeper ever needs to be bumped there. Default would still be to omit the field - we will set it when bumping to this version in 2.x
https://jira.d2iq.com/browse/COPS-7127
(on another note, the patch scripts are not really updated. doesn't look like they've been used for some time so some scripts are outdated. I've only run the one relevant patch I needed here which didn't break anything)
**Does this PR introduce …

[gatekeeper] fix: Allow configuring sideeffects

---

staging/kube-prometheus-stack/Chart.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/grafana/cronjob-home-dashboard.yaml
staging/kube-prometheus-stack/patch/patch_11_mesosphere_helpers.sh
staging/kube-prometheus-stack/patch/patch_6_mesosphere_values.sh
staging/kube-prometheus-stack/templates/_helpers.tpl
staging/kube-prometheus-stack/templates/grafana/cronjob-home-dashboard.yaml
staging/kube-prometheus-stack/values.yaml

bug
It looks like 2.x centralized-grafana was trying to hit `centralized-grafana-grafana` service instead of the actual service `centralized-grafana` in the cronjob. We were templating the service name to `{{ .Release.Name }}-grafana` which generally works, but I found that the grafana subchart defines its `fullname` like so:
https://github.com/grafana/helm-charts/blob/grafana-6.16.4/charts/grafana/templates/_helpers.tpl#L19-L20
```
{{- define "grafana.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
************{{- if contains $name .Release.Name -}}************
{{- .Release.Name | trunc 63 …
```

kube-prometheus-stack: Allow grafana svc name override in cronjob

---

stable/cert-manager-crds/Chart.yaml
stable/cert-manager-crds/Makefile
stable/cert-manager-crds/README.md
stable/cert-manager-crds/crds/cert-manager.crds.yaml

The chart provides `cert-manager` CRDs.
Feature
We don't want to rely on the upstream `cert-manager` chart to create and manage CRDs. We would like to keep the CRDs on the attached cluster even when `cert-manager` kommander app is uninstalled. Also, we would like to manage CRDs using flux. Both goals can be achieved by using to helmreleases in kommander `cert-manager` app - the upstream `cert-manager` chart and the chart provided in this PR.
https://jira.d2iq.com/browse/D2IQ-85306
The chart was tested in https://github.com/mesosphere/kommander-applications/pull/201 and https://github.com/mesosphere/kommander/pull/1453
**Does this PR introduce a …

feat: Provie cert-manager CRDs chart

---

staging/kube-prometheus-stack/Chart.yaml
staging/kube-prometheus-stack/patch/patch_6_mesosphere_values.sh

feat/chore
Discovered that we can use config to set home dashboard now, so we no longer need to use cronjobs to set the home dashboard, yay! Also bumped kubectl to 1.21.3 which looks to be the image mostly used in other kommander apps
https://jira.d2iq.com/browse/D2IQ-77877
```release-note
kube-prometheus-stack: Disable grafana home dashboard cronjob
```
**Checklist**

[kube-prometheus-stack] Disable grafana home dashboard cronjob

---

staging/istio/Chart.yaml
staging/istio/charts/prometheus-operator/Chart.yaml
staging/istio/charts/prometheus-operator/templates/servicemonitors.yaml
staging/istio/charts/prometheus-operator/values.yaml
staging/istio/requirements.lock
staging/istio/requirements.yaml

Feature
This allows setting custom servicemonitor labels in chart values. This allows us to update servicemonitor labels in response to changes in Prometheus configuration without modifying this chart.
```release-note
```
**Checklist**

[staging/istio] feat: Add servicemonitor labels chart value

---

stable/dex/Chart.yaml
stable/dex/templates/certificate.yaml
test/e2e-kind.sh

Bug
The hardcoded secret name "dex" will collide with the name of the config secret if the chart release is named "dex". This will lead to a failed chart install or upgrade if cert-manager creates the secret before Helm can.
https://jira.d2iq.com/browse/COPS-7193
I looked at updating the deployment to reflect the new cert secret name, but it already expects it by default: https://github.com/mesosphere/charts/blob/7e5e0248cef5bc23e5716a4f8d3a13c9145609b9/stable/dex/templates/deployment.yaml#L1-L3
So it looks like we'll also need to remove this line from the default dex chart config to receive this fix: …

[stable/dex] fix: Prevent name collision for config and cert secrets

---

staging/gatekeeper/Chart.yaml
staging/gatekeeper/patch/patch_2_upgrade_crds_job.sh
staging/gatekeeper/templates/crds.yaml
staging/gatekeeper/values.yaml
staging/velero/Chart.yaml
staging/velero/templates/install-crds.yaml
staging/velero/values.yaml

Bug and Feature
This updates charts so that their kubectl images can be set in chart values.
https://jira.d2iq.com/browse/D2IQ-84836
```release-note
[staging/gatekeeper] Fixes CRD jobs to use the kubectl image from chart values.
[staging/velero] Adds a `kubectlImage` chart value.
```
**Checklist**

[multiple charts] Use kubectl images from chart values

---

Dispatchfile
mergebot-config.json

chore
We need to move off Dispatch for this repo. I'm reusing the existing charts PR TC job (lint and test charts) that is triggered for PRs. I think we need to merge this PR to `master` to be able to test the mergebot config
https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_Konvoy_ChartPr?branch=&mode=builds
Also removed the publish job off Dispatch, and re-activated ths TC publish job: https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_Konvoy_Chart?branch=&buildTypeTab=overview&mode=builds#all-projects
https://jira.d2iq.com/browse/D2IQ-86436
```release-note
```
**Checklist**

build: Add mergebot config, move off Dispatch to TC

---

stable/kommander-cert-federation/Chart.yaml
stable/kommander-cert-federation/templates/cert-federation.yaml
stable/kommander-cert-federation/values.yaml

Because of how we ship the current `cert-federation` chart with a static version 0.0.1 - https://github.com/mesosphere/kommander/blob/main/chart/cert-federation/Chart.yaml#L7 recent changes (https://github.com/mesosphere/kommander/commits/main/chart/cert-federation/templates/cert-federation.yaml) have updated the chart here - https://github.com/mesosphere/kommander/blob/gh-pages/charts/cert-federation-v0.0.1.tgz (overwritten) even though we shipped the same chart in older versions of kommander. This is not desired as it effectively makes it an unknown of what "version" of the chart a customer is running as its updated (overwritten) with every change to that chart. 
This PR fixes above issue by adding this chart into …

feat: add kommander-cert-federation chart

---

stable/kommander-cert-federation/Chart.yaml
stable/kommander-cert-federation/templates/cert-federation.yaml
stable/kubecost/Chart.yaml
stable/kubecost/values.yaml
staging/kube-prometheus-stack/Chart.yaml
staging/kube-prometheus-stack/patch/patch_6_mesosphere_values.sh
staging/kube-prometheus-stack/values.yaml
staging/velero/Chart.yaml
staging/velero/templates/cleanup-crd.yaml
staging/velero/values.yaml
test/ct.yaml
test/helm3/ct-e2e.yaml
test/helm3/ct.yaml

chore
Minor bumps of kubectl 1.2x (most are 1.23, but at least one is 1.21). This is to catch CVE fixes in the build artifacts.
Partially fixes...
[D2IQ-90196](https://jira.d2iq.com/browse/D2IQ-90196)
[D2IQ-89723](https://jira.d2iq.com/browse/D2IQ-89723)
[D2IQ-90200](https://jira.d2iq.com/browse/D2IQ-90200)
[D2IQ-89801](https://jira.d2iq.com/browse/D2IQ-89801)
```release-note
NONE
```
**Checklist**

chore: Minor bump of kubectl 1.2x

---

staging/traefik-forward-auth/Chart.yaml
staging/traefik-forward-auth/templates/deployment.yaml
staging/traefik-forward-auth/values.yaml

Feature
Adds an option to use the OS trusted CAs for publicly trusted certificates (e.g. issued by Let's encrypt)
https://jira.d2iq.com/browse/D2IQ-89301
```release-note
```
**Checklist**

feat: traefik-forward-auth: support publicly (OS) trusted CAs

---

stable/kommander-cert-federation/Chart.yaml
stable/kommander-cert-federation/templates/cert-federation.yaml
stable/kubecost/Chart.yaml
stable/kubecost/values.yaml
staging/istio/Chart.yaml
staging/istio/values.yaml
staging/knative/Chart.yaml
staging/knative/charts/serving/values.yaml
staging/kube-prometheus-stack/Chart.yaml
staging/kube-prometheus-stack/patch/patch_6_mesosphere_values.sh
staging/kube-prometheus-stack/values.yaml
staging/velero/Chart.yaml
staging/velero/templates/cleanup-crd.yaml
staging/velero/values.yaml

chore
Bumps kubectl to 1.24.1 across all charts used by kommander-applications.
https://jira.d2iq.com/browse/D2IQ-90193
https://jira.d2iq.com/browse/D2IQ-90194
```release-note
NONE
```
**Checklist**

chore: Bump kubectl to 1.24.1

---

CODEOWNERS

We don't really use SIGs anymore - some have no users, some have one, they are all outdated. This is blocking PRs from getting merged, and oftentimes requires an admin to merge. For now, until we decide what we're doing with SIGs or decide how to tackle ownership of specific charts, let's add @mesosphere/kommander group as toplevel owner and remove SIGs from specific charts. The kommander team is owning the majority of applications, so I think this makes sense.
```release-note
```
**Checklist**

build: Add @mesosphere/kommander group to CODEOWNERS

---

staging/dex-k8s-authenticator/Chart.yaml
staging/dex-k8s-authenticator/templates/configmap.yaml
staging/dex-k8s-authenticator/templates/deployment.yaml
staging/dex-k8s-authenticator/templates/secret_hmac.yaml
staging/dex-k8s-authenticator/values.yaml

Feature
Allows to use helm to generate HMAC secret during the installation and store it as a secret. The generated value is mounted to `dex-k8s-authenticator` as an ENV variable and its not stored in the ConfigMap.
I've manually test that the value is correctly injected into the container by running a custom build of `dex-k8s-auth` that will print the HMAC secret:
```
KUBECONFIG=kubeconfig-mh-management kubectl -n kommander logs dex-k8s-authenticator-77dd9fffc-rd6xb
2022/06/27 15:50:16 Using config file: /app/configuration/config.yaml
2022/06/27 15:50:16 HMAC_SECRET: QjZqMFZMMER5dmtuRVVpMDlwaFVodDFIczd6SmM1SEQ=
2022/06/27 15:50:16 useClusterHostname: …
```

feat: store hmac as k8s secret for dex-k8s-auth

---

staging/dex-k8s-authenticator/Chart.yaml
staging/dex-k8s-authenticator/templates/configmap.yaml

Bug
When providing empty clusters list to `dex-k8s-authenticator` the ConfigMap ends with invalid YAML that cannot be parsed.
Example:
```
data:
config.yaml: |-
listen: http://0.0.0.0:5555
web_path_prefix: /
debug: false
pluginVersion:
useClusterHostnameForClusterName: false
clusters:
{}
```
```release-note
```
**Checklist**

fix: dka empty clusters renders invalid yaml

---

staging/istio/Chart.yaml
staging/istio/crds/crd-operator.yaml
staging/istio/templates/deployment.yaml
staging/istio/templates/service.yaml
staging/istio/values.yaml

feat
When bumping kiali to the latest, I got a warning that it required istio 1.14+, so bumping istio to latest here https://github.com/istio/istio/tree/1.14.1/manifests/charts/istio-operator
```release-note
```
**Checklist**

feat: Bump istio to 1.14.1

---

.github/workflows/stacked-prs.yml

Chore
Adds Stacked PRs support to the repository. This workflow allows us to create a chain of PRs that are dependent on each other.  Instead of one big PR. 
--
--
--
**Checklist**

ci: add stacked PR support

---

.github/workflows/ct.yaml
Makefile

CI
Fixes ct lint command.
--
This is a quick fix that focuses on fixing CI first.  It assumes `yamllint` and `yamale` packages should be installed locally for now. 
--
**Checklist**

fix: use correct config for ct lint

---

.github/workflows/ct.yaml

Bug
Chart testing workflow was running on `master` instead of the PR branch it should run on.
https://d2iq.atlassian.net/browse/D2IQ-94277
```release-note
```
**Checklist**

fix: chart testing workflow running on master instead of PR branch

---

Makefile

CI
The `publish` make target grabs the latest commit message to use for publishing charts to gh pages.
If the last commit contains double quotes, the publish will fail (See this commit 9adbd8945f08f826f46bf0ab372dda975a82226e)
```release-note
```
**Checklist**

ci: escape double quotes in commit message

---

.github/workflows/stale-prs.yaml

feat
Add workflow to close stale PRs (30 days of inactivity)
```release-note
```
**Checklist**

ci: Add stale prs workflow

---

stable/dex/Chart.yaml
stable/dex/templates/secret.yaml
stable/dex/values.yaml

Feature
I set the `lazyInitConnectors` field in the default desired dex configuration in https://github.com/mesosphere/kommander-applications/pull/934. However, since the helm chart values.yaml did not support the field, the field was not rendered in the actual dex configuration.
This PR updates the helm chart.
https://d2iq.atlassian.net/browse/D2IQ-95346
* Add support for the `lazyInitConnectors` dex configuration field to the values.yaml.
* Change the default image to the d2iq fork, because upstream dex does not yet support the `lazyInitConnectors` field.
```release-note
Adds support for the …
```

feat: Bump dex to 2.11.0

---

staging/knative/Chart.yaml
staging/knative/PATCHES.md
staging/knative/charts/serving/Chart.yaml
staging/knative/charts/serving/templates/serving-core.yaml

Feature
Current PDB policies for knative serving activator and webhook make it impossible to run through upgrades when the corresponding HPA is not doing anything. In an ideal world, there will be ton of workloads which makes the HPA put up more pods and thus the current `minAvailable: 80%` might make sense. But most of the upgrades are run during downtime and in these scenarios HPA is not reliable to satisfy the `minAvailable: 80%` policy on PDB. 
This PR relaxes the PDB to instead use `maxUnavailable: 1` so that we can evict all pods when deployment has just 1 replica.
https://d2iq.atlassian.net/browse/D2IQ-96590
**Does this PR introduce a …

feat: relax PDB for knative-serving activator and webhook

---

staging/knative/Chart.yaml
staging/knative/charts/eventing/Chart.yaml
staging/knative/charts/eventing/templates/eventing.yaml
staging/knative/charts/serving/Chart.yaml
staging/knative/charts/serving/templates/serving-core.yaml

Bumps knative charts to not use deprecated v2beta2 as its no longer supported in k8s 1.26+
Partially address https://d2iq.atlassian.net/browse/D2IQ-96638 
```release-note
```
**Checklist**

feat: bump v2beta2 HPA to v2 in knative

---

.github/workflows/ct.yaml
.github/workflows/publish.yml

- ci: Upgrade asdf install action to v2
- ci: Use forked asdf parse versions
Otherwise this will break GHA once set-output is removed at end of May.

ci: Update out of date actions

---

staging/knative/Chart.yaml

This PR bumps the knative serving version chart in the parent knative chart.
```release-note
```
**Checklist**

fix: bump knative serving version to v1.10.2

---

staging/knative/Chart.yaml
staging/knative/charts/serving/Chart.yaml
staging/knative/charts/serving/templates/net-istio.yaml

Bug
This PR fixes the error in the net-istio-webhook pod:
```
panic: failed to convert the environment variable "WEBHOOK_PORT" : strconv.Atoi: parsing "tcp://10.97.172.47:9090": invalid syntax
goroutine 1 [running]:
knative.dev/pkg/webhook.PortFromEnv(0xc000084730?)
knative.dev/pkg@v0.0.0-20230418073056-dfad48eaa5d0/webhook/env.go:44 +0x125
main.main()
knative.dev/net-istio/cmd/webhook/main.go:84 +0x7c
```
I have no idea why the `WEBHOOK_PORT` is set to that value, It's not defined on the deployment at all so it should use the default of `8443`. It was made configurable in https://github.com/knative-sandbox/net-istio/commit/8a63e68aa04c6fa25e227d6f48ba73c397f28ca4 but that sets it to the default port if the env var isn't …

fix(knative): Set WEBHOOK_PORT on net-istio-webhook deployment

---

Makefile

bug
discovered a bug in the publish target when the job failed on latest change to publish the KPS chart, which added the subchart tarballs to .gitignore and requires `helm dep update` to run when packaging to include it. the envvars (which sets `HELM_DEP_UPDATE` to true) were not actually getting passed into the command.
```
Error: found in Chart.yaml, but missing in charts/ directory: kube-state-metrics, prometheus-node-exporter, grafana, prometheus-windows-exporter
```
```release-note
```
**Checklist**

fix(publish): Actually pass in env vars to command

---

staging/kube-prometheus-stack/Chart.yaml
staging/kube-prometheus-stack/patch/mesosphere/templates/ingress-rbac/grafana.yaml
staging/kube-prometheus-stack/templates/ingress-rbac/grafana.yaml

bug
backports https://github.com/mesosphere/charts/pull/1448 into previous KPS release (for dkp 2.5)
https://d2iq.atlassian.net/browse/D2IQ-98716
```release-note
```
**Checklist**

fix: add required flag to be able to view grafana dashboard

---

stable/cert-manager-crds/Chart.yaml
stable/cert-manager-crds/Makefile
stable/cert-manager-crds/crds/cert-manager.crds.yaml

Needed for bumping cert-manager to v1.12.3 - See https://github.com/mesosphere/kommander-applications/pull/1604
```release-note
```
**Checklist**

feat: bump cert-manager to v1.12.3

---

hack/charts/publish.sh
stable/dex/Chart.yaml
staging/dex-k8s-authenticator/Chart.yaml

This PR fixes an issue when more than one chart is modified and passed to Helm for linting. Now, the space between those is no longer interpreted as a part of the path. 
The failure: https://github.com/mesosphere/charts/actions/runs/6637202644
Previous behavior:
```
▶ installing helm
helm 3.10.1 is already installed
▶ installing helm-ct
helm-ct 3.7.1 is already installed
▶ publishing charts
================================================================================
Finding changed charts
================================================================================
Adding stable/dex to charts list
Adding staging/dex-k8s-authenticator to charts list
================================================================================
Linting charts …
```

fix: multiple chart linting failing

---

stable/cert-manager-crds/Chart.yaml
stable/cert-manager-crds/Makefile
stable/cert-manager-crds/crds/cert-manager.crds.yaml

Feature
Bumps cert-manager to v1.13.1
```release-note
```
**Checklist**

feat: bump cert-manager to v1.13.1

---

stable/object-bucket-claim/Chart.yaml
stable/object-bucket-claim/README.md
stable/object-bucket-claim/templates/object-bucket-claim.yaml
stable/object-bucket-claim/values.yaml

Bug
Autoremoval of completed jobs as triggered by the `ttlSecondsAfterFinished` interferes with proper functioning of the Helm controller in two ways:
- when the Job somehow gets removed before the controller manages to check for its completion, the controller fails reconciliation of the corresponding HelmRelease
- a rollback to remediate a failed upgrade will fail if the versions have different immutable fields (`podTemplateSpec`, etc), as the rollback attempt normally happens before the Job is deleted
This PR makes Helm execute this Job as a Helm hook, similarly to how all other Jobs in `mesosphere/charts` are managed. In addition, to avoid a potential collision with the old non-hook version of the chart, the Job is …

fix: convert the `object-bucket-claim` Job into a Helm hook

---

.github/workflows/publish.yml

Bug
MERGEBOT_TOKEN is no longer valid (and should be redundant)
The `publish` workflow
Not tested; it might be necessary to add more write permissions to GITHUB_TOKEN (I don't see what they are)
```release-note
NONE
```
**Checklist**

fix: use GITHUB_TOKEN to publish charts

---

staging/kube-oidc-proxy/Chart.yaml
staging/kube-oidc-proxy/templates/deployment.yaml
staging/kube-oidc-proxy/values.yaml

Feature
In order to use [maintained](https://github.com/TremoloSecurity/kube-oidc-proxy) and updated `kube-oidc-proxy` version we'd need to specify path to CA certs in container as a KOP flag.
https://d2iq.atlassian.net/browse/D2IQ-100007
```release-note
```
**Checklist**

feat(kube-oidc-proxy): add option to specify system CA certs path

---

stable/cert-manager-crds/Chart.yaml
stable/cert-manager-crds/Makefile
stable/cert-manager-crds/crds/cert-manager.crds.yaml

1.15.0 cert-manager has upstream bug and fix hasn't merged yet: https://github.com/cert-manager/cert-manager/pull/7108
https://jira.nutanix.com/browse/NCN-100545
```release-note
```
**Checklist**

feat: bump `cert-manager` to 1.14.7

---

staging/knative/Chart.yaml
staging/knative/charts/serving/crds/serving-crds.yaml
staging/knative/charts/serving/templates/pre-upgrade-hook.yaml

Bug
* Flux cannot upgrade between 1.10.4 and latest version because of the missing `v1alpha1` version for `domainmappings` resources.
* It is necessary to disable more webhooks to get error free upgrades
https://jira.nutanix.com/browse/NCN-104372
```release-note
```
**Checklist**

fix(knative): add missing domainmappings v1alpha1 version

---

staging/thanos-traefik/Chart.yaml
staging/thanos-traefik/templates/ingressroutetcp.yaml

Remove use of deprecated Traefik k8s APIs [thanos-traefik]
https://jira.nutanix.com/browse/NCN-104783

feat: remove deprecated thanos traefik api

---

stable/cosi/Chart.yaml
stable/cosi/README.md
stable/cosi/crds/apiextensions.k8s.io_v1_customresourcedefinition_bucketaccessclasses.objectstorage.k8s.io.yaml
stable/cosi/crds/apiextensions.k8s.io_v1_customresourcedefinition_bucketaccesses.objectstorage.k8s.io.yaml
stable/cosi/crds/apiextensions.k8s.io_v1_customresourcedefinition_bucketclaims.objectstorage.k8s.io.yaml
stable/cosi/crds/apiextensions.k8s.io_v1_customresourcedefinition_bucketclasses.objectstorage.k8s.io.yaml
stable/cosi/crds/apiextensions.k8s.io_v1_customresourcedefinition_buckets.objectstorage.k8s.io.yaml
stable/cosi/templates/apps_v1_deployment_container-object-storage-controller.yaml
stable/cosi/templates/rbac.authorization.k8s.io_v1_clusterrole_container-object-storage-controller-role.yaml
stable/cosi/templates/rbac.authorization.k8s.io_v1_clusterrolebinding_container-object-storage-controller.yaml
stable/cosi/templates/rbac.authorization.k8s.io_v1_role_container-object-storage-controller.yaml
stable/cosi/templates/rbac.authorization.k8s.io_v1_rolebinding_container-object-storage-controller.yaml
stable/cosi/templates/v1_namespace_container-object-storage-system.yaml
stable/cosi/templates/v1_serviceaccount_container-object-storage-controller-sa.yaml
stable/cosi/upgrade_operator.sh

Adding a cosi helm chart which will be consumed by CAREN
https://jira.nutanix.com/browse/NCN-104827
```
~/git/output/daily ❯ k get crds|grep objectstorage                                                                                                13:53:53
bucketaccessclasses.objectstorage.k8s.io                                        2024-12-18T21:47:13Z
bucketaccesses.objectstorage.k8s.io                                             2024-12-18T21:47:13Z
bucketclaims.objectstorage.k8s.io                                               2024-12-18T21:47:13Z
bucketclasses.objectstorage.k8s.io                                              2024-12-18T21:47:13Z
buckets.objectstorage.k8s.io …
```

feat: add cosi helm chart

---

hack/charts/publish.sh

Bug
Run deps download before linting to avoid issues with `kube-prometheus-stack` publishing.
```release-note
```
**Checklist**

fix: download deps before linting

---

stable/cosi/Chart.yaml
stable/cosi/templates/apps_v1_deployment_container-object-storage-controller.yaml
stable/cosi/values.yaml

Feature
Latest stable version from https://console.cloud.google.com/gcr/images/k8s-staging-sig-storage/GLOBAL/objectstorage-controller?inv=1&invt=Abk6pA
Also made these as values.  
```release-note
```
**Checklist**

feat: update update COSI image to latest

---

stable/cosi-bucket-kit/Chart.yaml
stable/cosi-bucket-kit/templates/bucketaccessclasses.yaml
stable/cosi-bucket-kit/templates/bucketaccesses.yaml
stable/cosi-bucket-kit/templates/bucketclaims.yaml
stable/cosi-bucket-kit/templates/bucketclasses.yaml
stable/cosi-bucket-kit/templates/ceph-provider.yaml
stable/cosi-bucket-kit/values.yaml

chore: update the `cosi-bucket-kit` chart such that:
- It can be disabled easily with a top level boolean
- Nest all the fields in values.yaml inside a new top level `cosi-bucket-kit` key.  
This makes it easy to deploy the cosi-bucket-kit as a chart inside other components (harbor etc.,)
https://jira.nutanix.com/browse/NCN-105274
Linter is expected to fail cuz upgrades will break from previous version to current version. This is fine cuz the chart is in alpha version and is not used anywhere yet.
```release-note
```
**Checklist**

feat: allow disabling cosi-bucket-kit chart easily

---

stable/kommander-cert-federation/Chart.yaml
stable/kommander-cert-federation/templates/cert-federation.yaml
stable/kommander-cert-federation/values.yaml

chore
bump kubefed version to v0.11.1
```release-note
```
**Checklist**

chore: kubefed version to v0.11.1

---

stable/cosi-bucket-kit/Chart.yaml
stable/cosi-bucket-kit/templates/job-readiness.yaml
stable/cosi-bucket-kit/values.yaml

Add a cosi secret transformer for harbor
```release-note
```
**Checklist**

feat: add cosi transformer for harbor and kubecost

---

staging/cosi-driver-nutanix/Chart.yaml
staging/cosi-driver-nutanix/templates/_helpers.tpl
staging/cosi-driver-nutanix/templates/deploy.yaml
staging/cosi-driver-nutanix/templates/rbac.yaml
staging/cosi-driver-nutanix/templates/sa.yaml
staging/cosi-driver-nutanix/templates/secret.yaml
staging/cosi-driver-nutanix/values.yaml

Bug
We need to template resource names to prevent resource clashing and make them distinguishable.
no issue
```release-note
```
**Checklist**

fix: Template resource names of cosi nutanix driver

---

stable/cosi-bucket-kit/Chart.yaml
stable/cosi-bucket-kit/templates/job-readiness.yaml

This fixes a bug that I recently introduced in the parsing of the BucketInfo value in the COSI secret. This commit refactors the fetching of the BucketInfo JSON so it does that only once and then parses the values from that JSON rather than fetching the secret for every field.
```release-note
```
**Checklist**

fix(cosi-bucket-kit): Correctly parse BucketInfo

---

stable/cosi-bucket-kit/Chart.yaml
stable/cosi-bucket-kit/templates/job-readiness.yaml

Tested with following json contents:
```bash
❯ echo '{"metadata": {"name": "valid"},"spec":{"secretS3":{"region":"us-east-1"}}}' | jq -r 'if (.spec.secretS3.region // "") == "" then "none" else .spec.secretS3.region end'                                                                       13:18:04
us-east-1
❯ echo '{"metadata": {"name": "valid"},"spec":{"secretS3":{"region":""}}}' | jq -r 'if (.spec.secretS3.region // "") == "" then "none" else .spec.secretS3.region end'                                                                                13:18:31
none
❯ echo '{"metadata": {"name": "valid"},"spec":{"secretS3":{"foo-region":""}}}' | jq -r 'if (.spec.secretS3.region // "") == "" then "none" else .spec.secretS3.region end' …
```

fix: parse region in BucketInfo correctly

---

staging/cilium-hubble-relay-traefik/.helmignore
staging/cilium-hubble-relay-traefik/Chart.yaml
staging/cilium-hubble-relay-traefik/templates/_helpers.tpl
staging/cilium-hubble-relay-traefik/templates/ingressroutetcp.yaml
staging/cilium-hubble-relay-traefik/values.yaml
test/helm3/ct-e2e.yaml

Feature
This chart is used to route requests from outside the cluster to the Cilium Hubble Relay service.
https://jira.nutanix.com/browse/NCN-105953
* The chart is safe to install, even if Cilium Hubble Relay is not running on the cluster.
* Because the chart requires traefik CRDs, it is excluded from the ct-e2e
tests.
* The chart will be installed by a kommander application.
```release-note
```
**Checklist**

feat: Add cilium-hubble-traefik chart

---

staging/cilium-hubble-relay-traefik/Chart.yaml
staging/cilium-hubble-relay-traefik/templates/ingressroutetcp.yaml
staging/cilium-hubble-relay-traefik/values.yaml

Bug
The default traefik configuration requires routes to be in the same namespace as their service. Previously, we deployed the route in the kommander namespace.
```release-note
```
**Checklist**

fix: In cilium-hubble-relay-traefik, deploy IngressRouteTCP in the Service namespace

---

staging/docker-registry/Chart.yaml
staging/docker-registry/patch/nutanix/patch_5_update_syncer_image.patch
staging/docker-registry/values.yaml

Bug
Follow up to https://github.com/mesosphere/charts/pull/1578 to set a stable tag for the regsync image.
```release-note
```
**Checklist**

fix: set a release tag for docker-registry regsync image

---

stable/kommander-cert-federation/Chart.yaml
stable/kommander-cert-federation/templates/cert-federation.yaml

Bug
```bash
kubectl logs -n kommander deployment/prometheus-traefik-certs-kommander-cert-federation patch-secret
+ echo 'ensuring federatedsecret kommander-thanos-server-tls does not exist'
ensuring federatedsecret kommander-thanos-server-tls does not exist
+ kubectl delete federatedsecret kommander-thanos-server-tls --ignore-not-found=true
federatedsecret.types.kubefed.io "kommander-thanos-server-tls" deleted
E0512 12:38:01.555782       8 reflector.go:166] "Unhandled Error" err="k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *unstructured.Unstructured: federatedsecrets.types.kubefed.io \"kommander-thanos-server-tls\" is forbidden: User \"system:serviceaccount:kommander:prometheus-traefik-certs-komman …
```

fix: Add watch federatedsecret capability to cert federation role

---

staging/docker-registry/Chart.yaml
staging/docker-registry/patch/nutanix/patch_3_sync_data_across_instances.patch
staging/docker-registry/templates/_helpers.tpl

Bug
Fixing the regsync sidecar container to properly support registries with TLS enabled.
1. Using `127.0.0.1:5000` instead of `0.0.0.0:5000` as a target because having 0.0.0.0 in a cert SANs is not recommended.
2. Adding the CA from the TLS secret to `/etc/docker/certs.d/` 
Tested on a live cluster:
```
kubectl logs -n registry-system cncf-distribution-registry-docker-registry-1 -c docker-registry-syncer -f
time=2025-05-14T15:53:06.296Z level=INFO msg="Image sync needed" source=cncf-distribution-registry-docker-registry-0.cncf-distribution-registry-docker-registry-headless.registry-system.svc.cluster.local:5000/library/nginx:dkoshkin target=127.0.0.1:5000/library/nginx:dkoshkin
time=2025-05-14T15:53:06.306Z level=INFO …
```

fix: registry syncer with TLS

---

staging/docker-registry/Chart.yaml
staging/docker-registry/patch/nutanix/patch_3_sync_data_across_instances.patch
staging/docker-registry/templates/_helpers.tpl

Bug
In https://github.com/mesosphere/charts/pull/1582 I fixed it when TLS is enabled, but broke it when not enabled.
```release-note
```
**Checklist**

fix: registry syncer without TLS

---

staging/docker-registry/Chart.yaml
staging/docker-registry/patch/nutanix/patch_2_support_statefulset.patch
staging/docker-registry/templates/service-headless.yaml

Bug
The port here needs to match the targetPort, in order for things like kubectl port-forward to work correctly.
```release-note
```
**Checklist**

fix: registry headless service port

---

staging/registry-syncer/Chart.yaml
staging/registry-syncer/README.md
staging/registry-syncer/templates/_helpers.tpl
staging/registry-syncer/templates/configmap-deployment.yaml
staging/registry-syncer/templates/configmap-job.yaml
staging/registry-syncer/templates/deployment.yaml
staging/registry-syncer/templates/job.yaml
staging/registry-syncer/values.yaml

Feature
Adds a chart to sync OCI artifacts across registries with https://regclient.org/usage/regsync/.
This will be used for the AGF feature to sync OCI artifacts between the management and workload clusters. I've kept the chart flexible enough though where it can be used to sync across any registries.
Tested locally:
```
$ helm install registry-syncer-0197a434-b175-76c0-a016-5d3ffc2ee3e4 /Users/dimitri.koshkin/src/github.com/mesosphere/charts/staging/registry-syncer -f /Users/dimitri.koshkin/src/github.com/mesosphere/charts/staging/registry-syncer/nkp-values.yaml --namespace dk-agf-syncer-chart-wrkld-d94q7
NAME: registry-syncer-0197a434-b175-76c0-a016-5d3ffc2ee3e4
LAST DEPLOYED: Wed Jun 25 08:36:43 2025
NAMESPACE: …
```

feat: add registry-syncer chart

---

staging/dex-k8s-authenticator/Chart.yaml
staging/dex-k8s-authenticator/templates/configmap.yaml
staging/dex-k8s-authenticator/templates/configmap_templates.yaml

label validation in dex-k8s-authenticator
```
Helm install failed for release kommander/dex-k8s-authenticator with chart dex-k8s-authenticator@1.4.1+dd5ad60c48ad: failed to create resource: ConfigMap "dex-k8s-authenticator" is invalid: metadata.labels: Invalid value: "dex-k8s-authenticator-1.4.1+dd5ad60c48ad":
a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```
```release-note
``` …

fix: label validation in dex-k8s-authenticator
